### ISSUE TITLE
suggestion: if the "gift" card is know show what it is when mouse is over it

### ISSUE THREAD

**Issue by KayaTheRock** [Epix37/Hearthstone-Deck-Tracker#1985] opened 2016-01-14 19:36 UTC
Hello

If the card that the opponent received from the board is a known card such as coin (there are much more known received cards) highlight it and show it if the mouse is over it.  

Thanks

**Comment by jleclanche** [comment] 2016-03-25 16:25
Dupe of #2224

**Closed by jleclanche** 2016-03-25 16:25 UTC
