### ISSUE TITLE
Issues while streaming Hearthstone on Twitch with OBS

### ISSUE THREAD

**Issue by alphaesport** [Epix37/Hearthstone-Deck-Tracker#1961] opened 2016-01-06 15:15 UTC
Hello guys,
I stream Hearthstone via Twitch. When I use HDT while streaming via Windowcapture in OBS I have serious lag on stream. 
I have 100 mbit down and 5 mbit upload. 
My Computer should not be the problem.

I tried to stream with lower bitrate / low FPS ( 1250/25) instead of 2000/30 and 720p instead of 1080p but i had still heavy lag. i also set updatedelay in config file from 100 to 1000.

Game and HDT run normal while streaming.

Sry for my bad english and thanks for help.

**Comment by MechaLynx** [comment] 2016-01-06 16:40
I can't replicate this and it's unclear what the problem is. I can preview a window capture with HDT overlayed while playing and there's nothing abnormal about it.

If your bitrate is the same in the settings, have you checked OBS to see if it actually remains stable? It's possible this is related to your OBS config rather than HDT (are you sure it isn't monitor capture? that one is terrible and may cause lots of lag). If you're running Hearthstone in fullscreen and aren't watching OBS actively, it might be better to test it in windowed mode to check what the actual bitrate is and what it's doing.

In order to make sure this isn't OBS, please paste the profile you're using [here](https://www.pastebin.com). __Make sure you remove your stream key before posting the link!__. You can also just copy your settings manually. Please include the capture source settings if you do so.

Also, it's important to know the OS and (assuming it's Windows) whether you're using Aero or not.

**Comment by alphaesport** [comment] 2016-01-06 17:26
Thx mate. Ur advice to try it in Windowed mode was great. My issues came from gamecapturing HS.

Could you explain Aero to me?
There is a checkbox in my Video-Settings but I cant click it bec its greyed out. 
It says: "Aero-Overlay deactivating at the start [ ] " (translated)
Is that what u mean?

**Comment by MechaLynx** [comment] 2016-01-06 17:47
Game capture should work fine, except the HDT overlay would not be visible. Game capture is what I use normally and it had the same exact behavior. Your settings were probably at fault. Also, you stated you _were_ using window capture in the first place.

Anyway, Aero is part of the windowing manager (it's what makes your windows glassy and shit). You can have OBS disable it from video settings but that's it, from the setting you mentioned. What OS are you running? It's weird that it's greyed out.

If you are sure this isn't a problem related to HDT, please close this issue.

**Closed** 2016-01-11 11:00 UTC
