### ISSUE TITLE
Suggestion: Play order indicators for minions

### ISSUE THREAD

**Issue by markipoli** [Epix37/Hearthstone-Deck-Tracker#2026] opened 2016-01-28 15:37 UTC
I play mill rogue whenever it is viable (Mostly only in tavern brawls) and it is vitally important to know the play order of the cards to see which survive Vanish (Go back to the hand instead of being destroyed) with an almost full hand (The oldest ones survive). Could you maybe have an optional feature to put a number next to each minion to show what ones are the oldest? Thanks.

**Comment by Epix37** [comment] 2016-01-29 07:50
Along the lines of #142 - I thought about this before, should be added eventually. It's a good idea.

**Comment by Cu8eR** [comment] 2016-01-29 13:22
+1, really good idea

**Comment by tknights2015** [comment] 2016-01-31 21:52
A really, really good idea

**Comment by Epix37** [comment] 2016-03-31 21:53
Duplicate of #1031

**Closed by Epix37** 2016-03-31 21:53 UTC
Labels: enhancement
