### ISSUE TITLE
HDT stops recording games as the day changes (from 11:59PM to 00:00AM)

### ISSUE THREAD

**Issue by LordHMX** [Epix37/Hearthstone-Deck-Tracker#1553] opened 2015-10-03 05:55 UTC
I've been having this issue since the last update, HDT just stops recording games after the real time clock hits 00:00 AM.

Restarting HDT seems to fix the issue but it's coming back everyday.

**Comment by veri745** [comment] 2015-10-14 03:23
This definitely seems to have merit

![midnight](https://cloud.githubusercontent.com/assets/5815066/10474165/f99e4288-71f8-11e5-97bd-921c1f011a77.PNG)

**Comment by Epix37** [comment] 2015-10-14 06:16
Might be related to [this](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/LogReader/LogLineItem.cs#L17), which is supposed to deal with day changes, since the logs do not contain any date information in the timestamp. Not sure why yet though.

**Comment by culinko** [comment] 2015-10-14 07:02
Maybe some kind of AM/PM issue?

**Comment by Epix37** [comment] 2015-10-19 00:28
Possibly also fixed with v0.12.2?

**Comment by LordHMX** [comment] 2015-10-19 04:12
Just tested it, same issue. Started a game at 11:56pm and ended at 12:08am. 

It's different for me in the sense that nothing gets recorded at all, I don't even see it in the Statistics window.

If I close/restart the app then everything comes back to normal.

**Comment by thaweed** [comment] 2015-10-29 16:06
I am having this exact issue and it is quite disturbing since i am playing my few games during the day change mostly. Is there anything we can provide to further debug the issue? Might this be related to windows timesettings in any way?

**Comment by veri745** [comment] 2015-10-30 05:06
Appears to be 100% reproducible.  Every midnight that I play, I notice the games stop being recorded properly.  Sometimes the overlay gets messed up, and the games get recorded as casual instead of ranked.

**Comment by ceceita** [comment] 2015-11-04 13:34
i think this bug is still present , on new day overlay stop working ...  closing and opening hdt fix it

**Comment by irufus** [comment] 2015-12-15 23:52
If this was never addressed I will take a look into it.

**Comment by Epix37** [comment] 2015-12-16 07:54
@irufus this has not been fixed, no. I looked into it a while ago and found that the PowerLogReader stops working, but others (I think Bob specifically in this case) don't. No idea what to make of that.

**Comment by ceceita** [comment] 2015-12-16 16:42
didn't have the problem in last period ...
btw i noticed logs whitouts problem dont have the 00.00.00 timer action

**Comment by Epix37** [comment] 2016-03-09 09:30
I can't seem to reproduce this issue, but I have a reasonable idea what the problem is: [FileInfo.LastWriteTime  returns the time the file was started to be written to, rather than the last something was appended](http://stackoverflow.com/questions/1448716/net-fileinfo-lastwritetime-fileinfo-lastaccesstime-are-wrong).

Could you guys give this version a shot: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.15_PRE1

**Comment by zedor** [comment] 2016-03-09 15:51
I'll try it out tonight (I can possibly fiddle with the windows date/time but whatevs)

**Comment by zedor** [comment] 2016-03-09 23:29
Seems to work! But there was an issue with the tracker in the game right after day switch: http://puu.sh/nAUbO/6563f6f45b.png . The tracking went haywire, showing what I draw but not graying it out. I only use HDT for the stats and don't know if this was connected to your prerelease/dayswitch, but I thought I might aswell mention it.

**Closed** 2016-03-25 15:36 UTC
Labels: bug
