### ISSUE TITLE
Last Played opponent missing = Game not tracked

### ISSUE THREAD

**Issue by MorallyGreybeard** [Epix37/Hearthstone-Deck-Tracker#1478] opened 2015-09-14 23:54 UTC
Noticed this a few times tonight, whenever the last opponent played doesn't show up on the friends tab the game isn't logged either.  Is there a way to save the last replay or assign it to a game in the log window?

**Comment by veri745** [comment] 2015-09-15 03:59
I didn't put it together until I saw this issue, but this has been happening to me as well.

**Comment by Epix37** [comment] 2015-09-15 06:47
Nice observation. Depening on what the underlying problem is, that might be fixable.

After you had a game like that (not recorded, no last played name) please post the following files here:
* From "Hearthstone/Logs" (**before closing hearthstone**)
  * "Power.log"
  * "Bob.log"
* "%AppData%/HearthstoneDeckTracker/Logs/hdt_log.txt" (`options > tracker > settings > open appdata folder`)


http://pastebin.com/

**Comment by veri745** [comment] 2015-09-16 04:16
I played 6 games with a paladin deck, against

 * Druid - loss
 * Warlock - win
 * Mage - win
 * Warlock - win
 * Priest - win
 * Paladin - win
The game vs the priest was not tracked

Requested files:

HDT log: http://pastebin.com/GkBcx8i5
Bob log: http://pastebin.com/dFB2jHt7
Power log: too large for pastebin

**Comment by veri745** [comment] 2015-09-16 04:21
Relevant selection from the HDT log:
http://pastebin.com/ihJagsuF

It looks like it didn't track the turns correctly and discarded the game

**Comment by veri745** [comment] 2015-09-16 06:50
Another example of a game being discarded as a "DiscardZeroTurnGame"

Also vs Priest

http://pastebin.com/UTPawCUd

**Comment by Epix37** [comment] 2015-09-16 06:52
Could you upload the power.log somewhere? (http://www.zippyshare.com/ for example)
That's the one I really need to have a look at.

But this does seem like it might be fixable.

**Comment by veri745** [comment] 2015-09-16 06:54
This is my most recent Power.log.  I have the first one saved as well if you need to see that:
http://www10.zippyshare.com/v/ASG5IXXw/file.html

**Comment by Epix37** [comment] 2015-09-16 07:27
Let me know if it still happens with this version: https://github.com/Epix37/HDT-Test/releases/tag/v0.11.4PRE2

Since this is still somehow related to server issues this might be a bit hard to track.
Here's a possible approach: Since the turns seem to be always 0, the opponent's card marks should all show "0" when this problem occours. So use the v0.11.3 (live version) until you notice this, then close it, start 0.11.4PRE2 and see if the marks are correct / the game is recorded.

**Comment by veri745** [comment] 2015-09-16 16:28
I was trying to reproduce to try the pre-release, and I just experienced an issue where a ranked game was tracked, but it was recorded as unranked:
 HDT Log:
http://pastebin.com/WQk8TKFS

I'm posting here because I'm not sure if it belongs in #1433, #1451, or is something else.

**Comment by veri745** [comment] 2015-09-21 03:55
I was finally able to reproduce the issue.

I switched over to 11.4pre2 as requested, but the issue persisted.  

HDT log from 11.4pre2:
http://pastebin.com/zFhY8rMx

Log files:
http://www44.zippyshare.com/v/Lz5yFFJs/file.html

**Comment by veri745** [comment] 2015-09-21 04:03
btw, The 11.4 pre version is not marked as such (I noticed the log still says 11.3, and the version.xml file the same).  I re-downloaded to confirm that the version.xml still says 11.3

**Closed** 2016-02-20 18:11 UTC
Labels: bug
