### ISSUE TITLE
Deck version doesn't stick when syncing b/w two machines

### ISSUE THREAD

**Issue by aalear** [Epix37/Hearthstone-Deck-Tracker#1920] opened 2015-12-24 00:59 UTC
I have a deck that I synced to two computers. Then I edited it on the original computer where it was created and saved it with the same name as v1.1.

The other machine doesn't pick this up on normal sync. Full sync does work and update the deck, but the stats don't come with it correctly, and the deck list on that machine always resets back to v1 of the deck after I restart the tracker.

**Comment by DirtyGit** [comment] 2016-02-12 16:42
This is broken for me aswell in v0.13.9. It'd be great to get this fixed.

**Comment by Epix37** [comment] 2016-04-11 13:37
See #2186

**Comment by Epix37** [comment] 2016-04-15 07:35
Duplicate of #1508.

**Closed by Epix37** 2016-04-15 07:35 UTC
Labels: bug, HearthStats
