### ISSUE TITLE
Card art missing

### ISSUE THREAD

**Issue by CK011885** [Epix37/Hearthstone-Deck-Tracker#2346] opened 2016-04-14 18:15 UTC
I installed the program yesterday and used it all day without issue, after today on 4/14/16 I am now having an issue where card art is missing from one card (Which changes):

http://imgur.com/Se7m1Q0

In this screenshot Emperor Thaurissan is listed in the deck but the art is missing. I tried removing and readding the card. If I play around with it a bit sometimes the art will reappear but another card's art might go missing. It happened with Azure Drake and Sylvannas. I only have two decks added and this problem only seems to be with one of the two decks. The art will also be missing during the gameplay overlay, just showing a gap where the card art is missing.

**Comment by Epix37** [comment] 2016-04-14 18:52
Duplicate of #757.

**Closed by Epix37** 2016-04-14 18:52 UTC
