### ISSUE TITLE
Archetype selector

### ISSUE THREAD

**Issue by ppoutine** [Epix37/Hearthstone-Deck-Tracker#1545] opened 2015-10-01 23:00 UTC
The only thing I dislike about the deck tracker is manually entering the opponent's deck type (i.e. dragon priest vs control priest etc) after every match. Therefore, it would be awesome if this were automated in some way.

It could work as follows: The user sets up a key card or two for each archetype he wants to track. After each match, a UI element pops up with a text box or something, defaulting to whatever archetype the tracker detects. The user has the option to input manually if the tracker is wrong or if it's a new deck type. The input goes into the Notes field for that match.

Long term, it would be great to be able to see stats by archetype too.

I think Track O Bot does something like this, but I haven't played around in it. I'm guessing it happens more in the background.

That is my humble suggestion. Thanks for all your hard work on this program!

**Comment by anonymous555** [comment] 2015-10-02 02:32
See https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1088

**Comment by Epix37** [comment] 2016-03-31 21:41
Duplicate of #733.

**Closed by Epix37** 2016-03-31 21:41 UTC
Labels: enhancement, stats
