### ISSUE TITLE
HDT issues, started today

### ISSUE THREAD

**Issue by Valle641** [Epix37/Hearthstone-Deck-Tracker#2170] opened 2016-03-02 10:50 UTC
I have multiple problems and they all started today.
1. Opponent cards does not reset on match end.
2. Extra cards that I get during a game(From discover effects etc) does not reset upon starting the next game.
3. When my opponent plays a card, HDT shows the card plus a shadow version(like it does when you return it your opponents hand or entombing it)
4. Secrets windows does not go away when all secrets are popped.
5. No Damage counters on the board although I have then enabled.
6. No timer on the board although I have it enabled.
Restarting does not fix anything.
What should I do?

**Comment by Epix37** [comment] 2016-03-02 10:58
See point 1 and 2 here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by zacklytle** [comment] 2016-03-03 06:11
This happened to me today to, started about 5 games ago. Will upload logs in a bit.

**Comment by Epix37** [comment] 2016-03-03 06:21
Any chance you guys are using Innkeeper? The new version can cause problems.

**Comment by zacklytle** [comment] 2016-03-03 06:29
Negative. Only HDT is running.

**Comment by zacklytle** [comment] 2016-03-03 06:40
My logs don't seem to be updating: reset the Hearthstone path and then restarted game+HDT.
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/156277/hdt_log.txt)

**Comment by Epix37** [comment] 2016-03-03 06:44
Did you try [this](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config)?

**Comment by Epix37** [comment] 2016-03-03 06:47
Are you sure that is the latest HDT log?

```
[5:16:23 PM] Helper: Current version: 0.13.9.0
[5:16:23 PM] Helper: Latest LIVE version: 0.13.9.0
``` 

The latest release is v0.13.12

**Comment by zacklytle** [comment] 2016-03-03 07:03
I changed the log.config and restarted both HDT and Hearthstone, played 2 games, but the hdt_log.txt remains unchanged. I also tried running Battle.NET, Hearthstone, and HDT as administrator with no effect (to the log).

However, I've been unable to repeat the problem of the tracker sticking to the old game (it put rogue hero power in the deck too, which was odd). So something fixed the problem.

**Comment by GaryKing** [comment] 2016-03-04 07:35
I've had weird problems with HDT since about a week ago with the latest version. 

I do use Innkeeper. I don't think I started it within the past week though, so I haven't given it a chance to auto-update. 

What conflicts does Innkeeper have with HDT? I don't run Innkeeper all the time; I only run it to upload my cards to HearthPwn, then close it. So that shouldn't be a problem?

**Comment by Epix37** [comment] 2016-03-04 08:16
Innkeeper overwrites the log.config file with a lot less than what hdt needs to function (i.e. only 'Power'). 

I have dealt with this for the next release where hdt will watch the file for changes and make sure it contains everything necessary.

**Comment by zacklytle** [comment] 2016-03-05 05:31
Not using Innkeeper and it's still happening:
![hearthstone screenshot 03-05-16 00 29 06](https://cloud.githubusercontent.com/assets/3013511/13545910/9b4ab784-e269-11e5-8d1b-c43b6ac8e844.png)

**Comment by zacklytle** [comment] 2016-03-05 05:32
Also the turn timer keeps blinking on and off.

**Comment by zacklytle** [comment] 2016-03-05 05:53
Have now tried re-downloading and re-installing both Hearthstone and HDT. Definitely a bug, not a support issue.

**Comment by Epix37** [comment] 2016-03-05 07:45
This looks like the exact issue caused by a missing line in the log.config, see #2103. (therefore support)

I need a hdt log for anything furher.

**Closed** 2016-03-14 08:59 UTC
Labels: support
