### ISSUE TITLE
Show card on mouse over

### ISSUE THREAD

**Issue by surdu** [Epix37/Hearthstone-Deck-Tracker#1932] opened 2015-12-28 13:00 UTC
This is a feature request, not a bug, hope is in the right place.

Would it be possible that when you hover a card in the deck overlay, instead of showing the info pop-up for the card to show the card artwork from HS wiki, like for example this will be shown for Malygos:
http://hearthstone.gamepedia.com/File:Malygos(241).png?version=9eac6390f07cd7e32c79fa95851e6cb4

Or this:
http://www.hearthpwn.com/cards/241-malygos

(only the image, of course)

Alternatively, if possible, the cards might also be taken from the game itself, I don't know the internals of the game.

**Comment by rodrigokiller** [comment] 2015-12-28 18:02
I think that its a good request. However, there are many languages. The solution (maybe) is to use the cards from the game itself, but, I think that its not so easy.

**Comment by surdu** [comment] 2015-12-29 13:46
Good point, but maybe you can get only the artwork and overlay the text from code.

**Comment by andburn** [comment] 2015-12-29 14:00
I've been working on this feature for a while now, it uses the artwork from the game files. Don't know when it will be finished though :disappointed:

**Comment by rodrigokiller** [comment] 2015-12-29 17:39
Wow, its really good to know this. Good luck!

**Comment by Epix37** [comment] 2016-03-25 17:51
Duplicate of #302.

**Closed by Epix37** 2016-03-25 17:51 UTC
