### ISSUE TITLE
Missing class cards

### ISSUE THREAD

**Issue by aliberk8** [Epix37/Hearthstone-Deck-Tracker#1906] opened 2015-12-21 22:05 UTC
i can create every classes deck but i cant build druid and warrior deck cuz i cant see class cards

**Comment by andburn** [comment] 2015-12-22 12:45
This was also confirmed by @mrsimpleman on gitter, in his case only Mage and Warlock class cards showed up. Can't confirm it personally though.

**Comment by siragic** [comment] 2015-12-22 16:45
I can't create any new decks because of this problem. In my case I don't see any class cards on the card pool. I've checked the search filter but it is set to Type:All . Is this a confirmed bug or something?

**Comment by mrsimpleman** [comment] 2015-12-22 17:32
Hello,

Same goes for me but everything is fine for warlock and another class. I
cant see any class cards for any other class but it imports just fine from
a website like hearthpwn.

**Comment by siragic** [comment] 2015-12-22 18:16
Thank you very much @mrsimpleman , you've literally saved my day. 
Importing just works fine for me, too.

**Comment by aliberk8** [comment] 2015-12-23 18:53
but i dont wanna import i just wanna create some mine decks... what can i do? how can i fix this problem

**Comment by siragic** [comment] 2015-12-24 09:55
I hope it is going to be solved in new release. If I am not mistaken, this bug came out in v0.13.7 or v.0.13.6 . @aliberk8 maybe you should try one of the previous versions temporarily until a solution comes out. You can download it from the releases page.

https://github.com/Epix37/Hearthstone-Deck-Tracker/releases

**Comment by Epix37** [comment] 2015-12-28 09:12
Could someone post the log [(see here)](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) after doing this:
* restart HDT
* try to create a deck for a class where the cards are missing

**Comment by siragic** [comment] 2015-12-28 14:11
Excuse me for the delay, 

I've completed the bullets above you've asked me to do. I am sharing the link below. Though I couldn't notice any line about creting a new deck in the log file. 

Thanks for any advance on this matter.
http://pastebin.com/XbE76Med

**Comment by Epix37** [comment] 2015-12-28 15:03
I was hoping to see exceptions along the lines of "card could not be found in database". This is very confusing.

Maybe this is some config problem? Could you upload the config.xml found in `%AppData%/HearthstoneDeckTracker` (alternative: `options > tracker > settings > open appdata folder`)?

**Comment by siragic** [comment] 2015-12-28 15:17
Here it is;

But Github didn't allow me to upload .xml file, so I've changed extension to .txt

[config.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/73303/config.txt)

**Comment by siragic** [comment] 2015-12-29 13:39
Ok, it's about regional settings on computer. I've suspected before and now I've tested it recently. I've changed the 'format' of regional settings from 'Turkish' to 'English' and restart the application and it is fixed. Although before it was working correctly on Turkish settings.

**Comment by mrsimpleman** [comment] 2015-12-29 13:51
How do you change these regional settings can you explain me pls? Thanks!

**Comment by siragic** [comment] 2015-12-29 14:29
Of course;

But I am using Windows 10, it can be a little different on other operating systems. Windows button + X --> From the menu; select 'Control Panel' --> From control panel; select 'Region' --> From the first tab named 'Formats'; select Format: English(United States).

You don't have to resart PC but only Hearthstone Deck Tracker. If you are using another Windows system (But I'm not sure this works on every OS);

Windows button + R --> write 'control panel' to run window.
You're welcome..

**Comment by Tychoe** [comment] 2015-12-29 17:12
What a weird bug. I just did it and it works, thank you for sharing @siragic.

**Comment by aliberk8** [comment] 2015-12-30 16:15
i download v.0.13.5 but still i cant solve ... what can i do?

**Comment by siragic** [comment] 2015-12-31 09:45
You're welcome @Tychoe ,

@aliberk8 you can try changing the regional settings temporarily.

**Comment by Epix37** [comment] 2016-02-17 22:17
Should be fixed with v0.13.10

**Closed by Epix37** 2016-02-17 22:17 UTC
Labels: bug
