### ISSUE TITLE
Killing a Mad Scientist with a spell causes a pulled Spellbender to gray out

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#2247] opened 2016-03-20 10:01 UTC

**Comment by culinko** [comment] 2016-03-31 10:17
Couldn't reproduce in 0.14.0. Can you confirm?

**Comment by Epix37** [comment] 2016-04-11 07:22
Closing this for now then.

**Closed by Epix37** 2016-04-11 07:22 UTC
Labels: bug, secrets
