### ISSUE TITLE
Game state lost after reconnecting

### ISSUE THREAD

**Issue by VPenkov** [Epix37/Hearthstone-Deck-Tracker#1903] opened 2015-12-21 14:05 UTC
After my game reconnects, all of the played cards are now gone and tracked as if the game has just begun.

Any way to fix this? Or maybe show an "Is this a new game?" dialog with a "don't show again" checkbox?

**Comment by mvordeme** [comment] 2015-12-23 00:14
Looks like a duplicate of  #922.

**Closed** 2016-03-04 15:46 UTC
