### ISSUE TITLE
Turn timer is 75 seconds，not 90 seconds。

### ISSUE THREAD

**Issue by everchump** [Epix37/Hearthstone-Deck-Tracker#1113] opened 2015-06-23 11:26 UTC
[source](http://www.reddit.com/r/hearthstone/comments/3agk6v/turn_time_has_been_reduced_from_90_to_70_seconds/)

**Comment by culinko** [comment] 2015-06-23 13:31
Duplicate of #1007 and #1110.

**Closed** 2015-07-01 16:12 UTC
