### ISSUE TITLE
Trouble exporting decks, tracker seems to get stuck on zero mana button

### ISSUE THREAD

**Issue by Mistrelvous** [Epix37/Hearthstone-Deck-Tracker#1217] opened 2015-08-14 07:32 UTC
Ever since the developers of Hearthstone changed the collection manager, I've been having trouble exporting my decks from the tracker to the game. These are the two issues that seem to come up most often. I'd say 45% of the time, the deck tracker fails to load the deck and only two random cards (often 0-1 mana cards) are chosen. 50% of the time, the tracker loads the deck correctly but the first few cards (the lowest mana cards) are incorrect and often random low cost cards. 5% of the time, the export does what it is supposed to do and the deck is loaded correctly from the first try.

The problem stems from the location of the set-selector button. As soon as I try to export the deck, I believe the tracker tries to change the set to "all" and also make sure that no specific mana level is chosen. However, the issue that keeps arising occurs when the tracker selects the "0" (zero) mana option before trying to type in the card names. I assume the tracker is meant to hit that zero button twice, but what ends up happening a lot of times is the tracker makes the zero button stay selected instead of deselected. With zero mana selected, my cards never show up in the search and I end up with a deck of only 2 cards. This happens quite often, especially when I first try to export a deck from the tracker.

The other issue that keeps coming up is that the tracker will sometimes correctly export the deck, but when this occurs, the first few cards of the deck (the lowest mana cards) are incorrect cards. This is what usually happens after the initial deck fails to export correctly, as mentioned in the first paragraph. When the tracker fails to export, I try exporting again, and the second time, the deck will load correctly except for the first few cards, which are replaced with random low cost cards. It's easy for me to change those cards to the correct ones but what I've written above has been happening so often that I think it's best to let you know about this issue.

**Comment by Epix37** [comment] 2015-08-14 09:35
Probably related to #1162? If so, that might very well be fixed with the next update.

**Comment by Epix37** [comment] 2015-08-15 08:24
Please let me know if you still have these issues with the latest pre-release: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.10.8

**Comment by Mistrelvous** [comment] 2015-08-16 00:09
Hey Epix, I tried out the latest pre-release but I don't think the problem has been solved. Exporting worked great the first time but when I tried exporting another deck, the issue of the tracker occasionally selecting a random incorrect low mana card came up again. For example, in one of the decks I tried to export, it replaced Preparation (on my list) with Conceal (not on my list). Like I said, I can easily make the manual switch of changing Conceal to Preparation myself, but I'm not sure why the tracker chooses the wrong low mana card so frequently.  

I tried a third time with the latest pre-release and the zero mana button being stuck issue happened. I took a screenshot of what I see after the tracker fails to import a deck after getting stuck on zero mana and I'm going to attach it to this message.
![deck tracker export issue](https://cloud.githubusercontent.com/assets/11181065/9291373/688c2924-4389-11e5-8a2c-f26322e8c723.png)

**Comment by Mistrelvous** [comment] 2015-08-16 00:14
The 4th time I tried exporting, everything went smoothly, just like the first time. I am not sure what is causing the tracker to occasionally make export errors but sometimes it works smoothly, sometimes it does not. I wrote my initial message because it seemed to me that the instances of the tracker experiencing difficulty exporting decks occurs more often than exports running smoothly.

**Comment by Epix37** [comment] 2015-08-16 07:16
Hmm... Try lowering the speed in `options > tracker > exporting`, see if that helps.

**Comment by andburn** [comment] 2015-08-16 13:08
@Mistrelvous Can you post a couple of images of the collection manager, one with the zero mana on and one with it off (both taken from within Hearthstone using the *Print Screen* keyboard button).
Also:
- What resolution is Hearthstone set at?
- Have you tried exporting when in fullscreen?

**Comment by Mistrelvous** [comment] 2015-08-17 03:10
I tried lowering the speed to normal (60ms), but the same issues and inconsistency occurs. First attempt at exporting a deck, the deck loads 100% correctly. 2nd attempt, deck loads correctly except a random low cost card from the chosen class has replaced a card from my decklist. 3rd attempt, the tracker gets stuck on zero mana button and only cards with zero mana within the deck are loaded (pretty much exactly what happened in my screenshot above).

@andburn My resolution is set to 1920 x 1080. As soon as I open Hearthstone, I set it to 1920 x 1080. This is because I don't run Hearthstone in fullscreen so the game leaves a blank spot under resolution when I open it. Thus, every time I open it, I make sure to set resolution to 1920 x 1080. 

@andburn I tried exporting in fullscreen as you suggested for my third attempt at exporting and the result was mentioned earlier in this message: the tracker got stuck on zero mana button and only cards with zero mana within the deck were loaded in the game. I'm not sure why you want me to post screenshots of the collection manager with zero mana selected and unselected. I know how to toggle mana selection. I never touch the mana selection button. When exporting however, the tracker does this on its own. It clicks the zero mana button twice to ensure that no single mana option is selected.

**Comment by Mistrelvous** [comment] 2015-08-17 03:19
I think I found a solution to this issue. 
Here is what my export settings were when the issues were occurring:
-Speed: Fast (40ms) 
-Wait: 0 seconds
-Prioritize Golden Cards
-Set Deck Name
-Auto Clear Cards
-Show dialog before exporting

I then changed it to the following and so far, the tracker has been 100% successful after 4 tries:
-Speed: Normal (60ms) 
-Wait: 1 seconds
-Prioritize Golden Cards
-Set Deck Name
-Auto Clear Cards
-Show dialog before exporting

For some reason, the wait "1" second option makes the export work flawlessly. That, or it is the combination of 1 second wait + 60ms speed setting. Or maybe I just got lucky 4 times in a row. Either way, I think setting the default options of the tracker when exporting decks to wait 1 second and also normal (60ms) speed might help other users not run into the problems mentioned above.

**Comment by andburn** [comment] 2015-08-17 09:30
I'm glad you got a solution. 

The reason I asked for the screenshots was because the tracker takes a screenshot internally and tries to determine if the *zero mana crystal* is selected or not. I thought that process might be broken and was going to check it with your screenshots. If you could post them, I'd still like a look.

**Closed** 2015-09-14 23:02 UTC

**Comment by mvordeme** [comment] 2015-10-11 22:01
It happened to me again (see #1177) and it had nothing to do with screen resolution or the choice of windowed or full screen. Right now, I tried it again and it worked flawlessly. When it failed, I had been in a conversation. Don't know whether it could have had an impact.

**Comment by mvordeme** [comment] 2015-10-24 22:12
Is it any use to post in this issue after it has been closed? I think I have found a clue and a work-around solution for this problem:
The problem has nothing to do with the resolution or windowed display, neither has it anything to do with the export settings. The only thing that counts is whether you did open a conversation window in the current session of Hearthstone or not. If you did, the export will not work. It will select the 0 Mana filter when trying to deselect it and not find a single card in the deck. If this happens, close Hearthstone and open it again. Now the export will work. At the beginning, this will cause Hearthstone to display the message *Use the friends menu to start a conversation with a friend*.

**Comment by livejamie** [comment] 2015-11-25 20:31
I can confirm what @mvordeme said. Exporting to a Tavern Brawl as mentioned in #1177 doesn't seem to work if you've recieved a conversation window during that current session.

Restarting Hearthstone fixes the problem and allows me to export to a tavern brawl.

If I've received a message during the session it gets stuck on the 0 mana filter.
