### ISSUE TITLE
The ordering of the hands in ReplayView is not consistent

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#531] opened 2015-01-06 05:52 UTC
A minor issue:

The order in which the cards in the players and the opponents hand are displayed changes from move to move. 

At the last draw of turn 1:
Order of opponent hand: MR, AS, YP, VW, C
Player Hand: SB, SWP, IB, BL

At the first draw of turn 2:
Opponent hand: MR, AS, YP, VW, **MT,** C *(I think the new card should be the last)*
Player Hand: **SWP, BL, IB, SB** *(Order should stay the same and be consistent with the order of the cards in the game)*

https://www.mediafire.com/?ss9xgl6597e3ka3

**Comment by BVA64** [comment] 2015-01-06 20:25
It looks like the same issue is present also for the order of the minions on the board. 
Turn 12: I played the Kezan Mystic to the far right. In ReplayView it is shown to be in the middle. In Turn 13 it is shown in the correct position.
http://www.mediafire.com/download/73hjf9xu189nhq4/BVA64(Priest)_vs_Tardotron(Shaman)_2210-060115.hdtreplay
The issue I believe is somewhere in the method ResolveZonePos run before the replay is saved. In the saved json replay file the elements are already in the wrong "order".

**Comment by Epix37** [comment] 2015-01-06 20:39
Yes. The issue is in the second part of ResolveZonePos. I need to get the zonepos from all entites except the one that changed, then move the new one to the end if it's somewhere it shouldn't be. I'll try to fix that tomorrow.

**Comment by BVA64** [comment] 2015-01-06 21:01
Great! Thanks!

**Comment by Epix37** [comment] 2015-01-10 08:57
Alright, that seems to do it.

**Comment by Epix37** [comment] 2015-01-10 10:10
Should be fixed with v0.7.4

**Closed** 2015-01-10 10:11 UTC
Labels: bug, next update, replays
