### ISSUE TITLE
2/3 game wins

### ISSUE THREAD

**Issue by koalafishy** [Epix37/Hearthstone-Deck-Tracker#1345] opened 2015-08-27 04:12 UTC
Hi, just a small bug i seem to be experiencing.
The counter for how many wins I am away from 10 gold is stuck on 2 and 10 atm.
it reads Wins: 2/3 (10/100G) and doesn't increase when I win

Thought you might be interested

**Comment by MechaLynx** [comment] 2015-08-27 04:14
This is known and isn't a problem on HDT's side - Hearthstone's logging has changed and apparently it doesn't send information on this anymore or the format has changed. In any case, it doesn't seem like it can be fixed on this side, it's up to Blizz.

**Comment by koalafishy** [comment] 2015-08-27 04:20
OK sorry for not checking the forum properly before posting

**Comment by MechaLynx** [comment] 2015-08-27 15:23
It's ok, it's a bit hard to check. You might want to close this issue however, since the problem is tracked with bug #1278 anyway.

**Closed** 2015-08-27 17:26 UTC
