### ISSUE TITLE
Ranked games being marked as casual

### ISSUE THREAD

**Issue by dphil** [Epix37/Hearthstone-Deck-Tracker#1852] opened 2015-12-11 15:12 UTC
The last time I played ranked matches was on Dec 9, without problem. I did not play any games yesterday (Dec 10). Today, Dec 11, I downloaded the beta updates since I last used HDT on Dec 9, and played a ranked match. It did not show up in the HDT stats/game history. So I manually entered the game details myself, restarted HDT and Hearthstone and played 2 more ranked matches. Again, both games did not appear in my HDT stats/history.

I checked the HDT log and noticed that it did detect the details (opponent name/class, # turns, time, etc) about those games properly, but for some reason it was incorrectly marking the games as Casual mode, and thus discarding them since I have HDT set to record stats for ranked only.

Edit: I just tried turning on stat tracking for casual mode as well, and sure enough my next ranked match showed up in my game history/stats (as casual), after which I edited it manually to mark it as ranked instead of casual. I guess I'll continue doing that as a workaround until the game mode detection is fixed.

**Comment by andburn** [comment] 2015-12-11 18:51
Can you post a screenshot of hearthstone during a ranked game, and also the HDT log.

**Comment by dphil** [comment] 2015-12-11 21:31
Hm. I went to try to reproduce it, and it recorded a couple ranked matches in a row correctly. I restarted both HDT and Hearthstone to try again, and this time it recorded my next ranked match as Casual again. I hadn't taken a screenshot in-game since I assumed everything was working fine again, but after the issue arose again, I did save the log file:
[log_11122015-15258.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/59810/log_11122015-15258.txt)

The log is from the following sequence of actions:
1) Starting up HDT
2) Starting up Hearthstone
3) Going to Play mode, and clicking the Play button ("Ranked" was already selected in-game) and playing a match to completion, then clicking on the victory screen to return to the Play mode menu.

In case it is relevant, I play Hearthstone in windowed mode with the option for the game notes window to pop up at the end of the match to record any of my own notes about the match (which I generally do and did so for this match).

At 3:12:48 in the log it says "Game: Set CurrentGameMode to Casual". This was when I clicked on the "Play" button in the main Hearthstone menu to go into the Play mode screen. As mentioned before, the "Ranked" button was already selected, not Casual. Granted, maybe HDT simply defaults to Casual and then does some secondary detection for ranked mode later on (at the end of the match?), I don't know.

Here's the last portion of the log after the game ends and I click the victory screen to return to the Play mode screen:

[3:21:17 PM] HandleGameEnd: Waiting for game mode to be saved to game...
[3:21:18 PM] RankedDetection: Captured image is null
[3:21:18 PM] GameEventHandler: No ranks were detected.
[3:21:32 PM] HandleGameEnd: Game mode was saved, continuing.
[3:21:32 PM] HearthStatsManager: trying to upload match: Win vs Shaman, 11/12/2015 3:13:02 PM
[3:21:32 PM] HearthStatsAPI: Game Win vs Shaman, 11/12/2015 3:13:02 PM is not valid (invalid game mode: None)
[3:22:33 PM] UpdateOverlay: Refreshed overlay topmost status
[3:22:38 PM] HandleInMenu: Game is now in menu.
[3:22:39 PM] GameEventHandler: Set CurrentGameStats.GameMode to Casual
[3:22:39 PM] GameEventHandler: Saving DeckStats

Is this where it normally detects if the game was a ranked match? If so it seems to have failed. Does the game screen need to be in front/selected for this to work properly? I often switch to other windows during a match.

**Comment by dphil** [comment] 2015-12-11 21:42
I played  a few more matches, restarting HDT and Hearthstone each time, and I can't consistently reproduce the issue. Sometimes it detects it as ranked, sometimes not.

In the latest match I played, it correctly recorded it as a ranked match, and I found where it identified it as such in the log:

[4:22:19 PM] UpdateOverlay: Refreshed overlay topmost status
[4:22:26 PM] GameEventHandler: Trying to detect ranks... (tries=0, overlaytoggles=0)
[4:22:26 PM] Overlay: No ranks should be covered by any decks.
[4:22:26 PM] GameEventHandler: --- Opponent turn 1 ---
[4:22:27 PM] GameEventHandler: Rank detection successful! Player=5, Opponent=5
[4:22:27 PM] Game: Set CurrentGameMode to Ranked

So right near the start of the match (Turn 1) it was able to identify our ranks and set it to ranked mode. Looking back at the log file of the failed match attached in my previous post, I see that it tried numerous times to detect the ranks, but always failed, sometimes with the message "Captured image is null", sometimes without that message. I'm not sure why it fails in some matches but not others. these are all at the same rank (5). Again, I often jump between different windows while I'm playing, so maybe that is interfering with something?

**Comment by dphil** [comment] 2015-12-11 23:49
Ok after a little more testing I think I might know what's going on. It appears to attempt to detect ranks at the start of each player's turn. Whenever I have HS in the background and another window in the forefront at the start of a turn, it is unable to detect ranks (as indicated by the log - "Captured image is null...No ranks were detected"). It's entirely possible that, for the incorrectly tagged matches, I opened my browser or whatever at the end of every single one of my turns until the start of my next turn (at which point the HS icon in the taskbar flashes to notify me), thus denying HDT every start-of-turn chance to visually detect the ranks. Thus at the end of the match, HDT can't tell if the game was ranked or not, and thus defaults to Casual? This is my theory, anyway.

**Comment by andburn** [comment] 2015-12-12 10:32
Thanks for the info. You're right that HDT tries to detect rank at the start of each turn and at the end of a game. It also has a limit to the number of times it will try to detect during a single game, so the switching windows is most likely the cause. I'm sure there is something we can do to improve it. If you could post a screenshot of a game, it would still be useful to see what HS looks like at your resolution.

**Comment by anonymous555** [comment] 2015-12-13 15:34
I put my player deck on the left.  When I have a very large deck (like a reno deck with no duplicates), rank detection breaks.  But for smaller decks, rank detection works fine.  I wonder if the larger decks are covering up the rank icon and that is breaking it.  I use the overlay for decks, not an external window.

**Comment by andburn** [comment] 2015-12-13 15:59
The program is supposed to check if the rank icon is covered and hide the overlay briefly while it does the detection. It must not be working correctly. I'll test it out a bit myself.
If you could also post a screenshot of a game when you are using a large deck, that could be useful too.

**Comment by dphil** [comment] 2015-12-13 17:51
Hi andburn,

I just played another ranked match where I made sure the game screen was in the foreground at the start of multiple turns (I think on the first turn it was in the background though), but for some reason it still wasn't detecting the ranks and thus recorded it as a casual game in the end.

Here is the log: 
[log_13122015-124051.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/60542/log_13122015-124051.txt)

And here is a screenshot during the game, which is as it typically appears when I play:
![capture](https://cloud.githubusercontent.com/assets/3652549/11768315/0483f65c-a197-11e5-88e3-189d5aa9d932.PNG)

I use a screen dimming app so the image may look slightly dim. I'm not sure if that interferes with the rank detection at all. I play Hearthstone in windowed mode on a 30-inch 2560x1440 screen. I typically play with the Hearthstone window taking up about 1/4th of my screen (as in the above screenshot which is 1063x827.

**Comment by dphil** [comment] 2015-12-13 19:01
Aha, I think I know what's going on now. There were sort of 2 problems I was encountering. One (as already discussed earlier in this thread) was the issue of having HS in the background at the start of turns so HDT wasn't able to detect the ranks.
But it seems the other problem was due to the screen dimming app I've been using (I use bootcamped Windows on a Mac machine, and the manual brightness controls don't work properly so I use a 3rd-party app). After my above post I decided to test it out. I found consistently that if I set the dimmer below a certain threshold, it was never detecting the ranks even with HS in the foreground. But as soon as I increased the brightness above a certain point, it immediately detected the ranks at the start of the next turn.

So in that case perhaps it is possible to relax the tolerance of the image detection so it can still determine ranks at dimmer settings, or else maybe put a warning somewhere that screen dimmers can interfere with it.

**Comment by Epix37** [comment] 2015-12-14 11:03
Rank detection now waits for HS to be in foreground. 

@anonymous555 Could you post a screenshot of your game+overlay in ranked? HDT should normally briefly disable the overlay if the ranks might be covered by either deck list.

**Comment by andburn** [comment] 2015-12-14 19:16
@dphil unfortunately I don't think there's much that can be done regarding the screen dimmer problem, because the image detection is very sensitive to any variations.

**Comment by dphil** [comment] 2015-12-14 19:54
@andburn No worries, I know I'm probably in the vast minority for that particular issue, and it's easy enough for me to work around anyway by just adjusting the dimmer for one turn each match. But yeah maybe an FAQ post or something could help anyone who has this issue in the future. Cheers.

**Comment by anonymous555** [comment] 2015-12-15 02:21
Well now I don't know what's going on, I had rank detection fail even for a smaller deck

![rankdetection](https://cloud.githubusercontent.com/assets/8370128/11800234/7fe57dd6-a28f-11e5-858d-421180377ff6.png)

**Comment by Epix37** [comment] 2015-12-15 08:11
@anonymous555 part of the problem is most likely that v0.13.5 also requires the opponent rank to be detected for detection to be a success. That was changed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/758e1b027161f481f9e5374734b39e247a3461ec to only require the player rank.

The overlay *should* toggle though if the rank is covered - not sure why that's not happening. Could you post the hdt log?

**Comment by Epix37** [comment] 2015-12-16 08:14
Please try this release and let me know if you are still having issues: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.6_PRE1

**Comment by anonymous555** [comment] 2015-12-20 07:11
With 13.7, now it detects small decks just fine.

But 13.7 still has problems with large decks.  Now it properly detects it was ranked mode.  But the rank number itself is not found.  

I'm attaching a log of an example.  
[hdtlog.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/67733/hdtlog.txt)

**Comment by foxor** [comment] 2016-01-04 15:02
I'm reproducing this problem as well, here's a screenshot of the beginning of an incorrectly identified ranked match.  I don't know where to get the log.

![hearthstone screenshot 01-04-16 06 51 14](https://cloud.githubusercontent.com/assets/58071/12092218/839336ea-b2b0-11e5-9c06-afc9955d09e8.png)

**Comment by riQQ** [comment] 2016-01-04 22:05
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by foxor** [comment] 2016-01-06 14:55
Here's a log after it reproduced again.  This time, my first game was correctly categorized, but my second game was miscategorized.  I lost the first and won the second.  Also, I changed some cards between games, so I got warnings in the second one.

[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/79922/hdt_log.txt)

**Comment by FranDes** [comment] 2016-01-06 15:07
Hi, I have the same problem, the app records a game as casual while it is ranked. I've another problem (I think); it deletes my recent games, i don't know why. http://pastebin.com/KmGTdZ2P

**Comment by Epix37** [comment] 2016-02-20 18:09
closing in favor of #2034

**Closed by Epix37** 2016-02-20 18:09 UTC
Labels: beta, bug
