### ISSUE TITLE
Nodeck mode detect problems 

### ISSUE THREAD

**Issue by HellbringerOnline** [Epix37/Hearthstone-Deck-Tracker#2319] opened 2016-04-06 21:20 UTC
![image](https://cloud.githubusercontent.com/assets/14059683/14333285/f5f45fc8-fc5e-11e5-8c2b-682150ca0ad2.png)
![image](https://cloud.githubusercontent.com/assets/14059683/14333301/11c9e59c-fc5f-11e5-9c79-66dd63e94258.png)

**Comment by Epix37** [comment] 2016-04-06 21:34
I think this is correct.  

The cards in the list are the one still in the deck, likely those you mulliganed. v0.14 no longer displays created cards in the list unless they are in your deck or in you hand and 'include obtained cards'  is enabled. 

The deck/hand counters all display the correct values.

**Comment by HellbringerOnline** [comment] 2016-04-06 21:53
Its one game screens

**Comment by Epix37** [comment] 2016-04-07 06:19
I assume off of unstable portal? Then that's still working as intended (though I agree not optimal right now).

**Comment by Epix37** [comment] 2016-04-07 07:33
If not, this might also be related to the issue where the player list stops updating in some cases after mulligan. That's fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/f33c52758450b7701f97acf4fd6631e3dd3622fb.

**Comment by HellbringerOnline** [comment] 2016-04-07 16:37
I will continue research

**Comment by riQQ** [comment] 2016-04-07 17:09
Excavated Evil can't be obtained by unstable portal.

**Comment by Epix37** [comment] 2016-04-07 17:18
Right. Probably the second thing I mentioned then.

**Comment by yoshimo** [comment] 2016-04-07 19:07
The brawl has spells that aren't created by unstable portals and are already in your deck, you reveal them by drawing them instead of a portal.
Neither those class spells nor the portals nor the cards you get from the portals are shown for the current player.
Portals and played cards are shown for the opponent player though which seems inconsistent if my own deck is "empty".
[HDT_Portal_Brawl_buglog.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/209038/HDT_Portal_Brawl_buglog.txt)
Maybe the attached HDT log can shed some light on the issue.

**Comment by Epix37** [comment] 2016-04-08 20:37
All the cards in this brawl are "created" (the decks are swapped), so this is technically correct behavior.

The ability to show created cards in the list after they leave the deck/hand will be added in some fashion with #961.

Closing in favor of #961.

**Closed by Epix37** 2016-04-08 20:37 UTC
