### ISSUE TITLE
Deck Version not working over v9.0

### ISSUE THREAD

**Issue by frodo010595** [Epix37/Hearthstone-Deck-Tracker#1299] opened 2015-08-22 17:43 UTC
Hi,
There seems to be a problem with the deck tracker in the way that is you have more than 9 versions of a deck. I.E. if you have been updating and saving your deck as new versions a lot you will just be saving a lot of v1.0 decks. 
I have one deck which goes up to V13 on Hearthstats but only V1.0-V9.0 in Hearthstone Deck Tracker.
Don't know if there is a workaround but it is a bit annoying not to be able to save more Versions.

**Comment by Epix37** [comment] 2015-08-22 18:51
I seem to be able to create any number of versions in HDT. I assume the problem is syncing version > 10 from hearthstats to HDT?

**Comment by frodo010595** [comment] 2015-08-22 19:21
Yes, I too am able to create versions directly in the HDT. However if the deck is created on Hearthstats and is over V9 it seems unable to create higher version numbers. 
However the problem only occurs if I've created a higher than V9 deck on Hearthstats. If it's created on Hearthstats but belov V9 the deck can go above V10.

**Comment by Epix37** [comment] 2015-08-22 19:59
Will be fixed with the next update (probably monday).

**Comment by frodo010595** [comment] 2015-08-22 20:00
:+1: :)

**Closed** 2015-08-26 02:20 UTC
Labels: bug, next update
