### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by HelpTheNoob** [Epix37/Hearthstone-Deck-Tracker#2031] opened 2016-01-29 17:54 UTC
After the update my mouse freezes. (Windows 7)
Have to kill the program to unfreeze the mouse.
Regards Ole

**Comment by Epix37** [comment] 2016-01-29 17:59
Got a few tweets about this as well - not really any idea what the problem is.

* Please post the hdt log ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)).
* Does this happen every time you start it / does it resolve itself on it's own at some point?
* Does deleting the content of Hearthstone/Logs help? (close Hearthstone before deleting)
* What version of .NET Framework are you using? Does re-installing the latest version help?
* What OS are you using?

**Comment by LouJay** [comment] 2016-01-29 17:59
Hi! The same thing happens to me, here are a couple of additional details:

v0.13.7 works perfectly fine for me, but whenever I try to use v0.13.8 muy pointer freezes either completely or almost completely and I can't do anything else except use the keyboard to shut HDT down.  After that, I regain control of my mouse/pointer.  I already tried reinstalling v0.13.8 either downloading it manually or upgrading from the previous version but the same behavior happens anyway. I went back to v0.13.7 and it works smoothly.

I am using Windows 8.

**Comment by Epix37** [comment] 2016-01-29 18:19
I think I found the cause: Try disabling `options > overlay > interactivity`.

**Comment by HelpTheNoob** [comment] 2016-01-29 18:33
Hi

I cant produse a log file. No way to get to the options menu with key commands.
It does not resolve it self over time.
I deleted the content of Hearthstone/Logs - didnt help.
.NET Framework 4.5.2 is installed. Updating to a newer 4.6.1 did not help.
CPU-usage is not high - 1-3%

How do I get to the option menu with out a mouse ;)

Regards Ole

**Comment by Epix37** [comment] 2016-01-29 18:33
Please try this version and let me know if it fixes the problem: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.9_PRE1

**Comment by HelpTheNoob** [comment] 2016-01-29 18:37
v0.13.9_PRE1 is running great :)

Thank you so much.
You are a life saver :)

Regards Ole

**Comment by Epix37** [comment] 2016-01-29 18:44
Should be fixed with [v0.13.9](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.9).

**Closed by Epix37** 2016-01-29 18:44 UTC
Labels: bug
