### ISSUE TITLE
Deck comparison feature: Allow two decks to be highlighted in order to view the card-level diff

### ISSUE THREAD

**Issue by philip161** [Epix37/Hearthstone-Deck-Tracker#977] opened 2015-05-17 22:28 UTC
I think the best way of doing it right now is to export the decks into XML and then using a diff program to compare the files. It would be nice if I could select two decks in Hearthstone Deck Tracker itself and immediately select "Compare" after which I would be presented with something like:  
  
-1 Spider Tank  
+1 Piloted Shredder

**Comment by culinko** [comment] 2015-05-18 14:09
The comparison could look like when you edit a deck and there is the diff. between versions, it looks very good.

**Comment by jmdesprez** [comment] 2015-11-16 13:47
Duplicate of #771

**Closed** 2016-03-29 10:05 UTC
