### ISSUE TITLE
Export broken missplaces first 2 cards.

### ISSUE THREAD

**Issue by RavenousSix** [Epix37/Hearthstone-Deck-Tracker#1123] opened 2015-06-25 20:24 UTC
Whenever I export to game it picks the wrong cards for the first 2 cards, the rest are OK. I have to manually replace them by hand.

**Comment by Rumik** [comment] 2015-06-25 21:03
Me too! This, in conjunction with Hearthstone's annoying moving search field bug (which is fixed by turning on the touch keyboard) makes HTD rather unreliable! :(

**Comment by MarineKingAizen** [comment] 2015-06-26 00:16
I am also having this problem, it misses the 1st card or 2 usually. OR it will often put in a card I didn't have listed at all for that 1st slot. It's rare for me to import all 30 cards with a problem.

I got slightly better results by adjusting these settings under "import": Added in a  2 second delay before start and decreased the import speed to slow. Still, it doesn't work all the time.

**Comment by RavenousSix** [comment] 2015-06-26 01:15
It's the first time I've ever experienced this issue with the latest updated to HDT. Never had this issue before.

**Comment by andburn** [comment] 2015-06-26 12:31
It sounds like a problem that has been mentioned before, to do with changes to the collection manager with the latest Hearthstone patch. It should be fixed in the next HDT update.

**Comment by hastuur** [comment] 2015-07-06 20:44
No longer true : import feature is now worse since last update. Import deck name begins with )&é^ characters, cards present in collection are not found. In french version : zombie chow and sen'jin shieldmasta are two of those which don't work properly.

**Comment by andburn** [comment] 2015-07-07 10:32
@hastuur can you post the deck you are trying to export into hearthstone, either a web link or a screenshot. Also, what resolution are you using in hearthstone (e.g. 1920x1080) and is it windowed or fullscreen?

**Comment by hastuur** [comment] 2015-07-07 15:37
Hi. Here is copy of the export attempt and copy of the deck, as well as 
hearthstone state after import. Note the deck name that has unexpected 
characters. I once had that problem when accidentally switched to US 
keyboard but this is not the case here : i'm on french keyboard, 
verified while typing this :)
Resolution is 1920x1080, fullscreen.
If any other information may be useful, please tell me and i'll return 
them ASAP.

BTW, as a professional programmer, i am aware of the amount of work 
involved in that software. You do a great job there !

**Comment by andburn** [comment] 2015-07-07 16:08
@Epix37 is the one responsible for this great app. I'm just helping out :smile:

Your attachments don't seem to have made it to github, maybe only Epix gets them. If you could post the information here directly I might be able to get to the bottom of it.

**Comment by hastuur** [comment] 2015-07-08 16:38
Hi
Sorry that the screenshots did not make it
Here they are in downloadable form :
https://share.orange.fr/?_=hzP#Sb6vw1RulH12cafe1d60

I've made a few tests since then and noticed that the bottom left corner 
is accessed after clearing old deck, and it seems to mess with the next 
operations.
Most of the cards work well except a few which I think identified as 
those who contain "special" characters in their name and/or illustration 
author (not confirmed, it works too fast for my eyes).
The cards not found are systematically the same, it's a search criteria 
issue, but i cannot tell the origin.
My keyboard is french and i have both french and US languages installed 
because it's a heroes of the storm requirement. Default and current 
languages are french but some of the keys sent to hearthstone seem to be 
the US equivalents : cf [12]Basic naxxramas transformed in hearthstone 
in )&é^Basic xxx : & and 1 are on the same key, 2 and é too, the 
brackets i don't understand the translation but there must be a logical 
reason :)

If i can be of any help to resolve this, please tell.

Hastur.

**Comment by andburn** [comment] 2015-07-09 13:48
@hastuur I am not really sure what is causing the problem, but there are a few things you can try:

1. Make sure you are using the latest version of the tracker (0.10.7). Press the *help* button the version is shown at the bottom left.
- Go to `Options > Tracker > Exporting` and check *Paste names from clipboard*, this can help in exactly this situation.
- If the previous two options don't work it must be something to do with Windows and the language/keyboard set up.

**Comment by hastuur** [comment] 2015-07-09 19:00
Hi
Looks like second option was the one which works.
Thanks a lot.
I'll have to check what's done when that box is not checked :)

**Closed** 2016-04-11 07:31 UTC
