### ISSUE TITLE
Ranked Games Still recorded as Casual v0.13.7 / v0.13.9

### ISSUE THREAD

**Issue by tknights2015** [Epix37/Hearthstone-Deck-Tracker#1889] opened 2015-12-19 02:44 UTC
Ranked games are still being recorded as casual. Highlighted last game was a ranked game.  Did not have this issue in version 13.3

![ranked game recorded as casual](https://cloud.githubusercontent.com/assets/16232528/11910860/aa0627d6-a5bf-11e5-98c2-e309a0cfe01c.JPG)
[log_18122015-194147.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/67349/log_18122015-194147.txt)

**Comment by EAldanaJ** [comment] 2015-12-19 14:03
Hi, I had the same problem in version v0.13.7 at the start, but i changed my resolution setting in game to match my monitor settings and it worked really well Now its recording ranked games perfectly, with the new replay system wich is a bit odd xD but more accurate than the old one :D i hope this works for you

**Comment by andburn** [comment] 2015-12-19 14:53
@EAldanaJ its good you found a solution, but it should really work with all resolutions so its still sort of a problem. Also, unless your replays look like this: ![Replays](https://camo.githubusercontent.com/9cc3099929b9a8c194bfa75595e1c632d97a5f34/687474703a2f2f692e696d6775722e636f6d2f7475784f466d672e706e67)
Then it is probably not recording replays correctly and showing the old replay viewer, another problem :smile:.

**Comment by tknights2015** [comment] 2015-12-19 15:50
Glad you found a solution, but if the issue  was a problem with the game resolution and my monitor resolution, then the same issue would happen with version 13.3.  All of my games record correctly with v13.3 and do not record correctly with 13.7

**Comment by EAldanaJ** [comment] 2015-12-19 18:15
No, because the v13.5 and older works with a different game/rank detection as mentioned in the patch notes, the resolution or messing with it can make the tracker not recognizing the game and not recording any information from it, iwch like i said for me solved that way
@andburn yeah thats the new replay system i dont like that much but its very very accurate and on the spot for each play we make in game

**Comment by tknights2015** [comment] 2015-12-19 19:32
This is a new log from a game today.  Monitor resolution and in game resolution set to the same  1920x1200. Game setting is also HD. Does not make any difference if full screen or windowed.
[log_19122015-121651.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/67583/log_19122015-121651.txt)

**Comment by Epix37** [comment] 2015-12-20 01:39
Please make a screenshot during a ranked game via the HDT hotkey (set up under options > tracker > hotkeys)  and post it here.

**Comment by tknights2015** [comment] 2015-12-20 02:51
Ok Screen shot
![hearthstone 12-19-15 07-38-02](https://cloud.githubusercontent.com/assets/16232528/11916191/c56d1d70-a689-11e5-9db5-d8c9cc486ac0.png)
Game record
![hearthstone 12-19-15 07-48-36](https://cloud.githubusercontent.com/assets/16232528/11916192/ca534864-a689-11e5-964c-a6441e1df863.png)
Log file
[log_18122015-193410.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/67674/log_18122015-193410.txt)

**Comment by tknights2015** [comment] 2015-12-20 04:16
After I took the screenshot in game above, and  4 others, one in game.  The last 2  screenshots are empty, as if nothing is there.  I also replicated this again in the most current game in this log. All 6 screen shots with the HDT screenshot function are blank.
[log_19122015-211525.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/67688/log_19122015-211525.txt)
Blank image
![hearthstone 12-19-15 09-01-56](https://cloud.githubusercontent.com/assets/16232528/11916475/b58b5474-a695-11e5-8860-89aaa4485370.png)

**Comment by tknights2015** [comment] 2015-12-20 05:19
I restarted Heartstone and HDT and screenshots work now and games are recorded as ranked.
No settings changed.  Do you want the log and screen shots?

**Comment by tknights2015** [comment] 2015-12-20 06:32
With no changes, not closing HDT or Hearthstone.  Ranked games started again being logged as casual and screenshots with no data (blank)
[log_19122015-231930.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/67714/log_19122015-231930.txt)
![hearthstone 12-19-15 11-13-15](https://cloud.githubusercontent.com/assets/16232528/11916868/d0f741ec-a6a8-11e5-9355-83dd64106f40.png)

**Comment by ginko147** [comment] 2015-12-20 23:30
I can confirm that changing resolution below 1080p sometimes ranked games are being recorded as casual.

**Comment by tknights2015** [comment] 2015-12-30 04:38
This issue is still happening.

**Comment by tknights2015** [comment] 2016-01-10 05:40
This issue has resolved for me with no action or changes on my part.

**Comment by Epix37** [comment] 2016-01-11 11:08
Possibly a windows update? 

Not entirely sure how those empty screenshots happen. Most likely something system-specific.

**Comment by tknights2015** [comment] 2016-01-11 17:50
Not sure if it was a windows update, but possible I have not changed anything on this computer. As of now, my games are recording correctly.  I did have one game, in the last few weeks that did not record at all, but the ones that are recording at this time appear to be correct in ranked and casual.

**Comment by Epix37** [comment] 2016-02-12 09:59
Give this version a try: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.10_PRE2

**Comment by Epix37** [comment] 2016-02-20 18:07
Closing in favor of #2034

**Closed by Epix37** 2016-02-20 18:07 UTC
