### ISSUE TITLE
update a deck with cards not found

### ISSUE THREAD

**Issue by pompobit** [Epix37/Hearthstone-Deck-Tracker#2095] opened 2016-02-14 02:57 UTC
Is it possible to add to a deck the cards not found?

I'm trying to import my construscted decks, and I use "import from last game" or "import from game: constructed".
Both ways result in missing cards, I'd like to update them automatically when a card in a game is not found, so the deck would fix himself simply playing it.
I don't think it would be too hard, is there already something like this that I missed?

**Comment by Epix37** [comment] 2016-02-15 18:58
Automatically uploading the deck is extremely unpractical since would require the full deck to be played in a single game. 

Say you replace 1 card, during the course of the game you play all but 3 cards (both were already in the game). There is no way for HDT to know which card needs to be removed from the deck to make space for the new one. Even if you can determine the 3 missing cards from game one in the second, there is no way to know if any other modifications were made in the meantime. 

Modifying the deck in HDT only takes 5 seconds and is far more reliable. 

One thing I can do though is add a hotkey to edit the current deck.

**Comment by pompobit** [comment] 2016-02-15 19:22
right, didn't think about editing deck between matches.

An hotkey to add the card when it is not found would be great anyway.
Thank you.

It is OT but I'm thinking about this in these day so I catch the chance to ask to you:
Could be interesting a plugin to import a constructed deck from the game screen?
I mean something that captures the screenshot of the heartstone client when it is in constructed menu, then doing image recognition to analyze the screenshot to find the cards in the deck and import them in HDT.
This could work with a dedicated button to capture and analyze the screen because a single screenshot could be not enough if the cards list is too large and needs to be scrolled and to automatically detect scrolling could be hard.

I could write this plugin in my spare time, but I'm not sure, this would be against blizzard terms of use?

**Comment by Epix37** [comment] 2016-04-11 07:24
Duplicate of #1410.

Feel free to make such a plugin, sure.

**Closed by Epix37** 2016-04-11 07:24 UTC
Labels: deckbuilder
