### ISSUE TITLE
BUG with spell: Entomb

### ISSUE THREAD

**Issue by knoxius** [Epix37/Hearthstone-Deck-Tracker#1820] opened 2015-12-06 00:07 UTC
i just saw somebody else wrote about it, but they didn't bother to give any details. well, i will.

1. i use spell: entomb on piloted shredder (it goes to my deck)
2. i draw piloted shredder while having chromaggus on the board
3. HDT says: deck has a mismatch and gives options either to continue or choose no deck

p.s. i don't know, but if i had to guess, hdt client would bug out if i had chromaggus effect going or not, either way please fix it, thanks.

my civic duty is done, have a good day everyone

**Comment by Epix37** [comment] 2015-12-06 09:24
Thank you for reporting the issue.


Duplicate of #1815.

**Closed by Epix37** 2015-12-06 09:24 UTC
