### ISSUE TITLE
Incorrect versioning when uploading to hearthstats.

### ISSUE THREAD

**Issue by dantedog** [Epix37/Hearthstone-Deck-Tracker#662] opened 2015-02-10 15:30 UTC
I'm seeing a problem where the deck version is off by some amount. It looks kinda like it is lagging behind by 1 version? The cards also appear to be off by a version or so. I attached logs and playerdecks.xml to an email.

**Comment by Epix37** [comment] 2015-02-10 15:32
You mean the numbers displayed on HearthStats? Yea, I think the latest is under "current version". The web end is still being worked on I think.

@trigun0x2?

**Comment by dantedog** [comment] 2015-02-10 15:33
Also in the logs from decktracker, it claims its uploading the wrong versions.

**Comment by Epix37** [comment] 2015-02-10 15:35
Okay, I will have a look, thanks.

**Comment by Epix37** [comment] 2015-02-10 15:42
How did your test decks end up with so many version, especially multiplicates?

**Comment by dantedog** [comment] 2015-02-10 15:45
I created a deck in hdt. Used the sync to upload v1.0.0 to hearthstats. Removed the lowest mana cost card, added a card from the next mana slot. Saved as v2.0.0 . Sync. Removed lowest card... saved as v3.0.0 ...Saved v3.1.0

The multiplicates is purely from deck tracker syncing.

**Comment by dantedog** [comment] 2015-02-10 16:20
v3.1 in tracker:
![image](https://cloud.githubusercontent.com/assets/10820302/6130903/70e17dd2-b116-11e4-9bcb-6d330a5bc99f.png)

After syncing to hearthstats, latest version:
![image](https://cloud.githubusercontent.com/assets/10820302/6130924/a221cd20-b116-11e4-87f2-666255b34bb4.png)

**Comment by trigun0x2** [comment] 2015-02-10 16:21
@dantedog can you link me to the deck? I can check if anything is wrong from the server side.

**Comment by dantedog** [comment] 2015-02-10 16:22
http://hearthstats.net/profiles/69381?locale=en

**Comment by Epix37** [comment] 2015-02-10 16:42
Should be fixed with v0.9.3. Thank you for reporting this.

**Comment by dvide** [comment] 2015-02-10 17:18
Hm, I've just updated to 0.9.3 and ran a full sync. 

On 0.9.2 I changed one of my decks and overwrote it as v1.0 (since I've not got any games assigned to it, I didn't want multiple versions of it). At the time I checked and it updated that deck on HearthStats as v1.0, not as a new version, as it should have.

Now that I've just run the full sync, it's added a second identical v1.0 on HearthStats. Not sure if this is something that's just been introduced in 0.9.3 (can't remember if I did a full sync in 0.9.2 sorry).

Deck on HearthStats: http://hearthstats.net/decks/giants-mage--29?locale=en

If I do HEARTHSTATS->DELETE SELECTED DECK, and then do another full sync, will it sort this you think?

**Comment by Epix37** [comment] 2015-02-10 17:28
`HEARTHSTATS > DELETE SELECTED DECK` will only delete one of the version, but clear all ids locally for it to be syncable again. So you can do that, manually delete the other and then resync.

**Comment by dvide** [comment] 2015-02-10 17:30
By 'manually delete the other', do you mean delete on HearthStats website? I only have one version on HDT.

**Comment by Epix37** [comment] 2015-02-10 17:31
Sorry, I thought it uploaded two decks, not two versions. In which case I meant the second deck on hearthstats. But just `delete selected version` and syncing again should do the trick.

**Comment by dvide** [comment] 2015-02-10 17:33
Delete selected deck you mean? :)

**Comment by dvide** [comment] 2015-02-10 17:37
I just tested this on another deck. I edited a versionless deck in HDT, and resaved it as v1.0. It automatically updated the deck on HearthStats as v1.0 to correspond to the change (as expected). Then I did a full sync, and it didn't create two v1.0 this time on HearthStats. So that's good.

**Comment by Epix37** [comment] 2015-02-10 17:40
deck, yes. Sounds like something finally starts to work as intended!

**Comment by dvide** [comment] 2015-02-10 17:42
Okay that worked with the Giants Mage deck. 

Obviously it invalidated the previous link when the deck got deleted, here's the new one:
http://hearthstats.net/decks/giants-mage--32?locale=en

**Closed** 2016-02-23 22:26 UTC
