### ISSUE TITLE
Secret tracker not working properly

### ISSUE THREAD

**Issue by Preyu** [Epix37/Hearthstone-Deck-Tracker#1847] opened 2015-12-11 03:48 UTC
https://gyazo.com/b47dc378a68d5690d1300a23a8742d6d

as you can see in the screenshot, i've attacked face, played a minion, and used hero power... but it greyed out completely wrong secrets.

Explosive trap: I attacked face, didn't trigger (still lit up)
Bear trap: same ^
Misdirect: same ^

the secret ended up being Snake Trap, which was greyed out.

Not sure if this is a solo adventure ONLY related issue, but I don't think it should be.

**Comment by ceceita** [comment] 2015-12-11 22:54
i think its an adventure problem caused by not detecting enemy class , but i think coding it it's a waste of time ..

**Comment by Epix37** [comment] 2016-04-11 07:26
I think this should be fixed.

**Closed by Epix37** 2016-04-11 07:26 UTC
Labels: secrets
