### ISSUE TITLE
[v0.13.18] Auto deck detection problems

### ISSUE THREAD

**Issue by depechenode** [Epix37/Hearthstone-Deck-Tracker#2270] opened 2016-03-27 18:06 UTC
Auto deck selection keeps looking at opponent's deck and causes "Wro ng Deck" selected error.  It turns off auto deck selection even though the correct deck is in use. This is new error since latest release of today

**Comment by Epix37** [comment] 2016-03-27 18:15
Could you [post logs](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) and the as wrong detected cards (warning in the overlay)?

**Comment by depechenode** [comment] 2016-03-27 18:20
k.  how do I get the logs you need?

**Comment by Epix37** [comment] 2016-03-27 18:23
Links are not visible enough here :/.

There you go: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by depechenode** [comment] 2016-03-27 18:32
ok grabbing the log. it just did it again with the release you posted in my other thread today.  I installed that over the auto patched one today.  It also reordered the preference of my player deck window when it errored out on the wrong card detected from opponent's deck.

**Comment by depechenode** [comment] 2016-03-27 18:39
here it is:
http://pastebin.com/UCb0Kp9F

**Comment by depechenode** [comment] 2016-03-27 18:40
so that log has both the wrong deck error and UI Player deck re order of preferences (despite Tracker settings showing correct order).  the reorder happened as the wrong deck selection error occurred.

**Comment by Epix37** [comment] 2016-03-27 18:41
Got the reordering fixed. 

Could you also post the deck you were using? `export > screenshot > upload` is probably the easiest way.

**Comment by Epix37** [comment] 2016-03-27 18:44
Sorry, and the cards that are missing? I.e. the ones the overlay warning contained. 

Apparently I'm not logging that for some reason.

**Comment by depechenode** [comment] 2016-03-27 18:45
k sec...

**Comment by depechenode** [comment] 2016-03-27 18:47
the warning comes when the opponent adds a card from field back to their hand it seems.  Alarm-o-bot did this in one game as well.  In this log i sent you, it was Archmage Antonidas.  BOth times were the opponent regaining a card in hand.

**Comment by depechenode** [comment] 2016-03-27 18:50
![depechenode_magic_control](https://cloud.githubusercontent.com/assets/15825689/14067124/ce16036a-f422-11e5-9d46-6ae5b6b21d19.png)

**Comment by depechenode** [comment] 2016-03-27 18:50
notice I never had the card in my deck.  the error was reporting from opponent's and the tracker thought is was my deck missing the card.

**Comment by Epix37** [comment] 2016-03-27 19:29
Alright, i updated the [**pre-release download**](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.13.18/Hearthstone.Deck.Tracker-v0.13.18.zip) again. 

I'm not sure I entirely solved the problem but I do think I may have isolated it well enough. Let me know if you are still having the same problems with the current download.

**Comment by depechenode** [comment] 2016-03-27 19:38
k will test it thank you

**Comment by depechenode** [comment] 2016-03-27 19:44
it isn't auto switching now to the correct deck.  I unzipped the release you just posted and extracted over top the current one.   I manually selected a deck in tracker but chose the correct deck I want to play in HS. when HS started game, the manual choice is still highlighted in tracker and wont switch to the correct in use.  I tried to click AUTO on and off and still no go.

**Comment by depechenode** [comment] 2016-03-27 19:44
If I manually click the deck in the tracker even with AUTO highlighted it then shows the correct is in use.

**Comment by depechenode** [comment] 2016-03-27 19:47
so far though, the deck visual order pref is retaining itself. so far...

**Comment by depechenode** [comment] 2016-03-27 19:49
oh just noticed.. the auto deck is only issued when same CLASS is played but different decks.  I use two diff mage decks.  Just tried with a warlock and it auto detected fine.

**Comment by Epix37** [comment] 2016-03-27 19:50
Did you actually draw cards that were not in the deck in that case? Deck detection works by checking if the drawn cards match the selected deck, so with the same class and especially before mulligan there is a chance it won't trigger.

**Comment by depechenode** [comment] 2016-03-27 19:51
yea it will warn me that a card does not exist

**Comment by Epix37** [comment] 2016-03-27 19:52
Hm.. see if that problem remains. It seems to working fine for me.

**Comment by depechenode** [comment] 2016-03-27 19:52
ok.  should the tracker still be highlighting the mage deck though? even though active deck is warlock?

**Comment by depechenode** [comment] 2016-03-27 19:54
If I click while playing a different deck in tracker, it highlights that deck in window, gives the cant find card error, but the active deck remains correct and next card it fixes the deck in HS.  but the deck in tracker remains highlighted even though it is not the correct active deck. I hopeI make sense

**Comment by depechenode** [comment] 2016-03-27 19:55
sometimes text doesnt really explain what I am seeing..

**Comment by Epix37** [comment] 2016-03-27 20:00
The deck list still shows the wrong deck as selected, but it is correct in the game overlay, yes?

If it's only highlighted (selected) in the deck list but it does not say 'ACTIVE' and the name is not bold, then that's fine.

**Comment by depechenode** [comment] 2016-03-27 20:01
k yea, the correct deck does go BOLD type, I was referring to the highlight when yo click the deck in tracker.

**Comment by depechenode** [comment] 2016-03-27 20:02
so it does appear that the auto deck may be fixed.   so far no other issues.  But I have not faced a player that pulls cards back into their hand yet to fully test.. hopefully soon..

**Comment by depechenode** [comment] 2016-03-27 20:19
I do see a different thing.   the white gift icon appears on my deck window in deck list when i mulligan the cards.  the same icon as the coin shows now.  Also the two cards that I mulliganed for, at the start of the game told me cards did not exist in deck.  Had the correct deck, in tracker and in game.  the error went away after mulligan, but the icons on MY player deck list interface appear to be wrong.

**Comment by depechenode** [comment] 2016-03-27 20:23
![iconerror_counterror](https://cloud.githubusercontent.com/assets/15825689/14067686/cff3ed66-f42f-11e5-8339-35d77b713254.png)

**Comment by depechenode** [comment] 2016-03-27 20:23
AND.. look at the deck count.  54 cards?   opponent showed they had 48 btw

**Comment by depechenode** [comment] 2016-03-27 20:26
and once again, these anomalies seem to only open when I have multiple class decks.  I have one warlock but three mage decks.  when I swap to mage from other class or from one mage to another mage this is where I see issues.

**Comment by depechenode** [comment] 2016-03-27 20:27
Next game I used the same deck and the deck count was correct again

**Comment by Epix37** [comment] 2016-03-27 20:35
Could you post the logs of those games?

(I'm going to bed for now, I'll have a look tomorrow.)

**Comment by depechenode** [comment] 2016-03-27 20:37
I can zip all the logs for the passed games if you want.  I have a couple of screenshots too that may help.  is there an email addy to send the zip?

**Comment by Epix37** [comment] 2016-03-27 20:55
epix@hsdecktracker.net

**Comment by depechenode** [comment] 2016-03-27 21:08
sent

**Comment by Epix37** [comment] 2016-03-28 19:54
Alright, I just spent about 13 hours rewriting basically the whole game state and deck tracking system.

Give this a shot: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.18.3

I'm fairly confident the deck selection is fixed. There might be a few new issues (cards getting removed from deck lists/not appearing), but it seems to be ok for the most part. Card animations when going grayed out to normal are a bit wonky.

Let me know how this one works for you.

**Comment by depechenode** [comment] 2016-03-28 21:52
Well it is worse.  It won't detect deck at all.

**Comment by depechenode** [comment] 2016-03-28 21:53
should I delete the tracker and reinstall fresh?

**Comment by depechenode** [comment] 2016-03-28 21:55
and it is not showing opponents cards in deck list as they play.  Stats are messing up too

**Comment by Epix37** [comment] 2016-03-28 21:57
try just restarting hdt and hs

**Comment by depechenode** [comment] 2016-03-28 21:59
k thanks bud will do after this match

**Comment by depechenode** [comment] 2016-03-28 22:03
ok it found correct deck but tells me cards not found in deck even though that are in deck.. the cards it is telling are the cards on the draw and the list shows them as white presents. after mulligan, the warning goes away.  Going finish the match and try swapping decks...

**Comment by depechenode** [comment] 2016-03-28 22:08
the deck list on UI also shows duplicates now of cards.   I have two screenshots for you in a minute

**Comment by depechenode** [comment] 2016-03-28 22:08
it is like the cards are not leaving the list as I play instead the list is growing

**Comment by depechenode** [comment] 2016-03-28 22:09
and opponent cards are still not showing in VS. deck list

**Comment by depechenode** [comment] 2016-03-28 22:14
![screen1](https://cloud.githubusercontent.com/assets/15825689/14091891/7b89251e-f508-11e5-897f-0f98184f27fd.png)
![screen2](https://cloud.githubusercontent.com/assets/15825689/14091894/7d46efb2-f508-11e5-8b35-fa6b4e343d92.png)

**Comment by depechenode** [comment] 2016-03-28 22:15
1st screen BEFORE mulligan, second is after mulligan and during the match  notice the white present boxes on both, as well as NO opponent cards listed.

**Comment by depechenode** [comment] 2016-03-28 22:17
playing another match now... changed to one of my mage decks, it found it but I have that pre mulligan error warning of cards not found still. and it goes away after mulligan, still have the extra cards listed after mulligan in list too..

**Comment by depechenode** [comment] 2016-03-28 22:18
also still not getting opponent cards in list

**Comment by depechenode** [comment] 2016-03-28 22:24
new error never seen before as game match ended....
![errorasgameended](https://cloud.githubusercontent.com/assets/15825689/14092078/dbb827ea-f509-11e5-91f7-1b79a4ab9bbe.png)

**Comment by depechenode** [comment] 2016-03-28 22:26
posted the crash txt on that paste site

**Comment by depechenode** [comment] 2016-03-28 22:32
I am recording a game going to zip it and send if not too large

**Comment by depechenode** [comment] 2016-03-28 22:34
go figure I get a slow player in match grrrrrrrrrrrrr

**Comment by depechenode** [comment] 2016-03-28 22:34
I will concede the match in two more turns so shorten the video.

**Comment by Epix37** [comment] 2016-03-28 22:38
I think there might be something weird going on with your hearthstone logging or config. 

Try this: 
- Close HDT and Hearthstone
- Run "HDTUninstaller.exe" and remove the `Hearthstone Logging`
- Go to "%AppData%/HearthstoneDeckTracker" (paste into Run dialog or explorer address bar), rename the "config.xml" to anything else
- Go `[Hearthstone Install Dir]/Logs`, delete everything
- Try again

**Comment by depechenode** [comment] 2016-03-28 22:38
k

**Comment by Epix37** [comment] 2016-03-28 22:53
Here's a fix for the crash: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.18.4

**Comment by depechenode** [comment] 2016-03-28 22:53
do I have to reset all my preferences in tracker now? Or can I somehow import just the prefs?

**Comment by Epix37** [comment] 2016-03-28 22:55
Try running it without changing any default settings, see if you still have the problems.

**Comment by depechenode** [comment] 2016-03-28 22:56
k so far it wont find the right deck  stays at no active deck selected I had to manually select

**Comment by depechenode** [comment] 2016-03-28 22:57
but this is the 13.18.3 version

**Comment by depechenode** [comment] 2016-03-28 22:59
now it is finding the decks

**Comment by depechenode** [comment] 2016-03-28 22:59
but i get that same error on start before mulligan

**Comment by depechenode** [comment] 2016-03-28 23:00
i have not changed any default settings
it is acting like it did earlier before the deleting of my config/logs

**Comment by depechenode** [comment] 2016-03-28 23:07
it is also reverting to version 1.0 of my decks instead of staying at 1.1 etc.  in the tracker

**Comment by Epix37** [comment] 2016-03-28 23:08
You can delete the new config.xml then and rename your old one back. (Close HDT before doing that)

It seems HDT thinks your setup phase is done before it even started. 

- There is a slim chance this is some weird .NET issue, try updating/reinstalling your .NET Framework installation.
- Try running HDT from a "clean installation" i.e. not overwriting the old files
- Please email me the "Power.log" file from the "Hearthstone/Logs" folder after a game or two

**Comment by depechenode** [comment] 2016-03-28 23:09
like literally in the tracker of my ALL, i have a mage deck that is 1.0 and 1.1.  I use 1.1  this next game it swapped  the deck to 1.0 in tracker on its own when I selected that deck in HS.  then threw the Card not found at top of HS.  Ihad to switch the deck to v1.1 manually in tracker

**Comment by depechenode** [comment] 2016-03-28 23:09
ok
 I am running Windows 10 Enterprise if you need that info

**Comment by depechenode** [comment] 2016-03-28 23:11
all the issues only happened after the weekend live update this past weekend where the card fading / themes stuff was added.

**Comment by depechenode** [comment] 2016-03-28 23:40
it is still having issues with deck versions

**Comment by depechenode** [comment] 2016-03-28 23:55
it is also still not removing the "draw" cards from my deck list and shows them as white presents still so it shows basically three copies if I have only two in deck or two if I have only 1

**Comment by depechenode** [comment] 2016-03-28 23:55
and again.. opponent cards are not displaying in the other deck list

**Comment by depechenode** [comment] 2016-03-29 04:07
I noticed my LOG.CONFIG file was different than the one you posted in the FAQ.  So I copied yours and set it for my use.  The game seems to work now, still get the initial card not found error prior to mulligan on the initial draw, but once mulligan is over, it seems to be working.  The major item that was diff in my log.config was the verbose command set to false.  your default  is true.  THAT might be why my logs were messing up.

**Comment by depechenode** [comment] 2016-03-29 04:08
and one quick ?, why do some of the cards in the deck list "grey" out?  I understand the Green highlight of the card name, but I dont get the greying out of the background?  Some cards in my hand cause the list to grey them out, but some are in my hand and do not grey out the card in the list..  Just wondering!

**Comment by depechenode** [comment] 2016-03-29 04:15
of course as I posted the last message I got an hard crash error causing tracker to shut down.  Deck Collection error something about a change to the deck?  But it was while I was in a match.
########## 3/28/2016 11:09:16 PM ##########
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Hearthstone_Deck_Tracker.Controls.AnimatedCardList.Update(List`1 cards, Boolean player, Boolean reset)
   at Hearthstone_Deck_Tracker.Core.<UpdatePlayerCards>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by depechenode** [comment] 2016-03-29 04:24
and it is back to after changing decks putting duplicate entries in the list as well as NOT displaying the opponents played cards in their list.

**Comment by Epix37** [comment] 2016-03-29 08:24
I *think* I managed to fix it. Here goes nothing: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.18.5

I was able to reproduce the problem consistently and now I no longer can, so that's something I hope.
(also fixed the above posted crash)

**Comment by depechenode** [comment] 2016-03-29 21:50
so far so good... trying another match with different deck to see how it goes.. but yep looks great so far!!!!!

**Comment by depechenode** [comment] 2016-03-29 21:56
still not sure what the "grey" background on deck list cards means.  the card warning still only appears just at mulligan/initial draw but goes away.  the correct deck is found instantly though.

**Comment by depechenode** [comment] 2016-03-29 21:57
I just got a card via "discovery" and it has grey background in deck list, not a present symbol.  On initial draw, one of the cards on the screen was grey background in list as well.

**Comment by depechenode** [comment] 2016-03-29 22:05
![draw1](https://cloud.githubusercontent.com/assets/15825689/14125361/70b3ff7e-f5d0-11e5-8a37-aa276cf62298.png)

**Comment by depechenode** [comment] 2016-03-29 22:05
![draw2](https://cloud.githubusercontent.com/assets/15825689/14125365/76c55552-f5d0-11e5-9c2a-05e43599e5df.png)

**Comment by depechenode** [comment] 2016-03-29 22:05
![draw3](https://cloud.githubusercontent.com/assets/15825689/14125367/7a928e70-f5d0-11e5-9d2b-9391970bc63b.png)

**Comment by Epix37** [comment] 2016-03-30 05:43
I assume you have "remove cards at 0" and "highlight cards in hand" enabled? This is exactly the result of that. Grayed out means it's no longer in the deck, and for it to be highlighted while in hand it can't be removed from the list yet.

**Comment by Epix37** [comment] 2016-03-30 14:09
should be all fixed with the v0.13.19 pre-release

**Closed by Epix37** 2016-03-30 14:09 UTC
Labels: beta, decktracker

**Comment by depechenode** [comment] 2016-03-31 02:36
everything works great except, I can no longer export deck to HS.  The log says it exported successfully, however,( when you try to export), the mouse does no focus on HS and nothing happens in HS.
