### ISSUE TITLE
Entomb bug

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#2025] opened 2016-01-28 06:01 UTC
I played a game as Priest. I play Entomb on opponent's Sludge Belcher. Opponent plays Deathlord. I kill Deathlord, and it draws the Sludge Belcher that I Entombed onto the field. HDT is then confused, and shows a message saying that the deck I'm playing with doesn't match the deck in its database, due to the extra Sludge Belcher.

Obviously a bug regarding Entombed minions then.

**Comment by Epix37** [comment] 2016-01-28 11:20
Could you post a HDT log and/or hs log of that (replay also works)?

**Comment by GaryKing** [comment] 2016-01-28 19:27
Log attached for the game between me as Priest vs. another player as Priest.

[Gary(Priest) vs War(Priest) 2128-270116.hdtreplay.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/108758/Gary.Priest.vs.War.Priest.2128-270116.hdtreplay.zip)

Relevant turns: Opponent plays Sludge Belcher and I Entomb it, both on Turn 7.
Sludge Belcher is pulled from Deathlord on Turn 15.

**Comment by stoppi123** [comment] 2016-02-05 10:13
I can confirm this, I first thought this is just an entomb bug. because it happend multiple times to me. Here is a replay of a turn 7 dr. boom, I entombed it (turn 7), and it came out of his deathlord turn 15.
[HDTReplay.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/118924/HDTReplay.zip)
"Error, card not found in deck"

**Comment by Mazurem** [comment] 2016-02-19 13:35
I just had this happen. It's weird because usually entomb works fine for me. Hopefully a log will help.

http://pastebin.com/krxQDGGc

Sneeds goes into my deck:
[13:14:33] Player BoardToDeck: id=28, cardId=GVG_114, cardName=Sneed's Old Shredder, turn=8, zonePos=2, created=true

Then the game is confused when it sees Sneeds in my deck:
[13:19:12] Player DeckDiscard: id=28, cardId=GVG_114, cardName=Sneed's Old Shredder, turn=12, zonePos=0, created=true
[13:19:12] GameEventHandler: Found incorrect deck on PlayerDeckDiscard
[13:19:13] IncorrectDeckMessage: 0 possible decks found.
[13:19:21] IncorrectDeckMessage: Now ignoring Dragon Priest as an incorrect deck

**Comment by Epix37** [comment] 2016-03-31 09:55
This should be fixed with v0.14.0.

**Closed by Epix37** 2016-03-31 09:55 UTC
Labels: bug, unconfirmed
