### ISSUE TITLE
Problem with Golden Monkey

### ISSUE THREAD

**Issue by Laperst** [Epix37/Hearthstone-Deck-Tracker#2239] opened 2016-03-18 23:31 UTC
Hi guys idk if somebody report this already. When you play golden monkey 4 mana 6/6 repleace your hand and deck with legendaries, then tracker isnt showing cards in deck. I know it dunno which legendaries you get, but can you add something to protect misstake with fattigue (like you have X legendaries)?

**Comment by bajungadustin** [comment] 2016-03-21 03:29
Would be cool to add [Legendary Gift Gard] block that would just be stacked up and replace your existing cards... cause it wont know which ones you have.. but you would still have a visual representation of the amount of cards you have left... 

this is really just polish.. but... that would be some legit polish.

**Comment by jleclanche** [comment] 2016-03-24 14:45
Dupe of #2224

**Closed by jleclanche** 2016-03-24 14:45 UTC
