### ISSUE TITLE
Deck version not saving

### ISSUE THREAD

**Issue by frodo010595** [Epix37/Hearthstone-Deck-Tracker#1692] opened 2015-11-02 07:43 UTC
Hi,
I have had a problem for a while when it comes to the deck version that is saved inside of the tracker. The problem is mostly a nuisance but still worth reporting I think.
Whenever I create a deck inside of the tracker everything is fine, it syncs with hearthstats and is there when I launch the tracker. However, most of the times when I create a different version of the deck, V1.2-1.5ish, the deck will upload to hearthstats and be saved there. But when I then exit the tracker and launch it again, the deck will have reverted back to the version that it was before, even if I create multiple new deck versions the tracker will jump backwards to the original one. This happens most of the time and I can't seem to find the source of the problem.
However, as soon as I click the "Force Full Sync" button, the tracker will update the deck to the correct version. It seems unreliable weather or not the "Sync Now" button does this.
Like I said, this is mostly a nuisance since you can get the deck version simply be syncing, but sometimes I forget and end up in a game with the wrong deck. =P
But anyways, thank you for creating this aweseom software, keep up the good work. :)

**Comment by cerobe** [comment] 2016-02-03 20:21
Hi,
i have the same problem here. As you do, I'm trying to full sync before playing to have the right version of the deck.

**Comment by Epix37** [comment] 2016-04-15 07:35
Duplicate of #1508.

**Closed by Epix37** 2016-04-15 07:35 UTC
Labels: HearthStats
