### ISSUE TITLE
Some errors with this replay

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#569] opened 2015-01-10 23:38 UTC
https://www.dropbox.com/s/ivdl2ulrjgv4ne2/dvide%28Mage%29%20vs%20alle0100%28Mage%29%202050-100115.hdtreplay?dl=0

Turn 11: When the opponent plays Water Elemental, it should still show two Mirror Image taunt minions on the board. One of them disappears. The Water Elemental was positioned on the far left. The board state shows up correctly at the start of turn 12.

Turn 13: When the Water Elemental attacks my face, the Mirror Image taunt minion randomly disappears again.

Turn 13: When the opponent plays arcane missiles, two missiles hit my face and one hit the sheep triggering duplicate. Obtaining the two sheep shows up correctly but it doesn't show the death of the sheep. The sheep still shows up as alive on the board on turn 14.

Turn 14: After I play the two duplicated sheep from my hand, the board state is correct again.

Turn 17: Opponent's Dr. Boom summons two boom bots but the second one doesn't show up on the board right away (on the 'Summon Boom Bot' action).

Turn 18: Both Boom Bots die to a Flamestrike but the damage they do with their deathrattles do not show up right away on their death actions. The Boom Bot on the right did 4 damage to the Loatheb, and the one on the left did 1 damage to my face. Not sure if this one is a bug or not.

Turn 18: When the Loatheb attacks Dr. Boom, the ghost sheep shows up again. It doesn't disappear again until Turn 20 when I play my coin.

Turn 22: When Kel'Thuzad attacks the Defender of Argus, the sheep shows up again.

Turn 24: When I Polymorph the opponent's Soot Spewer, it doesn't show the summoning of the sheep. When I Fireblast the sheep, I didn't Fireblast anything according to the replay visualization.

Turn 24: When Kel'Thuzad attacks the opponent's face, the sheep shows up again.

Turn 26: When Spectral Knight attacks the opponent's face, it disappears. When Kel'Thuzad attacks the opponent's face, the Spectral Knight returns but Kel'Thuzad now disappears and it shows the ghost sheep again.

Turn 28: When Kel'Thuzad attacks the opponent's face, it disappears again and is replaced with the sheep. When the Spectral Knight attacks, it disappears again. When the Twilight Drake attacks, the Sludge Belcher disappears. When the Sludge Belcher attacks everything looks correct.

**Comment by Epix37** [comment] 2015-01-11 09:13
I think I found the cause.

**Comment by Epix37** [comment] 2015-01-11 11:05
should be fixed with v0.7.5

**Closed by Epix37** 2015-01-11 11:05 UTC
