### ISSUE TITLE
After update to Win10 tracking is not working. 

### ISSUE THREAD

**Issue by ExterminanzHS** [Epix37/Hearthstone-Deck-Tracker#1453] opened 2015-09-12 13:04 UTC
HDT displays the deck but is not tracking any stats or movements during games. 

- checked .net framework already, up to date (that's what the installer said when i tried to install)
- compatibility mode and running as administrator did not fix the issue 
- copy a new log file did not solve the problem
- Hearthstone directory is set correctly, I checked in the file. 

Please help for further troubleshooting, maybe i am missing something really simple?

**Comment by Epix37** [comment] 2015-09-14 08:07
Any chance this just fixed itself by now? If you delete the log.config, does HDT create a new one?

**Comment by ExterminanzHS** [comment] 2015-09-14 21:10
nope, sorry but it's still not fixed. HDT created a new one but the overlay functions still don't work.

**Comment by riQQ** [comment] 2015-09-14 21:22
Are the logs in the directory `Hearthstone\Logs` created and filled?
What does the HDT log say (`Options -> Logging`)?

**Comment by ExterminanzHS** [comment] 2015-09-14 21:36
yes, there are as of now 5 files with system info. 
update did not fix the issue :(

HDT Log (did not find option logging in HDT, that's content of the files in HDT->Logs):
[22:31:34] Game: set CurrentGameMode to None
[22:31:34] HearthStatsAPI: Loading stored credentials...
[22:31:35] Game: -------- Reset ---------
[22:31:35] OpponentSecrets: Cleared secrets
[22:31:35] DeckList: Set active deck to: MalyLock (Warlock)
[22:31:35] Tracker: Switched to deck: MalyLock
[22:31:35] Game: -------- Reset ---------
[22:31:35] OpponentSecrets: Cleared secrets
[22:31:35] GameEventHandler: Reset constructed importing
[22:31:35] Helper: Checking for LIVE updates...
[22:31:35] Helper: Current version: 0.11.2.0
[22:31:35] LogReader: Current region: EU
[22:31:36] UpdateOverlay: Refreshed overlay topmost status
[22:31:36] BackupManager: Running BackupManager
[22:31:36] BackupManager: Backup for today already exists
[22:31:36] PluginManager: Loading Plugins...
[22:31:37] : Checking for duplicate matches...
[22:31:37] Helper: Latest LIVE version: 0.11.3.0

**Comment by riQQ** [comment] 2015-09-14 22:12
Nothing unusual there. What are the contents of the `Logs` folder?

**Comment by ExterminanzHS** [comment] 2015-09-14 22:17
HDT Logs, just some .txt files (hdt_log, then some logs with hdt_log_digits)
Hearthstone logs: just .txt as well, all from today

**Comment by Epix37** [comment] 2015-09-14 22:26
Does the `Hearthstone/Logs` folder contain any files called "*_old.log"? If not, does it if you start HDT without Hearthstone running?

If not, one of two things is the case:
* HDT has absoluetly not access to that directory for some reason.
* The Hearthstone directory is not correct after all (I think this is the more likely one). Try closing HDT and deleting the config.xml found in `%AppData%/HearthstoneDeckTracker`.

**Comment by ExterminanzHS** [comment] 2015-09-14 22:35
yes, there are files _old.log in Hearthstone/logs (Sorry about confusion, did just look the appdata logs up >.< )

**Comment by Epix37** [comment] 2015-09-14 22:40
Hm...

Play a game with HDT running (don't close Hearthstone after), and post the "Hearthstone/Logs/Power.log", "Hearthstone/Logs/Bob.log" and "%AppData%/HearthstoneDeckTracker/Logs/hdt_log.txt" here. (http://pastebin.com/)

**Comment by ExterminanzHS** [comment] 2015-09-14 22:59
unable to use pastebin for some reason... 
here are the files in Zippyshare:
http://www36.zippyshare.com/v/AkGKfKR1/file.html

**Comment by Epix37** [comment] 2015-09-14 23:00
That's a) only one file and b) Bob_old.log, not Bob.log :P.

**Comment by ExterminanzHS** [comment] 2015-09-14 23:01
haha, sorry... it actually did not create Bob.log, only the old one is there after I did what you said and played a game

**Comment by Epix37** [comment] 2015-09-14 23:04
* Close Hearthstone
* Delete all the files in Hearthstone/Logs
* Start hearthstone + a (practice if you like) game
* Are there any files in Hearthstone/Logs?

**Comment by ExterminanzHS** [comment] 2015-09-14 23:07
did what you said, only one file appeared which is Achievements.log

**Comment by Epix37** [comment] 2015-09-14 23:09
"%LocalAppData%/Blizzard/Hearthstone/log.config" - what's the content of that file?

**Comment by ExterminanzHS** [comment] 2015-09-14 23:11
%AppData%\Local\Blizzard\Hearthstone\log.config:


[Zone]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true
[Bob]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true
[Power]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true
[Asset]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true
[Rachelle]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true
[Arena]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true
[Achievements]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

**Comment by ExterminanzHS** [comment] 2015-09-14 23:12
btw, you are really good :) really appreciate the help!

**Comment by Epix37** [comment] 2015-09-14 23:13
Apparently not good enough, I don't understand this at all...
Try.. reinstalling Hearthstone? I'm out of ideas :(

**Comment by ExterminanzHS** [comment] 2015-09-14 23:15
ok, will do that (set Heartstone and HDT up completely new)

**Comment by ExterminanzHS** [comment] 2015-09-14 23:35
Reinstall did not help :/

seems like i am just not worthy :D

**Comment by riQQ** [comment] 2015-09-15 22:13
So this is a Hearthstone problem, if some logs aren't even created. But the existence of the *_old.log files means that it has been working in the past.

**Comment by quark-zju** [comment] 2015-09-23 09:27
I have encountered this issue as well. Strangely, the tracker *sometimes* works but *sometimes* totally not working. Deleting all .log files won't help. I am going to start Visual Studio to try to figure out more.

**Comment by quark-zju** [comment] 2015-09-23 10:11
The issue is fixed in the last build (9a9a4a199e840bba7cd2c2dead25ba772aead8e8). I am going to bisect this.

**Comment by quark-zju** [comment] 2015-09-23 10:58
It turns out the latest release also works here. I was using the wrong exe named `HearthstoneDeckTracker.exe`, which is probably copied from my long-time-ago VS build. HDTUpdate wrote `Hearthstone Deck Tracker.exe` and did not find the file name issue.

**Closed** 2016-03-25 16:20 UTC
