### ISSUE TITLE
No longer recording stats on v0.13.6

### ISSUE THREAD

**Issue by avatarx0** [Epix37/Hearthstone-Deck-Tracker#1881] opened 2015-12-17 16:25 UTC
v0.13.6 update note says screen dimming software might cause problems. I'm using f.lux program. I'm not sure if it's causing the problem but the new v0.13.6 version no longer records games results. I didn't have this problem with previous versions.

**Comment by Epix37** [comment] 2015-12-17 16:42
The worst case with screen dimming should be that ranked games are recorded as casual. 

HDT now uses another log to detect the rank (has to be enabled)  -  see if restarting Hearthstone and HDT helps.

**Comment by avatarx0** [comment] 2015-12-17 16:54
"HDT now uses another log to detect the rank (has to be enabled)" - where is that option?

I restarted both Hearthstone and HDT but it was still not recording game result. It tracks cards fine but it just wouldn't record results. 

I went back to v0.13.3 and it works fine.

**Comment by Epix37** [comment] 2015-12-17 17:05
Does it not record ranked *at all* or just as casual? 

Can you disable Flux and see if that fixed it?

**Comment by avatarx0** [comment] 2015-12-17 17:22
It does not record ranked games at all. I disabled f.lux but I still had the same problem.

**Comment by ginko147** [comment] 2015-12-17 20:56
Same problem here. I disabled flux and everything and my games is recored as Casual. Here is the log:

[22:46:26] UpdateOverlay: Refreshed overlay topmost status
[22:46:44] GameEventHandler: --- Game start ---
[22:46:44] Game: -------- Reset ---------
[22:46:44] Player Name: 
[22:46:44] Opponent Name: 
[22:46:44] OpponentSecrets: Cleared secrets
[22:46:44] GameEventHandler: --- Mulligan ---
[22:46:44] Opponent Draw: id=16, cardId=, cardName=, turn=0
[22:46:44] Opponent Draw: id=17, cardId=, cardName=, turn=0
[22:46:44] Opponent Draw: id=24, cardId=, cardName=, turn=0
[22:46:44] Player Draw: id=43, cardId=LOE_079, cardName=Elise Starseeker, turn=0
[22:46:44] Player Draw: id=46, cardId=GVG_110, cardName=Dr. Boom, turn=0
[22:46:44] Player Draw: id=49, cardId=EX1_558, cardName=Harrison Jones, turn=0
[22:46:45] Player Draw: id=50, cardId=CS2_106, cardName=Fiery War Axe, turn=0
[22:46:45] TagChangeHandler: Found hero with id=64
[22:46:45] GameEventHandler: Opponent=Shaman
[22:46:45] TagChangeHandler: Found hero with id=66
[22:46:45] GameEventHandler: Player=Warrior
[22:46:45] Player CreateInHand: id=68, cardId=GAME_005, cardName=The Coin, turn=0, mark=Coin, created=true
[22:46:45] GameStats: Got coin
[22:46:46] Player Name: ginko
[22:46:46] Opponent Name: moonklim
[22:47:08] Player Draw: id=44, cardId=AT_132, cardName=Justicar Trueheart, turn=0
[22:47:08] Player Mulligan: id=43, cardId=LOE_079, cardName=Elise Starseeker, turn=0
[22:47:08] Player Draw: id=39, cardId=EX1_606, cardName=Shield Block, turn=0
[22:47:08] Player Mulligan: id=46, cardId=GVG_110, cardName=Dr. Boom, turn=0
[22:47:11] Opponent Draw: id=23, cardId=, cardName=, turn=0
[22:47:11] Opponent Mulligan: id=16, cardId=, cardName=, turn=0
[22:47:11] Opponent Draw: id=33, cardId=, cardName=, turn=0
[22:47:11] Opponent Mulligan: id=17, cardId=, cardName=, turn=0
[22:47:13] GameEventHandler: Trying to detect ranks... (tries=0, overlaytoggles=0)
[22:47:13] Overlay: No ranks should be covered by any decks.
[22:47:13] GameEventHandler: --- Opponent turn 1 ---
[22:47:13] GameEventHandler: No ranks were detected.
[22:47:16] Opponent Draw: id=20, cardId=, cardName=, turn=1
[22:47:21] GameEventHandler: Trying to detect ranks... (tries=1, overlaytoggles=0)
[22:47:21] Overlay: No ranks should be covered by any decks.
[22:47:21] GameEventHandler: --- Player turn 2 ---
[22:47:21] Player Draw: id=43, cardId=LOE_079, cardName=Elise Starseeker, turn=1
[22:47:22] GameEventHandler: No ranks were detected.
[22:47:31] GameEventHandler: Trying to detect ranks... (tries=2, overlaytoggles=0)
[22:47:31] Overlay: No ranks should be covered by any decks.
[22:47:31] GameEventHandler: --- Opponent turn 2 ---
[22:47:31] Opponent Draw: id=32, cardId=, cardName=, turn=2
[22:47:32] GameEventHandler: No ranks were detected.
[22:47:36] Opponent Play: id=24, cardId=AT_052, cardName=Totem Golem, turn=2
[22:47:38] GameEventHandler: Trying to detect ranks... (tries=3, overlaytoggles=0)
[22:47:38] Overlay: No ranks should be covered by any decks.
[22:47:38] GameEventHandler: --- Player turn 3 ---
[22:47:38] Player Draw: id=58, cardId=EX1_005, cardName=Big Game Hunter, turn=2
[22:47:39] GameEventHandler: No ranks were detected.
[22:47:55] GameEventHandler: PlayerHeroPower (id:CS2_102 turn:2 from:-1)
[22:47:57] GameEventHandler: Trying to detect ranks... (tries=4, overlaytoggles=0)
[22:47:57] Overlay: No ranks should be covered by any decks.
[22:47:57] GameEventHandler: --- Opponent turn 3 ---
[22:47:57] Opponent Draw: id=5, cardId=, cardName=, turn=3
[22:47:57] GameEventHandler: No ranks were detected.
[22:48:02] Opponent Play: id=33, cardId=AT_052, cardName=Totem Golem, turn=3, mark=Mulliganed
[22:48:08] GameEventHandler: Trying to detect ranks... (tries=5, overlaytoggles=0)
[22:48:08] Overlay: No ranks should be covered by any decks.
[22:48:08] GameEventHandler: --- Player turn 4 ---
[22:48:08] Player Draw: id=56, cardId=FP1_012, cardName=Sludge Belcher, turn=3
[22:48:09] GameEventHandler: No ranks were detected.
[22:48:23] Player Play: id=68, cardId=GAME_005, cardName=The Coin, turn=3, mark=Coin, created=true
[22:48:24] Player PlayToGraveyard: id=68, cardId=GAME_005, cardName=The Coin, turn=3, mark=Coin, created=true
[22:48:25] Player Play: id=43, cardId=LOE_079, cardName=Elise Starseeker, turn=3
[22:48:25] : Found known cardId for entity 69: LOE_019t
[22:48:25] Player CreateInDeck: id=69, cardId=LOE_019t, cardName=Map to the Golden Monkey, turn=3, mark=Created
[22:48:31] GameEventHandler: Trying to detect ranks... (tries=6, overlaytoggles=0)
[22:48:31] Overlay: No ranks should be covered by any decks.
[22:48:31] GameEventHandler: --- Opponent turn 4 ---
[22:48:31] Opponent Draw: id=12, cardId=, cardName=, turn=4
[22:48:31] GameEventHandler: No ranks were detected.
[22:48:38] Opponent Play: id=20, cardId=EX1_248, cardName=Feral Spirit, turn=4
[22:48:40] Opponent CreateInPlay: id=70, cardId=EX1_tk11, cardName=Spirit Wolf, turn=4, mark=Created, created=true
[22:48:40] Opponent CreateInPlay: id=71, cardId=EX1_tk11, cardName=Spirit Wolf, turn=4, mark=Created, created=true
[22:48:41] Opponent PlayToGraveyard: id=20, cardId=EX1_248, cardName=Feral Spirit, turn=4
[22:48:46] GameEventHandler: Trying to detect ranks... (tries=7, overlaytoggles=0)
[22:48:46] Overlay: No ranks should be covered by any decks.
[22:48:46] GameEventHandler: --- Player turn 5 ---
[22:48:46] Player Draw: id=54, cardId=EX1_249, cardName=Baron Geddon, turn=4
[22:48:46] GameEventHandler: No ranks were detected.
[22:48:53] Opponent PlayToGraveyard: id=71, cardId=EX1_tk11, cardName=Spirit Wolf, turn=4, mark=Created, created=true
[22:48:54] Player Play: id=50, cardId=CS2_106, cardName=Fiery War Axe, turn=4
[22:48:56] Opponent PlayToGraveyard: id=70, cardId=EX1_tk11, cardName=Spirit Wolf, turn=4, mark=Created, created=true
[22:48:56] GameEventHandler: PlayerHeroPower (id:CS2_102 turn:4 from:-1)
[22:48:58] GameEventHandler: Trying to detect ranks... (tries=8, overlaytoggles=0)
[22:48:58] Overlay: No ranks should be covered by any decks.
[22:48:58] GameEventHandler: --- Opponent turn 5 ---
[22:48:58] Opponent Draw: id=25, cardId=, cardName=, turn=5
[22:48:58] GameEventHandler: No ranks were detected.
[22:49:09] UpdateOverlay: Refreshed overlay topmost status
[22:49:09] Opponent Play: id=5, cardId=EX1_258, cardName=Unbound Elemental, turn=5
[22:49:13] UpdateOverlay: Refreshed overlay topmost status
[22:49:26] Player PlayToGraveyard: id=43, cardId=LOE_079, cardName=Elise Starseeker, turn=5
[22:49:26] GameEventHandler: Trying to detect ranks... (tries=9, overlaytoggles=0)
[22:49:26] Overlay: No ranks should be covered by any decks.
[22:49:26] GameEventHandler: --- Player turn 6 ---
[22:49:26] Player Draw: id=37, cardId=EX1_606, cardName=Shield Block, turn=5
[22:49:27] GameEventHandler: No ranks were detected.
[22:49:44] Opponent PlayToGraveyard: id=24, cardId=AT_052, cardName=Totem Golem, turn=5
[22:49:44] Player PlayToGraveyard: id=50, cardId=CS2_106, cardName=Fiery War Axe, turn=5
[22:49:45] Player Play: id=56, cardId=FP1_012, cardName=Sludge Belcher, turn=5
[22:49:46] GameEventHandler: Trying to detect ranks... (tries=10, overlaytoggles=0)
[22:49:46] Overlay: No ranks should be covered by any decks.
[22:49:46] GameEventHandler: --- Opponent turn 6 ---
[22:49:46] Opponent Draw: id=22, cardId=, cardName=, turn=6
[22:49:47] GameEventHandler: No ranks were detected.
[22:50:07] Opponent Play: id=25, cardId=GVG_038, cardName=Crackle, turn=6
[22:50:09] TagChange: WARNING - unhandled zone change (id=72): CREATED -> SETASIDE
[22:50:09] Opponent CreateInPlay: id=72, cardId=EX1_258e, cardName=Overloading, turn=6, mark=Created, created=true
[22:50:12] Opponent PlayToGraveyard: id=25, cardId=GVG_038, cardName=Crackle, turn=6
[22:50:21] Opponent Play: id=23, cardId=EX1_238, cardName=Lightning Bolt, turn=6, mark=Mulliganed
[22:50:26] Opponent PlayToGraveyard: id=23, cardId=EX1_238, cardName=Lightning Bolt, turn=6, mark=Mulliganed
[22:50:26] Opponent Play: id=32, cardId=BRM_011, cardName=Lava Shock, turn=6
[22:50:29] Opponent PlayToGraveyard: id=32, cardId=BRM_011, cardName=Lava Shock, turn=6
[22:50:29] Player PlayToGraveyard: id=56, cardId=FP1_012, cardName=Sludge Belcher, turn=6
[22:50:29] Player CreateInPlay: id=73, cardId=FP1_012t, cardName=Slime, turn=6, mark=Created, created=true
[22:50:32] Player PlayToGraveyard: id=73, cardId=FP1_012t, cardName=Slime, turn=6, mark=Created, created=true
[22:50:34] GameEventHandler: Trying to detect ranks... (tries=11, overlaytoggles=0)
[22:50:34] Overlay: No ranks should be covered by any decks.
[22:50:34] GameEventHandler: --- Player turn 7 ---
[22:50:34] Player Draw: id=53, cardId=FP1_021, cardName=Death's Bite, turn=6
[22:50:34] GameEventHandler: No ranks were detected.
[22:51:01] Player Play: id=37, cardId=EX1_606, cardName=Shield Block, turn=6
[22:51:01] Player Draw: id=47, cardId=EX1_603, cardName=Cruel Taskmaster, turn=6
[22:51:04] Player PlayToGraveyard: id=37, cardId=EX1_606, cardName=Shield Block, turn=6
[22:51:05] Player Play: id=39, cardId=EX1_606, cardName=Shield Block, turn=6, mark=Mulliganed
[22:51:05] Player Draw: id=61, cardId=FP1_012, cardName=Sludge Belcher, turn=6
[22:51:08] Player PlayToGraveyard: id=39, cardId=EX1_606, cardName=Shield Block, turn=6, mark=Mulliganed
[22:51:08] GameEventHandler: Trying to detect ranks... (tries=12, overlaytoggles=0)
[22:51:08] Overlay: No ranks should be covered by any decks.
[22:51:08] GameEventHandler: --- Opponent turn 7 ---
[22:51:08] Opponent Draw: id=29, cardId=, cardName=, turn=7
[22:51:08] GameEventHandler: No ranks were detected.
[22:51:18] Opponent Play: id=29, cardId=EX1_567, cardName=Doomhammer, turn=7
[22:51:34] Opponent Play: id=22, cardId=CS2_045, cardName=Rockbiter Weapon, turn=7
[22:51:34] TagChange: WARNING - unhandled zone change (id=74): CREATED -> SETASIDE
[22:51:34] Opponent CreateInPlay: id=74, cardId=CS2_045e, cardName=Rockbiter Weapon, turn=7, mark=Created, created=true
[22:51:37] Opponent PlayToGraveyard: id=22, cardId=CS2_045, cardName=Rockbiter Weapon, turn=7
[22:51:45] Opponent PlayToGraveyard: id=74, cardId=CS2_045e, cardName=Rockbiter Weapon, turn=7, mark=Created, created=true
[22:51:45] GameEventHandler: Trying to detect ranks... (tries=13, overlaytoggles=0)
[22:51:45] Overlay: No ranks should be covered by any decks.
[22:51:45] GameEventHandler: --- Player turn 8 ---
[22:51:45] Player Draw: id=60, cardId=CS2_108, cardName=Execute, turn=7
[22:51:46] GameEventHandler: No ranks were detected.
[22:52:23] Player Play: id=61, cardId=FP1_012, cardName=Sludge Belcher, turn=7
[22:52:28] Player Play: id=60, cardId=CS2_108, cardName=Execute, turn=7
[22:52:29] Player PlayToGraveyard: id=60, cardId=CS2_108, cardName=Execute, turn=7
[22:52:29] Opponent PlayToGraveyard: id=33, cardId=AT_052, cardName=Totem Golem, turn=7, mark=Mulliganed
[22:52:30] GameEventHandler: Trying to detect ranks... (tries=14, overlaytoggles=0)
[22:52:30] Overlay: No ranks should be covered by any decks.
[22:52:30] GameEventHandler: --- Opponent turn 8 ---
[22:52:30] Opponent Draw: id=17, cardId=, cardName=, turn=8
[22:52:30] GameEventHandler: No ranks were detected.
[22:52:38] Opponent Play: id=12, cardId=AT_087, cardName=Argent Horserider, turn=8
[22:52:47] Player PlayToGraveyard: id=61, cardId=FP1_012, cardName=Sludge Belcher, turn=8
[22:52:47] Player CreateInPlay: id=75, cardId=FP1_012t, cardName=Slime, turn=8, mark=Created, created=true
[22:52:51] Player PlayToGraveyard: id=75, cardId=FP1_012t, cardName=Slime, turn=8, mark=Created, created=true
[22:52:51] GameEventHandler: --- Game was lost! ---
[22:52:51] GameEventHandler: Trying to detect ranks... (tries=15, overlaytoggles=0)
[22:52:51] Overlay: No ranks should be covered by any decks.
[22:52:51] HandleGameEnd: Game ended...
[22:52:51] Gamestats: Current Game ended after 8 turns
[22:52:51] HandleGameEnd: Assigned current game to deck: elise
[22:52:51] HandleGameEnd: Waiting for game mode detection...
[22:52:51] GameModeDetection: Detected gamemode, set CurrentGameStats.GameMode=Casual
[22:52:51] HandleGameEnd: Detected game mode, continuing.
[22:52:51] HandleGameEnd: Waiting for game mode to be saved to game...
[22:52:51] HandleGameEnd: Game mode was saved, continuing.
[22:52:51] HearthStatsManager: trying to upload match: Loss vs Shaman, 17.12.2015 22:46:44
[22:52:51] HearthStatsManager: background process indicator ON
[22:52:51] HearthStatsAPI: uploading match: Loss vs Shaman, 17.12.2015 22:46:44
[22:52:51] GameEventHandler: No ranks were detected.
[22:52:51] HearthStatsAPI: assigned id to match: 57131940
[22:52:52] HearthStatsManager: background process indicator OFF
[22:52:52] HearthStatsManager: success uploading match Loss vs Shaman, 17.12.2015 22:46:44
[22:52:59] HandleInMenu: Game is now in menu.
[22:52:59] HandleInMenu: Waiting for game mode detection...
[22:52:59] HandleInMenu: Detected game mode, continuing.
[22:52:59] GameEventHandler: Gamemode Casual is not supposed to be saved. Removed game from elise (Warrior).
[22:53:19] UpdateOverlay: Refreshed overlay topmost status

**Comment by Epix37** [comment] 2015-12-17 21:54
@ginko147 could you post a screenshot of the hs + hdt overlay in a ranked game?

**Comment by ginko147** [comment] 2015-12-17 22:15
Here you go:

![untitled](https://cloud.githubusercontent.com/assets/13107439/11883555/7c4f0e8c-a51c-11e5-8fa1-70c3373b340e.png)

**Comment by DerfelKadarn** [comment] 2015-12-17 22:17
Same problem here. I'm running HDT on a Win10 VM on a Mac using Parallels.

**Comment by tknights2015** [comment] 2015-12-17 22:32
My ranked games are also being recorded as casual and I have auto adjustment or screen dimming software.

**Comment by MyopicCat** [comment] 2015-12-17 22:41
I haven't tried ranked in the new version yet, but I just played 23 arena games. Only 13 of those games were recorded at all, and none of them were identified as arena games. No dimming or similar software in use.

**Comment by DerfelKadarn** [comment] 2015-12-17 23:12
I almost never had Rank or Game mode issues in the previous version. I wonder if there is an option (you mentioned one in a previous post) to re-enable the log-based detection. I'm kind of stuck between two versions 0.13.3 didn't handle Entomb properly so reverting will probably be as annoying.

**Comment by tknights2015** [comment] 2015-12-17 23:38
Log files repeat over and over. 
[4:35:55 PM] Overlay: No ranks should be covered by any decks.
![hdt](https://cloud.githubusercontent.com/assets/16232528/11885177/9ecbf2f8-a4dc-11e5-86f2-2083da7952d4.JPG)

**Comment by tknights2015** [comment] 2015-12-18 04:03
Just a footnote. I reverted back to version v0.13.3 And games are recorded correctly as ranked

**Comment by Epix37** [comment] 2015-12-18 08:31
@MyopicCat screen dimming should not have any effect on areng games, only ranked vs casual. Can you post hdt logs of those games?

@ginko147 Just had another look at the log you posted, the games not being recorded stemms from the fact that it does not register them as casual and you have recording casual games disabled. So if you enable that they at least will be recorded (in the wrong mode, but still).

**Comment by Epix37** [comment] 2015-12-18 08:57
Made some adjustments.
Can you guys give this version a shot? https://github.com/Epix37/HDT-Test/releases/tag/v0.13.7_PRE1

**Comment by bstuparu** [comment] 2015-12-18 09:32
Still detecting as casual with the new version, log is 
[here](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/66413/hdt_log.txt)

**Comment by Epix37** [comment] 2015-12-18 09:34
Can you try changing the resolutions and/or windowed/fullscreen?

**Comment by bstuparu** [comment] 2015-12-18 09:46
Changing the resolution did not work from 1920x1080 to 1600x900. Still detecting casual. Log 
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/66427/hdt_log.txt)

**Comment by Epix37** [comment] 2015-12-18 09:56
Could you post a screenshot of a ranked game via the HDT build-in functionality? `options > tracker > hotkeys` and set a hotkey for screenshot.

**Comment by bstuparu** [comment] 2015-12-18 10:00
No fullscreen still no result log 
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/66439/hdt_log.txt)
Will start game and screenshot it right away

**Comment by bstuparu** [comment] 2015-12-18 10:03
HDT seems to freeze when I try to screenshot. Key shortcut is Alt-F12

**Comment by Epix37** [comment] 2015-12-18 10:08
No crash, it just freezes?

At least we now most likely know where the issue is. Ranked detection uses the same sort of screenshot for analysis. I'll upload a build in 2 hours or so with some more explicit logging that should help figure out what exactly is causing it.

**Comment by bstuparu** [comment] 2015-12-18 10:10
Great, good job

**Comment by bstuparu** [comment] 2015-12-18 10:13
My apologies, it seems to prompt for where to save when focusing back to the application. The image is 
![this](https://cloud.githubusercontent.com/assets/16348456/11894556/aab015c8-a580-11e5-9b9f-2c967daf8626.png)

**Comment by Epix37** [comment] 2015-12-18 10:22
Huh.. running that screenshot through the rank detection works perfectly fine for me. 

There is one minor difference between the two screenshot implementations, let's hope that's the bug.

Try this one: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.7_PRE2

**Comment by bstuparu** [comment] 2015-12-18 10:46
PRE2 fixes the bug

**Comment by Epix37** [comment] 2015-12-18 11:32
Awesome!

**Comment by riQQ** [comment] 2015-12-18 13:05
Works for me.

**Comment by ginko147** [comment] 2015-12-18 13:17
Im going to login right now on my PC and I will let you know if its working with the PRE17 build.

**Comment by MyopicCat** [comment] 2015-12-18 14:01
Had time to test a quick arena run with PRE2. Went 6-3, all games recorded correctly. Seems OK now!

**Comment by Epix37** [comment] 2015-12-18 14:52
Released v0.13.7. Should be fixed!

**Closed by Epix37** 2015-12-18 14:52 UTC
Labels: bug
