### ISSUE TITLE
Crash on Startup (only while hearthstone is running)

### ISSUE THREAD

**Issue by Valodec** [Epix37/Hearthstone-Deck-Tracker#795] opened 2015-03-15 12:05 UTC
what i did in firstplace
1. i created a new deck and importet it.
2. started a public match with a different deck.
3. crash immediately at first carddraw (after the starting hand selection)
4. since then decktracker crash on startup
5. does not crash if hearthstone is NOT running

what i tried already
1. restart HS
2. restart PC
3. delete Decktracker Folder and copied("installed") fresh from up to date zip

what i didn't try
1. anything within appdata folders
2. format C :P 
3. throw PC out of my window (wouldn't fix it cuz pc room is in the basement)

Crash report from startup crash:

########## 15.03.2015 12:51:48 ##########
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Hearthstone_Deck_Tracker.GameEventHandler.SetPlayerHero(String hero)
   bei Hearthstone_Deck_Tracker.GameEventHandler.Hearthstone_Deck_Tracker.IGameHandler.SetPlayerHero(String hero)
   bei Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   bei Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Crash report from initial crash:

########## 15.03.2015 12:29:48 ##########
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Hearthstone_Deck_Tracker.GameEventHandler.SetPlayerHero(String hero)
   bei Hearthstone_Deck_Tracker.GameEventHandler.Hearthstone_Deck_Tracker.IGameHandler.SetPlayerHero(String hero)
   bei Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   bei Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[10:04:34] Load: Copied log.config to C:\Users\Valodec\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[10:04:34] Game: set CurrentGameMode to None
[10:04:35] Game: Done loading card database (enUS)
[10:04:35] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[10:04:35] OpponentSecrets: Cleared secrets
[10:04:35] Tracker: Set player itemsource as PlayerDeck
[10:04:35] Tracker: Switched to deck: murlocK
[10:04:35] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[10:04:35] OpponentSecrets: Cleared secrets
[10:04:36] Helper: Checking for updates...
[10:04:36] Helper: Current version: 0.9.7.0
[10:04:36] BackupManager: Running BackupManager
[10:04:36] BackupManager: Creating backup for today
[10:04:37] Helper: Latest version: 0.9.7.0
[10:30:12] Helper: Checking for updates...
[10:30:12] Helper: Current version: 0.9.7.0
[10:30:12] Helper: Latest version: 0.9.7.0
[10:30:23] LogReader: Current region: EU
[10:31:46] UpdateOverlay: Refreshed overlay topmost status
[10:33:58] UpdateOverlay: Refreshed overlay topmost status
....
shortened imo unimportant information
....
[12:22:52] Tracker: Switched to deck: Miracle Malygos
[12:22:52] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:22:52] OpponentSecrets: Cleared secrets
[12:22:52] GameEventHandler: Reset constructed importing
[12:22:59] DeckExporter: Exporting deckname:Miracle Malygos, class:Rogue, cards:30
[12:23:00] UpdateOverlay: Refreshed overlay topmost status
[12:23:00] DeckExporter: Waiting for 0 seconds before starting the export process
[12:23:00] DeckExporter: Clearing deck...
[12:23:04] DeckExporter: Setting deck name...
[12:23:05] DeckExporter: Clicking "all" crystal...
[12:23:05] DeckExporter: Creating deck...
[12:23:16] DeckExporter: Done creating deck.
[12:23:26] Tracker: Set player itemsource as PlayerDeck
[12:23:26] Tracker: Switched to deck: Modified Miracle Malygos
[12:23:26] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:23:26] OpponentSecrets: Cleared secrets
[12:23:26] GameEventHandler: Reset constructed importing
[12:23:28] Tracker: Set player itemsource as PlayerDeck
[12:23:28] Tracker: Switched to deck: S10 Tempo
[12:23:28] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:23:28] OpponentSecrets: Cleared secrets
[12:23:29] GameEventHandler: Reset constructed importing
[12:23:43] Tracker: Set player itemsource as PlayerDeck
[12:23:43] Tracker: Switched to deck: Your Power is Mine
[12:23:43] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:23:43] OpponentSecrets: Cleared secrets
[12:23:44] GameEventHandler: Reset constructed importing
[12:23:44] Tracker: Set player itemsource as PlayerDeck
[12:23:44] Tracker: Switched to deck: Trump's What's Yours Is Mine Priest
[12:23:44] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:23:44] OpponentSecrets: Cleared secrets
[12:23:44] GameEventHandler: Reset constructed importing
[12:23:51] Tracker: Set player itemsource as PlayerDeck
[12:23:51] Tracker: Switched to deck: Control
[12:23:51] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:23:51] OpponentSecrets: Cleared secrets
[12:23:51] GameEventHandler: Reset constructed importing
[12:23:59] Tracker: Set player itemsource as PlayerDeck
[12:23:59] Tracker: Switched to deck: Aggromage
[12:23:59] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:23:59] OpponentSecrets: Cleared secrets
[12:23:59] GameEventHandler: Reset constructed importing
[12:24:24] Tracker: Set player itemsource as PlayerDeck
[12:24:24] Tracker: Switched to deck: ArenaValue Warlock (2235)
[12:24:24] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:24:24] OpponentSecrets: Cleared secrets
[12:24:24] GameEventHandler: Reset constructed importing
[12:24:41] Tracker: set player item source to PlayerDrawn
[12:24:41] Tracker: Deselected deck
[12:24:41] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:24:41] OpponentSecrets: Cleared secrets
[12:24:41] Edit: Moved deckstats for deck Modified Miracle Malygos to default stats
[12:24:41] Edit: Removed deckstats from deck: Modified Miracle Malygos
[12:24:41] HearthStatsManager: trying to delete deck Modified Miracle Malygos (Rogue)
[12:24:41] HearthStatsManager: background process indicator ON
[12:24:41] HearthStatsAPI: deleting deck: Modified Miracle Malygos (Rogue)
[12:24:41] Edit: Deleted deck: Modified Miracle Malygos
[12:24:41] Edit: Moved deckstats for deck S10 Tempo to default stats
[12:24:41] Edit: Removed deckstats from deck: S10 Tempo
[12:24:41] HearthStatsManager: trying to delete deck S10 Tempo (Rogue)
[12:24:41] HearthStatsAPI: deleting deck: S10 Tempo (Rogue)
[12:24:41] Edit: Deleted deck: S10 Tempo
[12:24:41] Edit: Moved deckstats for deck Your Power is Mine to default stats
[12:24:41] Edit: Removed deckstats from deck: Your Power is Mine
[12:24:41] HearthStatsManager: trying to delete deck Your Power is Mine (Priest)
[12:24:41] HearthStatsAPI: deleting deck: Your Power is Mine (Priest)
[12:24:41] Edit: Deleted deck: Your Power is Mine
[12:24:41] Edit: Moved deckstats for deck Trump's What's Yours Is Mine Priest to default stats
[12:24:41] Edit: Removed deckstats from deck: Trump's What's Yours Is Mine Priest
[12:24:41] HearthStatsManager: trying to delete deck Trump's What's Yours Is Mine Priest (Priest)
[12:24:41] HearthStatsAPI: deleting deck: Trump's What's Yours Is Mine Priest (Priest)
[12:24:41] Edit: Deleted deck: Trump's What's Yours Is Mine Priest
[12:24:41] Edit: Removed deckstats from deck: Control
[12:24:41] HearthStatsManager: trying to delete deck Control (Priest)
[12:24:41] HearthStatsAPI: deleting deck: Control (Priest)
[12:24:41] Edit: Deleted deck: Control
[12:24:41] Edit: Moved deckstats for deck Aggromage to default stats
[12:24:41] Edit: Removed deckstats from deck: Aggromage
[12:24:41] HearthStatsManager: trying to delete deck Aggromage (Mage)
[12:24:41] HearthStatsAPI: deleting deck: Aggromage (Mage)
[12:24:41] Edit: Deleted deck: Aggromage
[12:24:41] Edit: Moved deckstats for deck ArenaValue Warlock (2235) to default stats
[12:24:41] Edit: Removed deckstats from deck: ArenaValue Warlock (2235)
[12:24:41] Edit: Deleted deck: ArenaValue Warlock (2235)
[12:24:41] GameEventHandler: Reset constructed importing
[12:24:45] HearthStatsAPI: deleted deck
[12:24:45] HearthStatsManager: success deleting deck Modified Miracle Malygos (Rogue)
[12:24:45] HearthStatsAPI: deleted deck
[12:24:45] HearthStatsManager: success deleting deck S10 Tempo (Rogue)
[12:24:46] HearthStatsAPI: deleted deck
[12:24:46] HearthStatsManager: success deleting deck Your Power is Mine (Priest)
[12:24:46] HearthStatsManager: background process indicator OFF
[12:24:46] HearthStatsAPI: deleted deck
[12:24:46] HearthStatsManager: success deleting deck Trump's What's Yours Is Mine Priest (Priest)
[12:24:47] HearthStatsAPI: deleted deck
[12:24:47] HearthStatsManager: success deleting deck Control (Priest)
[12:24:47] HearthStatsAPI: deleted deck
[12:24:47] HearthStatsManager: success deleting deck Aggromage (Mage)
[12:24:59] UpdateOverlay: Refreshed overlay topmost status
[12:25:56] UpdateOverlay: Refreshed overlay topmost status
[12:26:07] Tracker: set player item source to PlayerDrawn
[12:26:07] Tracker: Deselected deck
[12:26:07] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:26:07] OpponentSecrets: Cleared secrets
[12:26:08] GameEventHandler: Reset constructed importing
[12:26:16] SaveDeck: Saved Decks
[12:26:16] SaveDeck: auto uploading new/edited deck
[12:26:16] HearthStatsManager: trying to upload deck Legendary Control (Paladin)
[12:26:16] HearthStatsManager: background process indicator ON
[12:26:16] HearthStatsAPI: uploading deck: Legendary Control (Paladin)
[12:26:17] Tracker: Set player itemsource as PlayerDeck
[12:26:17] Tracker: Switched to deck: Legendary Control
[12:26:17] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:26:17] OpponentSecrets: Cleared secrets
[12:26:17] GameEventHandler: Reset constructed importing
[12:26:20] HearthStatsAPI: HearthStatsId assigned to deck: 334950
[12:26:20] HearthStatsAPI: HearthStatsDeckVersionId assigned to deck: 117245
[12:26:20] HearthStatsManager: background process indicator OFF
[12:26:20] HearthStatsManager: success uploading deck Legendary Control (Paladin)
[12:26:35] DeckExporter: Exporting deckname:Legendary Control, class:Paladin, cards:30
[12:26:35] UpdateOverlay: Refreshed overlay topmost status
[12:26:36] DeckExporter: Waiting for 0 seconds before starting the export process
[12:26:36] DeckExporter: Clearing deck...
[12:26:40] DeckExporter: Setting deck name...
[12:26:40] DeckExporter: Clicking "all" crystal...
[12:26:41] DeckExporter: Creating deck...
[12:26:52] DeckExporter: Done creating deck.
[12:26:56] UpdateOverlay: Refreshed overlay topmost status
[12:29:18] Game: set CurrentGameMode to Casual
[12:29:47] GameEventHandler: Game start
[12:29:47] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:29:47] OpponentSecrets: Cleared secrets
[12:29:47] Game: set CurrentGameMode to None
[12:29:47] GameEventHandler: Opponent-turn (1)
[12:29:47] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[12:29:47] Hearthstone: Set card 0 to age 0
[12:29:47] Hearthstone: Opponent Hand after draw: 0K,  ,  ,  ,0C,  ,  ,  ,  ,  
[12:29:47] GameStats: New play: OpponentDraw (, turn: 0)
[12:29:47] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[12:29:47] Hearthstone: Set card 1 to age 0
[12:29:47] Hearthstone: Opponent Hand after draw: 0K,0K,  ,  ,0C,  ,  ,  ,  ,  
[12:29:47] GameStats: New play: OpponentDraw (, turn: 0)
[12:29:47] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[12:29:47] Hearthstone: Set card 2 to age 0
[12:29:47] Hearthstone: Opponent Hand after draw: 0K,0K,0K,  ,0C,  ,  ,  ,  ,  
[12:29:47] GameStats: New play: OpponentDraw (, turn: 0)
[12:29:47] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[12:29:47] Hearthstone: Set card 3 to age 0
[12:29:47] Hearthstone: Opponent Hand after draw: 0K,0K,0K,0K,0C,  ,  ,  ,  ,  
[12:29:47] GameStats: New play: OpponentDraw (, turn: 0)
[12:29:47] GameEventHandler: PlayerDraw (id:EX1_062 turn:0 from:-1)
[12:29:47] GameEventHandler: Found incorrect deck on PlayerDraw
[12:29:47] GameStats: New play: PlayerDraw (EX1_062, turn: 0)
[12:29:47] GameEventHandler: PlayerDraw (id:CS2_173 turn:0 from:-1)
[12:29:47] GameStats: New play: PlayerDraw (CS2_173, turn: 0)
[12:29:47] GameEventHandler: PlayerDraw (id:FP1_030 turn:0 from:-1)
[12:29:47] GameStats: New play: PlayerDraw (FP1_030, turn: 0)
[12:29:47] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[12:29:47] GameStats: New play: OpponentDraw (, turn: 0)
[12:29:47] IncorrectDeckMessage: 0 possible decks found.
[12:29:48] GameEventHandler: Playing against Druid

**Comment by Epix37** [comment] 2015-03-15 12:37
Could you email me your `output_log.txt` found in `Hearthstone/Hearthstone_Data` when this happens? (epikz37@gmail.com)

**Comment by Epix37** [comment] 2015-03-15 13:44
I had no success reproducing this. Neither with the output_log, nor the PlayerDecks and config used here. 

*Nor* can I find what's supposed to cause the NullReferenceException in SetPlayerHero. Am I blind?

**Comment by Valodec** [comment] 2015-03-15 14:06
thanks for the help and nice conversation via email!

**Comment by dvide** [comment] 2015-03-15 14:08
https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/38a9a1108836012d433b8edadea295115a5ed215/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L344

Think it might be this I added. I guess it should say `if(deck != null && deck.Archived)`

**Comment by Epix37** [comment] 2015-03-15 14:08
Let's leave this open since it's actually still not fixed :).

And on that note, the workaround we found seems to be disabling "auto deck selection".

**Comment by Epix37** [comment] 2015-03-15 14:10
@dvide I'm not so sure. If that was the case, the log (above) would show 
```
Logger.WriteLine("Found more than 1 deck to switch to - last played: " + lastDeck.Name, "HandleGameStart");
```

**Comment by dvide** [comment] 2015-03-15 14:10
Hm that's true :)

**Comment by Epix37** [comment] 2015-03-15 14:13
The only possible null exception I see is `DeckList.Instance.Decks` containing `null`
https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/38a9a1108836012d433b8edadea295115a5ed215/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L327

Could that be?

**Comment by dvide** [comment] 2015-03-15 14:50
I just tried adding a null deck to `DeckList.Instance.Decks` and then calling `DeckList.Save()`. The null deck isn't saved to `PlayerDecks.xml` and so it's not there when you reload either.

**Comment by Epix37** [comment] 2015-03-21 20:18
I still have no idea what's causing this. Just try-catching will have to do for now.

**Comment by fmoraes74** [comment] 2015-03-23 15:22
Is this now fixed with the recent code change? I ran into this crash today. I had a Mech Rogue deck selected but was playing a Mech Mage.

I have the crash logs if you want to see them.

**Closed** 2015-04-01 05:23 UTC
Labels: bug, help wanted
