### ISSUE TITLE
Auto-deck selector issue

### ISSUE THREAD

**Issue by Pand3m0nia** [Epix37/Hearthstone-Deck-Tracker#677] opened 2015-02-11 18:36 UTC
With the new version of Hearthstone Deck Tracker if I play a game with a deck, and then decide to swap to a deck of a different Hero, the "Wrong Deck detected" message pops up (which is fine) and the possible options appear, clicking any of them doesn't seem to get rid of the dialog, and the deck list of the correct deck does appear, but the title of the previous deck will remain, e.g. I played Shaman after playing Paladin Midrange, and the title showed Paladin Midrange while the list was the correct Shaman one. After I click the "X' on the dialog I get the message that auto deck-select has been disabled and I need to re-enable it.

**Comment by Calioe** [comment] 2015-02-11 22:44
the autodeck doesn t work neither for me anymore....!!

**Comment by WaxPaper** [comment] 2015-02-12 09:59
Same here... I actually thought this was the reason for one of the last hotfixes, but now that I'm re-reading through the release notes I see that this issue wasn't specifically mentioned.

Would a snippet of the log help you diagnose the issue at all?

**Comment by Epix37** [comment] 2015-02-12 10:13
Didn't get around to this yet but it's on my todo list for the next update.

**Comment by Calioe** [comment] 2015-02-14 22:24
In fact even if I manually select after I have issues to recognize the right deck after the issue with autodeck

**Comment by WaxPaper** [comment] 2015-02-24 08:09
Same here, Calioe... Anyone know of a workaround that helps until the next update gets released? It's not a problem with a parameter in the config file, for example, is it?

Epix37, have you ever considered providing access to "nightly" (or however often you update) builds of the program? I know that we could always download the source here and compile it ourselves, but I personally don't have any programming knowledge and I don't have any software tools that would compile either... If it's a pretty easy thing to do, that's another story; I'll do some Googling and figure out how...

But otherwise, it would be cool to have access to development builds with the newest updates baked-in, if you have the time and willingness to compile some of your more substantial milestone updates, before they're ready for release...

**Comment by rdellaripa** [comment] 2015-02-27 14:13
I, too, am having this issue, where if I have Auto Deck Selection enabled, and it tries to figure out a deck I've switched to, it constantly pops up the dialogue for which deck it could be. I think this started around the release of .9, or it could be that I have lots of decks and it's getting lost in them. If I can help figure it out, let me know.

**Comment by Epix37** [comment] 2015-03-01 09:16
I think I found the issue. Do you guys have `include obtained cards` enabled in `options > decks´?

**Comment by Pand3m0nia** [comment] 2015-03-01 09:34
I have tried with it both enabled and disabled with no success, still get the same dialog box appearing and can't select a deck.

**Comment by Epix37** [comment] 2015-03-01 09:35
Could you upload the hdt_log.txt found in HearthstoneDeckTracker/Logs after that happened?  (www.pastebin.com)

**Comment by Epix37** [comment] 2015-03-01 10:56
@WaxPaper I do release tests build (usually in issue somewhere) every now and then when I feel it's necessary. Maybe I'll do that a bit more regular in the future. 

This being one of the cases where feedback might be helpful, please check if the current build still has the same issues (I can't seem to reproduce it): https://github.com/Epix37/HDT-Test/releases

**Comment by WaxPaper** [comment] 2015-03-02 08:28
@Epix37 I don't think I've ever had the "include obtained cards" option enabled, although when the bug first started happening it the latest release, I allowed the app to create a new, fresh ini config file just in case mine was corrupted or something... That didn't fix the problem, although I can't be sure I didn't have that option enabled previously.

Regardless if I did, it wasn't working back then, so I'm not sure... Are you saying that enabling this option should fix the auto-selection bug? I'll try it out and get back to you here. I'll also give that newer version you linked a try; the pre-release 0.9.6 one...

Thanks...

**Comment by Epix37** [comment] 2015-03-02 08:53
There were two issues with the deck selection dialog, the other one was related to "include obtained", this one seems not to be. Enabling the option should not fix it, no. 

If the prerelease still has the issue, please upload the hdt_log.txt for me (see above).

**Comment by Pand3m0nia** [comment] 2015-03-02 09:46
@Epix37,

So I played a game with my Shaman deck, with the Auto-select option checked and nothing happened. Only when I changed to an incorrect deck (Druid Midrange) did the "Wrong Deck Selected" Window popup appear.

Here is the pastebin: http://pastebin.com/7svwBxAn

I'm sorry I didn't know which parts are relevant or not, I just copied the logs from when I first tried to select the wrong deck.

**Comment by Epix37** [comment] 2015-03-02 09:55
@Pand3m0nia With what version is that?

**Comment by WaxPaper** [comment] 2015-03-02 09:56
@Epix37 So I tried enabling that option and as you eluded to about it being a different issue, it didn't help. I downloaded that new pre-release and tried using it (although I just let it use my current config instead of making a new one) and the bug seems to persist...

http://pastebin.com/vyMAvh8i

Here's a pastebin of the log; I tried to make it easier for you by snipping the relevant part. This log begins right as I'm starting a Casual game, which was followed by an Arena game (obviously using a different deck). One thing I noticed in the log is that the auto-selector did seem to find the correct deck even though it wasn't previously selected (the Paladin deck, after playing an Arena as Mage and having that selected), but for some reason the client is still recognizing it as incorrect.

From there on, it's the usual bug, with the auto-deck selection menu being presented, although it won't "initialize" on a deck even if you manually select it. It'll keep looping back to the "incorrect deck" error until you either choose the "no deck" option or close the dialog menu, which will force the client to use no deck and turn off auto-detection.

What else would help you debug this issue? Would log level 1 (instead of 0, like this one) help? Would a video screengrab of the problem happening help in any way? Thanks man...

**Comment by Epix37** [comment] 2015-03-02 10:08
> It'll keep looping back to the "incorrect deck" error until you either choose the "no deck" option or close the dialog menu, which will force the client to use no deck and turn off auto-detection.

Did you cut that out by any chance? I can't seem to find that part in the log. 

Could you send your "PlayerDecks.xml" and "config.xml" files ("%AppData%/HearthstoneDeckTracker") to epikz37@gmail.com? Maybe that helps finding the issue.

**Comment by WaxPaper** [comment] 2015-03-02 10:16
@Epix37 I was describing what WILL happen if you do that, instead of just closing it the first time, which is what I did in that log... Actually I can't remember if I closed the dialog via the "X" in the corner or hit the "Use No Deck" button in that specific log; if it makes a difference, lemme know.

Also, here's another log at the "1" level, just in case it helps. Again, the log begins before I enter a casual game, with a different deck selected than the one I'm using: http://pastebin.com/T8qxYtCg

And here's the Config and PlayerDecks files you asked for, in a zip: http://www15.zippyshare.com/v/WWv595I1/file.html

**Comment by Epix37** [comment] 2015-03-02 10:22
This looks promising, I'm able to reproduce it.

**Comment by Pand3m0nia** [comment] 2015-03-02 10:26
@Epix37, 0.95, I also downloaded the pre-release, issue still seemed to persist. Sorry I can't be more help.

**Comment by WaxPaper** [comment] 2015-03-02 10:41
@Epix37  Could this be related to the "Advanced Window Search" option? The fact that you were able to reproduce it using my configs made me wonder about my settings, so I started looking around in there to see if there were some things I could disable...

It's not enough to make a call either way yet, although after I disabled that option a little while ago, I haven't seen the bug for the past few games... Don't know if it's coincidence or not, yet...

**Comment by Epix37** [comment] 2015-03-02 11:09
Alright, I'm fairly certain I got it fixed. Please try the latest build: https://github.com/Epix37/HDT-Test/releases/tag/v0.9.6_PRE2

**Comment by Pand3m0nia** [comment] 2015-03-02 11:18
@Epix37, downloaded the new pre-release, the issue seems to be fixed, if I select the the incorrect deck the dialog doesn't even appear anymore, it just automatically switches to the correct deck now :)

Thanks for fixing it!

**Comment by WaxPaper** [comment] 2015-03-02 11:20
@Epix37 Pre2 seems to be working so far, after the first couple games now... I'll let you know if that changes and the bug reemerges. Fingers crossed, though! Thanks for all your work, man...

**Comment by Epix37** [comment] 2015-03-02 11:20
Great! :) Thanks for the help guys!

**Closed** 2015-03-02 11:40 UTC
Labels: bug, next update

**Comment by Pand3m0nia** [comment] 2015-03-02 13:13
Hi again,

The Auto deck selector doesn't seem to work if I just start a game with no deck selected and the Auto deck selector option checked. Nothing happens, no error message appears. If I select a wrong deck it will select the correct deck.

**Comment by Epix37** [comment] 2015-03-02 13:20
That it working as intended

**Comment by Pand3m0nia** [comment] 2015-03-02 13:21
@Epix37 , ah ok, thanks.
