### ISSUE TITLE
v0.13.14 Golden Monky

### ISSUE THREAD

**Issue by tetsuzi** [Epix37/Hearthstone-Deck-Tracker#2185] opened 2016-03-07 04:10 UTC
I English do not speak well.

I Play Golden Monkey.
I get an warning in the next draw.
This is happening from v0.13.14.

![2016-03-07](https://cloud.githubusercontent.com/assets/17695538/13560704/c2129a6e-e465-11e5-9272-41f600c6b5d6.png)

http://pastebin.com/JH4B1up1

**Comment by zaheer12a** [comment] 2016-03-08 00:32
Had the same issue. The Deck tracker completely stopped functioning afterwards. No games are being tracked right now for some reason.

**Comment by Epix37** [comment] 2016-03-08 11:22
Working on fixing this for the next release.

@zaheer12a If the problem is permanent give [this](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config) a shot.

**Comment by Epix37** [comment] 2016-03-08 15:49
Fixed with c9f752f .

**Comment by ShoestringTaz** [comment] 2016-03-11 14:15
I am having the same problem but don't understand the fix as can't find the file the bde416 refers to?

**Comment by Epix37** [comment] 2016-03-11 15:00
Deleted the code comments. Quote andburn:
> @ShoestringTaz this is a reference to the piece of code that fixes the problem. It will be available with the next update to the tracker.

**Comment by Epix37** [comment] 2016-03-15 16:10
Should be fixed with v0.13.16.

**Closed by Epix37** 2016-03-15 16:10 UTC
Labels: bug
