### ISSUE TITLE
Hearthstone suddenly choppy after installing

### ISSUE THREAD

**Issue by Diamades** [Epix37/Hearthstone-Deck-Tracker#1097] opened 2015-06-16 20:45 UTC
Hey! So great addon, I'm really having a good time using it. The only issue is as soon as I installed it, I start to get weird FPS spikes. I used Fraps to test and even though I'm running at locked 60 FPS, whenever *I* do an action, it drops about 30%. No effect when opponent does things, maybe only when it's looking at my logfile or something?

Even weirder, I deleted the HDT, and reinstalled HS and STILL have this issue. Did it permanently modify some file that is causing this? Anyone seen this? 

Edit: In doing some previous searching (on the issues list), I found a couple of people with exactly the same issue as me. Turns out it's the sole presence of a log.config file. My complication now is that I should have no issue whatsoever with it as I'm running a high-end (modern) gaming computer with everything relevant on an SSD. Why does a config file do this? Any suggestions as to a fix?

Thanks!

**Comment by kiyo1** [comment] 2015-06-17 17:07
I've started getting this too, but I'm not sure it's the log.config file? Have you confirmed this? If so, what was the fix?

**Comment by Diamades** [comment] 2015-06-17 17:40
Yes I confirmed that it is the log file. By deleting it and turning off the deck tracker it's fixed. Issue is I want to use the deck tracker without the lag!

**Comment by Talhoo** [comment] 2015-06-18 14:05
I also have this problem, just downloaded this tracker and started lagging. After removing the log file the lag was gone.

I play also on SSD, and the latest i5. My gfx is slightly outdated but I doubt it has anything to do with that. 

Is there any extra info we can give to fix this problem ? Or should we start complaining to blizzard for this ?

**Comment by Diamades** [comment] 2015-06-18 14:07
Good to know that this is a known problem. I'm running a Titan so it's definately not a gfx issue :P Any chance we can get a response from the authour? 

Thanks!

**Comment by Diamades** [comment] 2015-06-18 21:01
I've posted on the official forums, and it turns out many people are having this issue.

http://us.battle.net/hearthstone/en/forum/topic/18122597684
http://us.battle.net/hearthstone/en/forum/topic/18122624001

Hopefully we get an official response.

**Comment by dvide** [comment] 2015-06-18 22:16
I've noticed the same thing after the hearthstone patch. Really jerky every time I play a card etc. Not on an SSD though. They must have done something that affects the performance of the logging output. It's not a supported feature so I doubt Blizzard will do anything about it.

**Comment by Diamades** [comment] 2015-06-18 22:17
That would seriously suck. But yes, something must have changed. Maybe the author of this glorious addon would be able to figure something out? :)

**Comment by Epix37** [comment] 2015-06-22 09:34
@dvide pretty much hit the nail on the head. HDT needs all the logging that is currently enabled to function properly, so I see no way to improve the performance and Blizzard will not "fix" this because the log is not intended to be used period. 

I agree it sucks not there is nothing I can do.

**Comment by Diamades** [comment] 2015-06-22 11:17
Hmm, so Epix are you experiencing the same lag?

**Comment by Epix37** [comment] 2015-06-22 11:21
Did a quick test again, completely smooth for me.

**Comment by Diamades** [comment] 2015-06-22 11:24
Humm, so wouldn't that imply that there is something we can do on our end to fix it (i.e. the affected)? It seems some people have this issue, some don't.

**Comment by Epix37** [comment] 2015-06-22 11:30
I have no idea tbh. If I had the issue myself I might be able to find something, but this way around makes that impossible. 

As far as I know this does happen without HDT running, right? So it's some problem with your hardware/OS. *Maybe* changing hearthstone settings (windowed) has some effect? Maybe it's certain SSD/HDD manufactureres? Encrypeted drives? It's all just guessing :/.

**Comment by Diamades** [comment] 2015-06-22 11:32
Yeah, that's the thing. Even if I uninstall HDT, delete the log file and remake it (with my own settings inside it) it will lag. Not related to HDT at all, it's just the sheer *logging* aspect of Hearthstone. My first guess was some sort of permission thing to that file that was slogging along everytime it tried to read/write to the file. But everything seemed to check out there.

**Comment by irufus** [comment] 2015-06-26 04:29
Has anyone tried to monitor performance using Microsoft's Processor Explorer? I wonder if it's aggressively using its file handler or is there any signs of High Disk I/O.

**Comment by irufus** [comment] 2015-07-08 03:04
@Epix37 
After doing some research I discovered that this is a universal issue with Unity logging. I also notice that no matter what I set log level to in the config files the logging is still extremely verbose. 

As a temporary fix could we just disable logging when someone closes Hearthstone Deck Tracker or add an option to reset logging on application exit?

Also does anyone recognize what method of debugging Blizzard is using or is it possible their using a particular plugin?

**Comment by bdzs** [comment] 2015-07-08 13:44
I can confirm that have the same problem.

Had to disable the log.config file and stopped using the Tracker otherwise the game is not unplayable but... it's just not good.

**Comment by dhoepelman** [comment] 2015-07-26 12:43
This is probably only a problem if you run on a HDD, a SSD should be much better in handling this kind of I/O.

If you don't have an SSD/don't want to install hearthstone on it, you could place only the log there through [a symlink](http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/). A fast USB3 flash drive might work too.

**Comment by Diamades** [comment] 2015-07-26 13:15
Nope, running on an SSD (which is only ~45% full I might add, also purchased 6 months ago).

This is something related to a change blizzard made in the most recent patch. So far there's about 15 people on the forums who have been talking about it, where this only started happening after the patch. What type of change in code could do this/how could it only affect a few people?

**Comment by dvide** [comment] 2015-07-26 19:04
I tried using this [ramdisk software](https://www.softperfect.com/products/ramdisk/), and created a symbolic link for the output log file so that it would write to the virtual disk instead. So theoretically it shouldn't have been writing the log output to disk at all, but keeping it all in RAM instead. It didn't seem to help though. Perhaps a little bit, but it was hard to tell.

If anyone wants to play around with it, I had to set the symlink itself to read only so that Hearthstone didn't delete it and recreate the file (removing the symlink). This worked but only once for each time you run Hearthstone, because then the Battle.net Agent would download something and recreate the file after you close Hearthstone. Kind of annoying but workable enough for testing it out.

**Comment by r3lik** [comment] 2015-08-16 04:34
so no fix eh?

**Comment by slowcom** [comment] 2015-08-23 19:33
I have found the fix!

For some reason Windows Defender is scanning the log output every time the log gets written to.  All you need to do is add an exception in Windows Defender for USERPROFILE%\AppData\Local\Blizzard    and the lag is gone!

**Comment by Epix37** [comment] 2015-08-23 20:04
Doesn't seem to work for everybody apparently (?): https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1274#issuecomment-133868583

**Comment by Bahzur** [comment] 2015-08-24 11:26
Curious thing:
Im on Win 7 and dont have Windows Defender activated because i already use Avira Antivir. So after seing that putting the log into an exceptions seems to help, i just did that in Avira. The log and the Hearthstone process are now in an exception from the lifescanner of Avira and that does seem to work for me! I have no more fps drops when a card is played.

**Comment by xyzXXXok** [comment] 2015-08-24 12:16
well on my system there is only windows defender installed. could it be the windows firewall?

**Comment by MechaLynx** [comment] 2015-08-24 12:18
Wouldn't the Resource Monitor from the Task Manager on Win7/Vista show whether there is a lot of activity on the log file? I don't have this problem so I can't test it, but it might provide some insight and clear this up.

**Comment by xyzXXXok** [comment] 2015-08-24 12:28
made firewall exceptions for everything hearthstone and hearthstone tracker, still laggy

**Comment by xyzXXXok** [comment] 2015-08-24 12:39
well i set a lot of exceptions for everything hearthstone related in both windows defender and firewall. it seems to run better, but still not perfect. so weird

**Comment by fridayfreak** [comment] 2015-08-24 19:22
fuck you epix37 you screwed my hearthstone up and you dont even have a own conclusion to your own fucking program. please fix this bullshit

**Comment by xyzXXXok** [comment] 2015-08-24 19:23
woa dude come down. what the hell

**Comment by Epix37** [comment] 2015-08-24 19:26
@fridayfreak [Breathe and read the FAQ](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#why-is-my-game-so-choppy--fps-so-low-after-using-hdt)

**Comment by fridayfreak** [comment] 2015-08-24 19:29
I dont freaking even have it left on my computer and the lag is still there :(

**Comment by xyzXXXok** [comment] 2015-08-24 19:31
just delete the log file in that folder:

C:\Users\YOURUSERNAME\AppData\Local\Blizzard\Hearthstone

That solution was mentioned before, you didn't have to insult the creater. we are trying to solve the problem.

**Comment by Jcrawford19** [comment] 2015-08-24 19:32
@fridayfreak The Hearthstone servers are experiencing some major lag due to the TGT release according to @playhearthstone's twitter https://twitter.com/PlayHearthstone/status/635861508413456384, this may be a related issue.

**Comment by Epix37** [comment] 2015-08-24 19:38
Can I assume that's it and remove this not so helpful part of the conversation?

**Comment by Jcrawford19** [comment] 2015-08-24 19:43
@Epix37 Golden Rule: only keep constructive conversations.

**Comment by burlamacco** [comment] 2015-08-25 08:36
i've solved setting the log file in read only after hearthstone has been lounched.
if you close ad open hearthstone it will make a new file so you'll have to set the new file again in read only.
i'll try the windows defender tip this evening.
sorry about my enginsh :)

**Comment by r3lik** [comment] 2015-08-27 21:41
the window defender "fix" as well as the read-only change did not improve anything for me.

**Comment by BobT36** [comment] 2015-08-29 02:17
Hmm is this a recent problem? I've only just started using it so it's hard for me to say, some threads reference this from months ago though. 

Do we think this may be an SSD related issue? (Obv to do with the logging itself). As my PC is a beasty x64, 4.2ghz I7 Hex core, 16GB RAM etc, but lags like shit with every action (attacking with a minion, playing a card etc), but no SSD. My girlfriend's PC that is far worse has an SSD, and she has no lag / choppiness at all.

Presuming I shouldn't have to exclude this in Windows Defender, if it is turned off? I'm using Norton Internet Security and have added the entire Blizzard folder to the Sonar Exclusion list.

**Comment by slowcom** [comment] 2015-08-30 02:34
I think it may be an SSD issue. Seems like everyone here has an SSD.


I've tried Hearthstone on my SSD and my Hybrid Drive. It was laggy on both
HDs. Making an exception in Windows Defender worked for me.

**Comment by BobT36** [comment] 2015-08-30 06:53
I don't have an SSD though, only a Sandisk Readycache (that makes my normal HD function like a hybrid). My girlfriend has a full SSD (for both hearthstone and windows) and it works like a charm. 

With windows defender, do you actually have it switched on? I have mine turned off as I use Norton. 


----- Reply message -----

**Comment by jmundi1704** [comment] 2015-08-30 08:29
Adding an exception to the Windows Defender seemed to alleviate the problem somewhat, but there is still noticeable stuttering (it is more playable though) and making the log read-only did not change anything for me. It seems that Windows Defender is only partly to blame, there seem to be something else that is adding to the load. If anyone else comes up with new ideas it would be awesome, because i would really love to be able to use the HDT :)

P.S. I have an SSD, but the game is installed on the HDD. The log file though IS on the SSD.

**Comment by andburn** [comment] 2015-08-30 11:02
@jmundi1704 How did you move the log file to SSD, did you use a symlink?

**Comment by BobT36** [comment] 2015-08-30 11:27
Probably has the OS on the SSD.

My GF has both OS and the game on it and has no problems. Using Norton same as me too 



----- Reply message -----

**Comment by jmundi1704** [comment] 2015-08-30 11:37
Yeah my OS is on the SSD and i have the game installed on the HDD

**Comment by Xalph** [comment] 2015-08-30 14:14
after disabling windows defender, the lag goes off, and i'm able to use Decktracker + Hearthstone together.
Might get another anti virus other than windows defender.

**Comment by BobT36** [comment] 2015-08-31 02:36
Here's my specs from the log, just in-case we have a similar system issue:

2015-08-31 03:20:18.348: SystemInfo - Device Model: Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz (16337 MB)
2015-08-31 03:20:18.358: SystemInfo - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
2015-08-31 03:20:18.368: SystemInfo - CPU Type: Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz
2015-08-31 03:20:18.377: SystemInfo - CPU Cores: 12
2015-08-31 03:20:18.386: SystemInfo - System Memory: 16337
2015-08-31 03:20:18.395: SystemInfo - Screen Resolution: 1920x1080
2015-08-31 03:20:18.405: SystemInfo - Screen DPI: 96
2015-08-31 03:20:18.414: SystemInfo - GPU ID: 4232
2015-08-31 03:20:18.422: SystemInfo - GPU Name: NVIDIA GeForce GTX 590
2015-08-31 03:20:18.431: SystemInfo - GPU Vendor: NVIDIA
2015-08-31 03:20:18.440: SystemInfo - GPU Memory: 1489
2015-08-31 03:20:18.449: SystemInfo - GPU Shader Level: 30
2015-08-31 03:20:18.458: SystemInfo - GPU NPOT Support: Full
2015-08-31 03:20:18.466: SystemInfo - Graphics API: Direct3D 9.0c [nvd3dum.dll 9.18.13.5306]
2015-08-31 03:20:18.476: SystemInfo - Graphics Supported Render Target Count: 4
2015-08-31 03:20:18.486: SystemInfo - Graphics Supports 3D Textures: True
2015-08-31 03:20:18.495: SystemInfo - Graphics Supports Compute Shaders: False
2015-08-31 03:20:18.504: SystemInfo - Graphics Supports Image Effects: True
2015-08-31 03:20:18.513: SystemInfo - Graphics Supports Render Textures: True
2015-08-31 03:20:18.523: SystemInfo - Graphics Supports Render To Cubemap: True
2015-08-31 03:20:18.532: SystemInfo - Graphics Supports Shadows: True
2015-08-31 03:20:18.541: SystemInfo - Graphics Supports Sparse Textures: False
2015-08-31 03:20:18.550: SystemInfo - Graphics Supports Stencil: 1
2015-08-31 03:20:18.559: SystemInfo - Graphics RenderTextureFormat.ARGBHalf: True
2015-08-31 03:20:18.569: SystemInfo - Graphics Metal Support: False

**Comment by andburn** [comment] 2015-08-31 09:14
AFAIK there are two log files, one where ever the OS is `%LocalAppData%\Blizzard\Hearthstone\Logs` and one where Hearthstone is installed `<Hearthstone_Install_Dir>\Hearthstone_Data\output_log.txt`. Maybe you need to exclude them both?

**Comment by jmundi1704** [comment] 2015-08-31 12:53
@andburn I excluded both. The stuttering is not completely gone, but i started using the app nonetheless. I can still feel a difference between not using the app and using it, but it's not so annoying so as to not use it. And it can't be an issue with my setup, because i am running the game on a PC that's way over its recommended specs. Doesn't matter, it's much better now after excluding the log file from Windows Defender so i'm half happy :)

**Comment by BobT36** [comment] 2015-08-31 19:02
I've excluded both logs in both Norton and Windows Defender (Though I have the latter disabled), I'm not sure but it may have felt there was a slight reduction in the lag, but there was still a noticeable 1-3 sec delay when hitting with a minion or performing an action. It's obviously affecting the FPS as I could actually regrow the vegetables on the Pandaria map! (There's a bug where if you're running >60fps or something, the veg never grows back, the water just keeps flowing. I have a 120FPS monitor so I could usually never do that heh).

CPU usage was 2-5% the entire time, and Physical memory at 45%, and that's with other apps running. 

Weird though that it's completely fine on my gfs machine. I thought it was because she has an SSD but others here say they have one and still have the issue. Here's her specs:

2015-08-31 18:33:40.907: SystemInfo - Device Model: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (8072 MB)
 2015-08-31 18:33:40.913: SystemInfo - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
 2015-08-31 18:33:40.914: SystemInfo - CPU Type: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
 2015-08-31 18:33:40.914: SystemInfo - CPU Cores: 4
 2015-08-31 18:33:40.915: SystemInfo - System Memory: 8072
 2015-08-31 18:33:40.916: SystemInfo - Screen Resolution: 1920x1080
 2015-08-31 18:33:40.923: SystemInfo - Screen DPI: 96
 2015-08-31 18:33:40.924: SystemInfo - GPU ID: 26648
 2015-08-31 18:33:40.925: SystemInfo - GPU Name: AMD Radeon HD 7800 Series
 2015-08-31 18:33:40.925: SystemInfo - GPU Vendor: ATI
 2015-08-31 18:33:40.926: SystemInfo - GPU Memory: 2027
 2015-08-31 18:33:40.927: SystemInfo - GPU Shader Level: 30
 2015-08-31 18:33:40.927: SystemInfo - GPU NPOT Support: Full
 2015-08-31 18:33:40.928: SystemInfo - Graphics API: Direct3D 9.0c [aticfx32.dll 8.17.10.1404]
 2015-08-31 18:33:40.929: SystemInfo - Graphics Supported Render Target Count: 4
 2015-08-31 18:33:40.930: SystemInfo - Graphics Supports 3D Textures: True
 2015-08-31 18:33:40.930: SystemInfo - Graphics Supports Compute Shaders: False
 2015-08-31 18:33:40.931: SystemInfo - Graphics Supports Image Effects: True
 2015-08-31 18:33:40.932: SystemInfo - Graphics Supports Render Textures: True
 2015-08-31 18:33:40.932: SystemInfo - Graphics Supports Render To Cubemap: True
 2015-08-31 18:33:40.933: SystemInfo - Graphics Supports Shadows: True
 2015-08-31 18:33:40.934: SystemInfo - Graphics Supports Sparse Textures: False
 2015-08-31 18:33:40.934: SystemInfo - Graphics Supports Stencil: 1
 2015-08-31 18:33:40.935: SystemInfo - Graphics RenderTextureFormat.ARGBHalf: True
 2015-08-31 18:33:40.936: SystemInfo - Graphics Metal Support: False
Antivirus: Norton Internet Security
Harddrive: SSD. Standard speed, 4GB+ free space.

**Comment by Talhoo** [comment] 2015-09-01 11:42
You should address blizzard, cause it's their problem. You can recreate this problem without having the deck tracker. (by just enabling the log)

**Comment by Epix37** [comment] 2015-09-10 17:45
Should be fixed with v0.11.0 !

**Closed by Epix37** 2015-09-10 17:45 UTC
