### ISSUE TITLE
HDT constantly fails to record random wins or losses. Example: I finish 7-3, HDT says I'm 6-2

### ISSUE THREAD

**Issue by heywoody** [Epix37/Hearthstone-Deck-Tracker#1559] opened 2015-10-04 03:01 UTC
I rarely had this problem with previous versions of HDT.  I took a hiatus from Hearthstone from July-September, and when I returned a few weeks ago I updated HDT and now this problem occurs with literally every single arena run.  HDT works perfectly during games, tracking my cards and my opponent's cards.  But for some reason some games are not recorded as wins or losses upon their conclusion.  

Earlier this year, whenever this problem happened I'd simply add a "tag" to the arena run with the correct score, like "7-3" and HDT would almost immediately update the run with that score.  Now when the problem occurs, tags don't change the score.  Was the feature removed?  Why can't I change my arena score whenever HDT fails to record the result of a game? 

Does alt-tabbing out of the game cause this bug?  Sometimes I tab out but I always have the game maximized when the game ends, which is when the result (win or loss) should be recorded.  But HDT still misses some games with no rhyme or reason why.  

I love HDT though.  Thanks for all the work you do on it!

**Comment by riQQ** [comment] 2015-10-04 08:22
Maybe you weren't leaving the end game screen fast enough. The games aren't recorded until you leave the end game screen and return to the menus. HDT waits 5 minutes for this to happen and discards the game if it doesn't.

**Comment by veri745** [comment] 2015-10-04 14:58
I would guess this is related to #1478

**Comment by heywoody** [comment] 2015-10-04 21:11
"Maybe you weren't leaving the end game screen fast enough. The games aren't recorded until you leave the end game screen and return to the menus."

Are you referring to the "Victory" screen?  I always immediately click out of that, and return to the main Arena screen.  

"I would guess this is related to #1478"

I saw on reddit people saying this bug was fixed in Hearthstone, but honestly I've no idea.  I never noticed the bug (last played opponent missing) in the first place.

**Comment by megablue** [comment] 2015-10-05 18:40
it happens to me as well. my arena win rate is pretty much a mess since it fails to record some of match results and it was too late until i realized it. It is still here even with the latest version.

**Comment by Epix37** [comment] 2015-10-05 18:59
Might be fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/c16afb7f4754b71ea0d6eb8bbf9995b2e554680a

**Comment by trigunflame** [comment] 2015-10-05 22:06
If so, please push a new build asap. I've lost multiple games at random because of whatever this may be and it never used to happen.

**Comment by Epix37** [comment] 2015-10-06 18:51
Please give this version a shot and let me know if you still experience the issue:
https://github.com/Epix37/HDT-Test/releases/tag/v0.11.5PRE1

**Comment by veri745** [comment] 2015-10-07 05:28
The very first game I played using 11.5PRE1 was a ranked game, got marked as casual.

http://pastebin.com/tZpA3TwN

I did not close/restart Hearthstone before loading it up, though.  I will do that and continue testing

**Comment by veri745** [comment] 2015-10-07 06:05
Third time's a charm: game not detected.  

http://pastebin.com/65YxnrGG

Log files:
http://www63.zippyshare.com/v/igjGtHYQ/file.html

Also, the overlay didn't from that game go away after the game ended, it still appears at the main menu

**Comment by Epix37** [comment] 2015-10-07 06:39
the first one is another issue entirely, ranked detection should hopefully be fixed soon

As for the other two: the problem seems to be that it fails to detect when the game enters the menu again - no idea why though, it's definitely in the log. I had this issue before but was not able to reproduce it after restarting HDT and HS.

**Comment by Epix37** [comment] 2015-10-12 09:54
Hopefully fixed with v0.12.0. Please let me know if it still happens.

**Closed by Epix37** 2015-10-12 09:54 UTC
Labels: bug, testers wanted
