### ISSUE TITLE
[Idea] Advanced card statistics

### ISSUE THREAD

**Issue by banksee** [Epix37/Hearthstone-Deck-Tracker#481] opened 2014-12-22 06:39 UTC
Hello! My name is Denis and I'm really enjoying your app. When I'm playing this game, I try to write down some statistics or analysis for each card, for example: my Chillwing Yeti killed 2 guys that cost my opponent 6 mana in total etc. Is there a way to include this feature? Thx for your time, cheers!

**Comment by Epix37** [comment] 2016-03-31 21:48
Dupe of #446

**Closed by Epix37** 2016-03-31 21:48 UTC
Labels: enhancement, stats
