### ISSUE TITLE
Player Deck overlay not showing when starting minimized

### ISSUE THREAD

**Issue by Xilef11** [Epix37/Hearthstone-Deck-Tracker#808] opened 2015-03-20 16:24 UTC
When the tracker is started minimized (to tray) , the overlay for the player's deck does not appear until the main tracker window is opened, after which it can be minimized again without breaking anything.
I am not sure if it is a problem with the overlay or with the tracking, or if it also happens when the tracker starts minimized in the task bar instead of system tray.
using v0.9.7

**Comment by Epix37** [comment] 2015-03-21 07:28
Do you mean the player deck window or the actual overlay?

**Comment by Xilef11** [comment] 2015-03-23 23:12
the overlay, but only the player's deck is not showing.
![sans titre](https://cloud.githubusercontent.com/assets/8212678/6792657/7c4ae916-d190-11e4-91db-85d28972cefd.jpg)
(card age, marks and timers are not enabled in this screenshot)

**Comment by Epix37** [comment] 2015-03-28 17:31
I'm not able to reproduce this at all. All combinations of minimized, minimzed to tray, starting HS first, starting tracker fist, in game and in menu work fine for me. 

(I'm using the dev build obviously, so I could have unintentinally fixed this already)

**Comment by Xilef11** [comment] 2015-03-29 19:30
Interesting... I guess I'll wait for the next release to see if it's fixed

**Comment by Xilef11** [comment] 2015-04-04 22:06
It still happens on V 0.9.10... I am also starting HearthStone in fullscreen,

**Comment by Epix37** [comment] 2015-04-04 22:20
I think I may have had a very similar issue all day long without realizing it. 

When HDT is started after hearthstone, the overlay does not update until you click out of hearthstone and back in again once (not necessarily into the main HDT window).

I have a strong feeling this is related. (If so, it's fixed now)

**Comment by askarmuk** [comment] 2015-04-06 09:36
I will post here now. I downloaded Prerelease 1 v0.10.0 but bug it still here. Before changing option:
![hs - no cards](https://cloud.githubusercontent.com/assets/8628595/7002799/da0e366e-dc69-11e4-8b8f-81b9f1fe486d.jpg)

After chose 'Use no deck':
![hs - after choosing use no deck in main window](https://cloud.githubusercontent.com/assets/8628595/7002800/e3ff05cc-dc69-11e4-95af-0214cfe31550.jpg)

How can I check that HDT was updated? It still has version 0.9.10.

**Comment by Epix37** [comment] 2015-04-06 10:01
Could you send the config.xml found in `%AppData%/HearthstoneDeckTracker` (Win+R, paste) to epikz37@gmail.com ? Even following your steps I can't reproduce this. Maybe there's some specific setting that causes this.

**Comment by Epix37** [comment] 2015-04-06 14:27
I know what the problem is now, just not yet how to fix it.

If you look at the hand marks in the first image, they are off to the right. The overlay is quite a bit wider than the acutal window, causing the deck to be outside of it. Opening the tracker (or any other window should work, too) and back into hearthstone, updates the size.

**Comment by Epix37** [comment] 2015-04-06 14:32
Maybe we can isolate the issue a bit:

Does this happen with 
1) a deck selected on HDT start
2) no deck selected on HDT start
3) HDT started before hearthstone
4) HDT started after hearthstone
5) *Actually* only when starting with windows

**Comment by Xilef11** [comment] 2015-04-06 23:21
I tried turning on the card marks, and I can confirm that the problem is the width of the overlay. It happens only when HDT is started minimized (perhaps to tray only?). It does not seem to matter if HDT is started with Windows or not, if a deck is selected, or if it is started before or after Hearthstone. Also, opening a window other than the tracker window does not solve the problem.

**Comment by Epix37** [comment] 2015-04-07 05:29
This *very* much sounds like it's a DPI problem. (please be a DPI problem!)
Try prerelease 4 here: https://github.com/Epix37/HDT-Test/releases

**Comment by askarmuk** [comment] 2015-04-07 13:11
It works correctly for me now with PR4.

**Comment by Xilef11** [comment] 2015-04-07 13:29
Prerelease 4 fixes it for me too. Also, I should have thought about it earlier, but I did change Windows' DPI settings to make things a bit larger... that might explain why it only happened on some systems

**Comment by Xilef11** [comment] 2015-04-07 13:30
Prerelease 4 fixes it for me too. Also, I should have thought about it earlier, but I did change Windows' DPI settings to make things a bit larger... that might explain why it only happened on some systems

**Closed** 2015-09-15 07:56 UTC
Labels: bug, can't reproduce
