### ISSUE TITLE
Hearthstone Deck tracker won't start

### ISSUE THREAD

**Issue by Behead** [Epix37/Hearthstone-Deck-Tracker#770] opened 2015-03-10 00:08 UTC
########## 2015-03-09 20:03:10 ##########
System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'Hearthstone_Deck_Tracker.MainWindow' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\Users\Olivier\AppData\Roaming\HearthstoneDeckTracker\config.xml' est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append)
   à Hearthstone_Deck_Tracker.Config.Load()
   à Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   à System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   à System.Windows.Application.DoStartup()
   à System.Windows.Application.<.ctor>b__1(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 2015-03-09 20:03:19 ##########
System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'Hearthstone_Deck_Tracker.MainWindow' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\Users\Olivier\AppData\Roaming\HearthstoneDeckTracker\config.xml' est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append)
   à Hearthstone_Deck_Tracker.Config.Load()
   à Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   à System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   à System.Windows.Application.DoStartup()
   à System.Windows.Application.<.ctor>b__1(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Behead** [comment] 2015-03-10 00:20
I try to start it and it automatically crashes. I went in AppData and the HearthstoneDeckTracker file is empty!

**Comment by dvide** [comment] 2015-03-10 00:32
Try closing HearthstoneDeckTracker and deleting the config.xml file it refers to in %AppData%/HearthstoneDeckTracker, then reopen HDT. It should recreate the file with default settings. It sounds like perhaps the permissions on that file have messed up for some reason.

**Comment by dvide** [comment] 2015-03-10 00:51
Probably related to #621 and #609. Looks like it's an anti-virus issue.

**Comment by Behead** [comment] 2015-03-10 01:19
This HDT folder in AppData exists, but is empty. I can't find the config.xml file. It seemed to me that it was AV related, but when I turned it off, it still didn't work.

**Comment by dvide** [comment] 2015-03-10 01:38
Maybe the AV changed the permissions on the folder, so even if you turn it off the problem remains. Can you go into your AV and see if you can find a reference to HDT and then unblock it or exclude it. It might free up the folder then. Do you use Bitdefender btw?

**Comment by Behead** [comment] 2015-03-10 01:40
I do, I changed from Norton to that this weekend and it was the worst decision of my life. I tried to look up how to do this, but Bitedefender seems so secure, you can't even restore from quarantine and I had to download HTD three times because BD messed up with it...

**Comment by dvide** [comment] 2015-03-10 01:42
lol oh dear :(

**Comment by Behead** [comment] 2015-03-10 01:45
What is strange though is that I disabled the AV, deleted the folder in AppData, redownloaded and it still doesn't work.

**Comment by dvide** [comment] 2015-03-10 01:47
That is strange. Does it recreate the folder and then crash the same as before? Not sure what to suggest, maybe @Epix37 will have some idea.

**Comment by Behead** [comment] 2015-03-10 01:48
It does, it recreates the folder, then it crashes, leaving the folder empty. I was so excited to learn about this exe, I really hope he does! :)

**Comment by dvide** [comment] 2015-03-10 01:55
What does it look like for you if you right-click on the AppAata HearthstoneDeckTracker folder and then go to Properties > Security tab, then click Advanced. Not that this would really help with anything I think, but I'm curious. This is what mine looks like:

![untitled](https://cloud.githubusercontent.com/assets/180188/6567999/88cfa938-c6c8-11e4-83ec-7416e1708d5f.jpg)

**Comment by Cu8eR** [comment] 2015-03-15 15:25
I cannot reproduce it

**Closed** 2015-04-01 05:28 UTC
