### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Atebitss** [Epix37/Hearthstone-Deck-Tracker#1274] opened 2015-08-19 16:38 UTC
Installed this earlier, had some issues but restarting hearthstone seemed to fix a lot of them, but one issue that isn't going, is lag, while the program is open, Hearthstone drops from 100 fps to about 5fps

**Comment by MechaLynx** [comment] 2015-08-19 16:47
Try turning Aero off and see if it keeps lagging like that.

**Comment by STORRM** [comment] 2015-08-19 23:44
think hearthstones capped at 30-60FPS so theres no way it was running at 100 unless you messed with the config files. i have seen some reports of the log files making the game choppy, on the battle net forums,  there are quite a few of posts to do with log files, simple test would be to remove it and see if that fixes it. i had crazy lag after the patch but its totally fine now. also try looking in setting, when i had force hide friend list turned forced on it was doing weird stuff. also try opening tracker before hearthstone/ restarting the computer.

**Comment by xyzXXXok** [comment] 2015-08-20 13:12
I'm having the same problems and can't get around it. only solution is deleting the log file but that basically means you can't use the tracker.

**Comment by Epix37** [comment] 2015-08-20 13:21
That's a differnet problem then. 
If the FPS only drop while HDT is running then it's some likely something that can be fixed (Aero).
If the game is laggy after using HDT, no matter if HDT is running or not, means it's the log file. This one there is nothing we can do about. As you said, removing the log.config, is the only way.

**Comment by xyzXXXok** [comment] 2015-08-20 13:25
yeah, well i know you're not responsible or anything, I just kinda wanna solve it. It was working a while back and now it doesn't anymore. 
If you (or anyone else) have any ideas to what might cause this, it would be very much appreciated by me and I'm sure a lot of other people with the same issue also.

thanks for making a great tool for hearthstone (I really wanna use it too :( )

**Comment by Neppord** [comment] 2015-08-20 13:49
@xyzXXXok might it be that your harddrive is overloaded? Defragmented or almost full? Or do you have any scanning program like antivirus software that is scanning the file aswell?

**Comment by xyzXXXok** [comment] 2015-08-20 14:06
Is there a way i can put the logfile somewhere else so i can test if its related to the harddrive? dont think its anti virus software, but it could be a virus/ malware that slows my main hard drive.

**Comment by Epix37** [comment] 2015-08-20 14:08
The file causing this is the output_log.txt found in Hearthstone/Hearthstone_Data. Installing Hearthstone somewhere else would be the way of moving it.

(The log.config makes it so Hearthstone generates the output_log)

**Comment by xyzXXXok** [comment] 2015-08-20 14:11
reinstalling.. if this works ...omg

**Comment by xyzXXXok** [comment] 2015-08-20 14:46
yep, still, even on a other hard drive. every interaction causes the game to drop frames. (like crazy) 

any other ideas?

Btw: I had the same problem with the "Track-o-Bot"-Tracker but not with "hearthstonedecktracker.com"

So my assumtion is that the problem is related to the card tracking in particular. (well i guess you knew that already)

**Comment by Epix37** [comment] 2015-08-20 22:08
It's not any perticular features that is causing this, it is the fact that hearthstone debug logging is turned on (which HDT is completely based on).

**Comment by STORRM** [comment] 2015-08-21 03:15
i have HS installed on a SSD and didn't have any problems with HDT until the most resent HS patch, some times i barely noticeable it other times its very noticeable, a restart of my PC fix's it most of the time tho. i wounder if something changed in HS debugger in 3.0 thats made it worse. pretty sure its the log file coz its when my op draws a card or something dies i get a hiccup but the frame rate is still fine. i did also just go from AMD to nivda for a GPU. so many small hard wear reasons could be why some ppl have the problem and others dont.

**Comment by STORRM** [comment] 2015-08-21 05:01
after cutting log.config out of Windows: C:\Users\YOURUSER\AppData\Local\Blizzard\Hearthstone and pasting it to desktop all the hiccups are gone, looking at the log files there really writing a lot of unneeded guff, would be cool if the devs mad a API for modders/ HDT type things but i dont think they ever will. i kinda wont to know it me changing from a AMD card to a nivda one is what mad it choppy or if its really just the 3.0 update. looking at the rate it writes data my system should have no problem with it at all.

**Comment by xyzXXXok** [comment] 2015-08-21 11:10
I wonder what the update did that is causing the hickups.

**Comment by Epix37** [comment] 2015-08-21 11:55
lots of redundant logging was added

**Comment by STORRM** [comment] 2015-08-22 08:23
ok so the question i have is what logging can we turn off and still have card drawn/ op cards played. because that's all i need. i only need to keep track of op cards played coz i ult tab a lot, and i like to know whats still in my deck while doing other stuff. i don't need replays card marks est est as long as i can have my deck and my ops played cards. what can be set to false [ Zone] [ Bob ] [ Power ] [ Asset ] [ Rachelle ] and still have the track some what work? like it looks like zone by its self can show whats in your hand just looking at the log file.

**Comment by STORRM** [comment] 2015-08-22 09:15
i bit of testing later and setting [ Power ] to false resolves 98% of the problem

**Comment by Epix37** [comment] 2015-08-23 08:53
The ones having problems: what graphics cards are you using?

**Comment by xyzXXXok** [comment] 2015-08-23 11:36
ATI 6800HD. 
I tried seting power to false, it is less laggy, yes, but still noticiable to a point were i prefer not to play it like that.

**Comment by Epix37** [comment] 2015-08-23 15:46
Give this a shot: https://www.reddit.com/r/hearthstone/comments/3hjxg0/does_anyone_experience_problems_with_windows_10/cuafv6n?context=3

**Comment by xyzXXXok** [comment] 2015-08-23 15:52
doesn't work. lag is still there.

**Comment by Epix37** [comment] 2015-08-23 16:11
Maybe try also excluding "... /Hearthstone/Hearthstone_Data"

**Comment by xyzXXXok** [comment] 2015-08-23 16:12
no, tried that too, didn't work either. :(

**Comment by Atebitss** [comment] 2015-08-23 17:28
Why would Graphics Cards effect it?  Im using a GTX 650 atm but upgrading to 960 next week

**Comment by Epix37** [comment] 2015-08-23 17:35
Probably just a weird coincidence we found,  but who knows.

**Comment by r3lik** [comment] 2015-08-23 21:42
still happening. I noticed that it does not happen on my MAC OSX machine. Must be something with Windows.

**Comment by BobT36** [comment] 2015-08-29 02:16
Hmm is this a recent problem? I've only just started using it so it's hard for me to say, some threads reference this from months ago though. 

Do we think this may be an SSD related issue? (Obv to do with the logging itself). As my PC is a beasty x64, 4.2ghz I7 Hex core, 16GB RAM etc, but lags like shit with every action (attacking with a minion, playing a card etc), but no SSD. My girlfriend's PC that is far worse has an SSD, and she has no lag / choppiness at all.

**Comment by STORRM** [comment] 2015-08-29 22:06
imo with the testing i have done its the game thats stuttering as its out putting the logs not the system its self, so it doesn't matter how OP the hardware is. yes its been around forever for some ppl but got a lot worse with 3.0. try playing a game in casual seeing if you have stuttering then opening a pack and see if you still have stuttering, that oddly fixs it for me atm as long as i dont close and reopen HS.  at some point it would be nice to do a poll for what hard wear ppl have and OS softer running in the background to try and work out some common ground.

**Comment by BobT36** [comment] 2015-08-31 02:36
Here's my specs from the log, just in-case we have a similar system issue:

2015-08-31 03:20:18.348: SystemInfo - Device Model: Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz (16337 MB)
2015-08-31 03:20:18.358: SystemInfo - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
2015-08-31 03:20:18.368: SystemInfo - CPU Type: Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz
2015-08-31 03:20:18.377: SystemInfo - CPU Cores: 12
2015-08-31 03:20:18.386: SystemInfo - System Memory: 16337
2015-08-31 03:20:18.395: SystemInfo - Screen Resolution: 1920x1080
2015-08-31 03:20:18.405: SystemInfo - Screen DPI: 96
2015-08-31 03:20:18.414: SystemInfo - GPU ID: 4232
2015-08-31 03:20:18.422: SystemInfo - GPU Name: NVIDIA GeForce GTX 590
2015-08-31 03:20:18.431: SystemInfo - GPU Vendor: NVIDIA
2015-08-31 03:20:18.440: SystemInfo - GPU Memory: 1489
2015-08-31 03:20:18.449: SystemInfo - GPU Shader Level: 30
2015-08-31 03:20:18.458: SystemInfo - GPU NPOT Support: Full
2015-08-31 03:20:18.466: SystemInfo - Graphics API: Direct3D 9.0c [nvd3dum.dll 9.18.13.5306]
2015-08-31 03:20:18.476: SystemInfo - Graphics Supported Render Target Count: 4
2015-08-31 03:20:18.486: SystemInfo - Graphics Supports 3D Textures: True
2015-08-31 03:20:18.495: SystemInfo - Graphics Supports Compute Shaders: False
2015-08-31 03:20:18.504: SystemInfo - Graphics Supports Image Effects: True
2015-08-31 03:20:18.513: SystemInfo - Graphics Supports Render Textures: True
2015-08-31 03:20:18.523: SystemInfo - Graphics Supports Render To Cubemap: True
2015-08-31 03:20:18.532: SystemInfo - Graphics Supports Shadows: True
2015-08-31 03:20:18.541: SystemInfo - Graphics Supports Sparse Textures: False
2015-08-31 03:20:18.550: SystemInfo - Graphics Supports Stencil: 1
2015-08-31 03:20:18.559: SystemInfo - Graphics RenderTextureFormat.ARGBHalf: True
2015-08-31 03:20:18.569: SystemInfo - Graphics Metal Support: False

**Comment by BobT36** [comment] 2015-08-31 05:17
STORRM, I've just verified that opening a pack doesn't help anything. 

I bought a pack, played an innkeeper game, verified I had the lag. Opened my pack, then tried again (without closing HS), still had the lag. 

Again, this is COMPLETELY FINE on my girlfriend's PC, though she has both HS and the log running on her SSD. Same windows version, and less powerful hardware than mine. I'll try post her specs tomorrow.

**Comment by STORRM** [comment] 2015-08-31 18:23
may stuttering lag has been pretty low last few days its odd how it comes and goes for me.
590 is a pretty rear card i wounder if HS just isn't optimized for some hard wear.
other then both being on nvida cards and being on win7 sp 1 i dont see any thing as first glance


2015-08-31 16:33:18.045: SystemInfo - Device Model: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (8148 MB)
2015-08-31 16:33:18.048: SystemInfo - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
2015-08-31 16:33:18.051: SystemInfo - CPU Type: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
2015-08-31 16:33:18.054: SystemInfo - CPU Cores: 4
2015-08-31 16:33:18.056: SystemInfo - System Memory: 8148
2015-08-31 16:33:18.058: SystemInfo - Screen Resolution: 1920x1080
2015-08-31 16:33:18.062: SystemInfo - Screen DPI: 96
2015-08-31 16:33:18.065: SystemInfo - GPU ID: 4483
2015-08-31 16:33:18.067: SystemInfo - GPU Name: NVIDIA GeForce GTX 660 Ti
2015-08-31 16:33:18.070: SystemInfo - GPU Vendor: NVIDIA
2015-08-31 16:33:18.072: SystemInfo - GPU Memory: 1989
2015-08-31 16:33:18.074: SystemInfo - GPU Shader Level: 30
2015-08-31 16:33:18.077: SystemInfo - GPU NPOT Support: Full
2015-08-31 16:33:18.080: SystemInfo - Graphics API: Direct3D 9.0c [nvd3dum.dll 10.18.13.5560]
2015-08-31 16:33:18.082: SystemInfo - Graphics Supported Render Target Count: 4
2015-08-31 16:33:18.085: SystemInfo - Graphics Supports 3D Textures: True
2015-08-31 16:33:18.088: SystemInfo - Graphics Supports Compute Shaders: False
2015-08-31 16:33:18.090: SystemInfo - Graphics Supports Image Effects: True
2015-08-31 16:33:18.092: SystemInfo - Graphics Supports Render Textures: True
2015-08-31 16:33:18.095: SystemInfo - Graphics Supports Render To Cubemap: True
2015-08-31 16:33:18.097: SystemInfo - Graphics Supports Shadows: True
2015-08-31 16:33:18.100: SystemInfo - Graphics Supports Sparse Textures: False
2015-08-31 16:33:18.102: SystemInfo - Graphics Supports Stencil: 1
2015-08-31 16:33:18.105: SystemInfo - Graphics RenderTextureFormat.ARGBHalf: True
2015-08-31 16:33:18.107: SystemInfo - Graphics Metal Support: False
2015-08-31 16:33:18.316: UberText LoadCachedData() failed: Arg_InsufficientSpace
Parameter name: chars

**Comment by STORRM** [comment] 2015-08-31 18:33
really if its super bad i would just cute the log.config from app data and past it on desktop and play HS with out HDT tracking for a while, you can past it back later if you wont the tracking. i added C:\Users\*yoursystemname*\AppData\Local\Blizzard\Hearthstone to my Libraries so its easy to get to. i would be interested to see if every one with the problem is on Windows 7 Service Pack 1 (6.1.7601) 64bit or is that just the common one every one has.

**Comment by xyzXXXok** [comment] 2015-08-31 18:39
actually my specs are in every aspect different to yours (except the intel cpu, but its a different model) and i have the same issues. i dont even run windows 7, i run 10.

**Comment by BobT36** [comment] 2015-08-31 18:43
Meh it's getting on a bit now, but 3gb vram (2 chips on the one card), and it still runs everything I've threw at it on ultra. My monitor is 120fps too and I always get a decent framerate. 

Still though this is to do with HS itself, not graphical issues, it's purely the logging that's the problem. And yeah for now I've just disabled the logging and running without the tracker. Shame though as it's really good.

Weird though that it's completely fine on my gfs machine. I thought it was because she has an SSD but others here say they have one and still have the issue. Here's her specs:

2015-08-31 18:33:40.907: SystemInfo - Device Model: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (8072 MB)
2015-08-31 18:33:40.913: SystemInfo - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
2015-08-31 18:33:40.914: SystemInfo - CPU Type: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
2015-08-31 18:33:40.914: SystemInfo - CPU Cores: 4
2015-08-31 18:33:40.915: SystemInfo - System Memory: 8072
2015-08-31 18:33:40.916: SystemInfo - Screen Resolution: 1920x1080
2015-08-31 18:33:40.923: SystemInfo - Screen DPI: 96
2015-08-31 18:33:40.924: SystemInfo - GPU ID: 26648
2015-08-31 18:33:40.925: SystemInfo - GPU Name: AMD Radeon HD 7800 Series
2015-08-31 18:33:40.925: SystemInfo - GPU Vendor: ATI
2015-08-31 18:33:40.926: SystemInfo - GPU Memory: 2027
2015-08-31 18:33:40.927: SystemInfo - GPU Shader Level: 30
2015-08-31 18:33:40.927: SystemInfo - GPU NPOT Support: Full
2015-08-31 18:33:40.928: SystemInfo - Graphics API: Direct3D 9.0c [aticfx32.dll 8.17.10.1404]
2015-08-31 18:33:40.929: SystemInfo - Graphics Supported Render Target Count: 4
2015-08-31 18:33:40.930: SystemInfo - Graphics Supports 3D Textures: True
2015-08-31 18:33:40.930: SystemInfo - Graphics Supports Compute Shaders: False
2015-08-31 18:33:40.931: SystemInfo - Graphics Supports Image Effects: True
2015-08-31 18:33:40.932: SystemInfo - Graphics Supports Render Textures: True
2015-08-31 18:33:40.932: SystemInfo - Graphics Supports Render To Cubemap: True
2015-08-31 18:33:40.933: SystemInfo - Graphics Supports Shadows: True
2015-08-31 18:33:40.934: SystemInfo - Graphics Supports Sparse Textures: False
2015-08-31 18:33:40.934: SystemInfo - Graphics Supports Stencil: 1
2015-08-31 18:33:40.935: SystemInfo - Graphics RenderTextureFormat.ARGBHalf: True
2015-08-31 18:33:40.936: SystemInfo - Graphics Metal Support: False
Antivirus: Norton Internet Security
Harddrive: SSD. Standard speed, 4GB+ free space.

**Comment by STORRM** [comment] 2015-09-01 04:46
lol when i was on 7800 Series i had no problem at all..... if the timing was a little different i would have more useful info to bad the card died, would be cool to swap it in to my system now and see if the problem goes away altogether. im really not sure this is ever going to be fixed with out some blizzard devs helping. if there was different logging levels it would really help to cut down on guff.

**Comment by BobT36** [comment] 2015-09-01 18:13
That would help a lot. Can't see why they can't have a "combat" log, and "debug" log setting. 

Yeah logging isn't officially supported for what we're using it for, but considering how popular deck trackers and the like are with streamers, it would be silly for them to ignore it.

**Comment by STORRM** [comment] 2015-09-01 18:56
well they did leave under taker with out nerf for 6 months, spectating came after a year+ of ppl asking.... blizzard time is "TM soon" . more well know streams have picked HDT up in the last few weeks so maybe thers hope of them looking at it like a real problem in 6 months to a year, would be nice if the logging showed why the logging was braking the game for some and not all.

**Comment by irufus** [comment] 2015-09-02 03:31
@Epix37 Have you considered increasing the buffer size of the FileStream to 8192? 

I think the issue could be the default buffer size is not big enough for reading the log which would cause more read IO than normal. I assume the majority of the performance problems are stemming from File IO operations which make any system and application seem like it is "lagging". 

I ran some tests using similar code to read the file using .ReadToEnd() and saw a decrease in IO reads from my testing application. I also tried decreasing the buffer size to see and was able to reproduce the lag users were probably experiencing.

I will try testing increasing the buffer size in HDT as well.

**Comment by irufus** [comment] 2015-09-02 03:55
Just tried 16kb and it seem to work flawlessly. I didn't get the micro-stutter like I did with the default buffer size.

**Comment by STORRM** [comment] 2015-09-02 09:41
@irufus so this is something you do to the whole computer as a whole or just for HS? googling ReadToEnd dosnt help me understand how to do something on my end im not a coder. BobT36 problem is worse then mine, so him testing to see if this is a fix is more relevant then me. but maybe you can explain a simple way i can test to see if it makes a difference with out adding some thing to HDT its self, seeing as epix37 doesn't have the same problem.

**Comment by Epix37** [comment] 2015-09-02 10:06
If the problem persists without HDT running, how does changing the buffer size help? (If it actually *does* help while HDT is running, that's great)

**Comment by xyzXXXok** [comment] 2015-09-02 10:10
how do you do that? increasing the buffer i mean?

**Comment by Epix37** [comment] 2015-09-02 10:13
You can't at the moment. It's also nothing you can set "globally on your computer", it determins in what size chunks HDT reads the log file.

**Comment by STORRM** [comment] 2015-09-02 14:29
coz he said "I will try testing increasing the buffer size in HDT >as well<" i think he means HS or something related, im really not sure not something i have ever had to mess with before.

**Comment by BobT36** [comment] 2015-09-02 19:46
Stoorm, it's the lines of code that govern reading / writing data from the log files. It's to do with the code on either end, (HS and DT). 

I'd give it a go myself but my VS is too old to open the project. If any of you want to give me a compiled version, I'll give it a test. I'd hazard a guess though that it won't solve it completely unless Blizz also make the change on their end. 

I'm wondering if all those with SSDs having this issue, also don't have as good specs. My specs are good but no SSD. Whereas my GF specs are decent, and she has an SSD, and doesn't encounter any lag at all.

**Comment by r3lik** [comment] 2015-09-02 20:47
Bob,

I have an Intel 520 series SSD running on an i7 3770k, gtx 980ti, 16GB RAM and have this issue on both windows 7 and 10 x64. 
Has it been confirmed that the issue indeed exists with HS logging enabled, even when HDT isn't running ?

**Comment by BobT36** [comment] 2015-09-03 00:39
Heh, definitely not a bad hardware issue causing it when have SSD too then. 

And it seems to exist for me. Easy to check though, turn off HDT, (leaving the log in place) run hearthstone. 

Weird it only affects some people.

**Comment by irufus** [comment] 2015-09-03 01:14
@STORRM In the HDT application there is code the constantly loops to check for updates to the log file. Every time the file changes in size it will seek to the last position where we have read data and attempt to load the remaining data into HDT for analyzing (updating played cards, checking status of game, etc). This is done several times throughout game play. 


@Epix37 My theory is that ReadToEnd() would use additional read operations to read the log file if the buffer size is not sufficient. When I tried making the buffer as small as 256 bytes I did notice a huge drop off in performance which led me to believe this is probably what other users are encountering on PCS that do not have sufficient throughput due to other applications like Anti-virus software, Backup software or Windows Defender. (My Hearthstone log is running on a newly purchased 2TB drive which is not the operating system drive)

I'm going to try talking to the Unity community to see if anyone else has encountered logging issues impacting performance of their game(Since Hearthstone IS a Unity game)

**Comment by BobT36** [comment] 2015-09-03 01:54
Cheers Irifus. 

Can we give an increased buffer size a try?

**Comment by xyzXXXok** [comment] 2015-09-04 08:23
any progress? Are wer trying the buffer size in a upcoming update?

**Comment by Epix37** [comment] 2015-09-04 08:26
Probably, yes. 
**But** if you have the same issues without HDT running changing the buffer size will not do anything for you. And from what I understands that's the case for most?

**Comment by BobT36** [comment] 2015-09-07 19:43
Does v0.10.17  include this?

I understand that it's likely the HS logging that's the issue. However it would be good to give it a try with the buffer increased on this end too. 

Doubt Blizz will ever sort it, but at least we can badger them about it then.

**Comment by Epix37** [comment] 2015-09-07 20:56
Not yet. I will add that and upload a build for you guys to test tomorrow.

**Comment by Epix37** [comment] 2015-09-07 20:58
Also I need someone with the lag issues to try this: 
* open `log.config` in `%LocalAppData%/Blizzard/Hearthstone`
* for all the logging namespaces:  set `ConsolePrinting`to `false` and `FilePrinting` to `true`
* restart hearthstone and see if you still have the problems (HDT will not work)

(!!even if you have no problems, this might not actually be the solution!!)

**Comment by BobT36** [comment] 2015-09-07 21:38
Before change: It lags up 1-2 secs when playing a card, attacking, and when damage is dealt / minion dies. If I'm clicking too much then Windows thinks HS isn't responding. FPS is definitely affected as I can actually regrow the veg on the Pandaria map heh, (I usually have >60fps so there's a bug in HS where it doesn't regrow).

After change: As far as I can tell, there's now no FPS drop/lag at all! DT didn't show anything though as you mentioned.

Would be nice to test the buffer thing anyway, post back when you've put up a new version, cheers. (Disabled my Norton autoprotect too, but encountered no difference before changing those parameters).

Then again if fileprinting is on, and consoleprinting is off, doesn't that mean logging to the hard disk isn't actually the problem? (So write buffers wouldn't change that), for me at least.

Here's my log.config:
[Zone]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false

[Bob]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false

[Power]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false

[Asset]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false

[Rachelle]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false

[Arena]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false

**Comment by Epix37** [comment] 2015-09-07 21:45
`ConsolePrinting` creates the `Hearthstone_Data/output_out.txt` and `%LocalAppDaat%/Blizzard/Hearthstone/Logs/hearthstone_*.log` files, while `FilePrinting` creates separate logfiles for each namespace in `Hearthstone/Logs`.

**Comment by BobT36** [comment] 2015-09-07 21:47
Ahh I see, so it likely is those log files then. Hmm well it's narrowed it down at least.

**Comment by dvide** [comment] 2015-09-08 06:10
I did a few test games vs AI and recorded them @ 60fps so I can try to visually compare animation jerkiness. I tried every combination of ConsolePrinting, FilePrinting, or NoPrinting, with and without Windows Defender exclusions. I didn't have HDT running for any of the tests.

Here are the results (best to watch them at 60fps):
[ConsolePrinting NoExclusions 1](https://www.youtube.com/watch?v=4qsZeBvfFjY)
[ConsolePrinting NoExclusions 2](https://www.youtube.com/watch?v=46CUIQeDbw0)
[ConsolePrinting Exclusions 1](https://www.youtube.com/watch?v=LDWPXnDXdIk)
[ConsolePrinting Exclusions 2](https://www.youtube.com/watch?v=pJf3kL4Yn7Y)
[FilePrinting NoExclusions 1](https://www.youtube.com/watch?v=F6dISBPA2Ko)
[FilePrinting NoExclusions 2](https://www.youtube.com/watch?v=zbcR4wCKAQo)
[FilePrinting Exclusions](https://www.youtube.com/watch?v=d1BE5vxwqYQ)
[NoPrinting NoExclusions](https://www.youtube.com/watch?v=1qe0utXwXT0)
[NoPrinting Exclusions](https://www.youtube.com/watch?v=LPwkliFhw7M)

It seems that FilePrinting rather than ConsolePrinting definitely helps for me. The best should of course be NoPrinting, but FilePrinting Exclusions and even FilePrinting NoExclusions feel identical to that.

I think the Windows Defender exclusions did help too, but not by much. I thought that the exclusions didn't help at all before now, because I do still have noticable lag with ConsolePrinting Exclusions compared with NoPrinting. But when comparing the ConsolePrinting Exclusions videos with the ConsolePrinting NoExclusions videos, I do think it is better? Hard to tell though. I'm second guessing myself after watching them again. ConsolePrinting NoExclusions 1 seemed a bit worse than ConsolePrinting NoExclusions 2, so perhaps it's anomalous (for example, when I coined out the Fencing Coach on turn 2 it was particularly bad).

Here are the Windows Defender exclusions I used. Not sure if only one of these helps or multiple:
![exclusions](https://cloud.githubusercontent.com/assets/180188/9725035/1b52b6b2-55d8-11e5-817d-9dfa2d2f3f2b.png)

Windows 10 Pro
Intel Core i5 760
GTX 660 Ti
12GB RAM
No SSD

**Comment by BobT36** [comment] 2015-09-08 06:28
Interesting. Nice testing you did. I only excluded the Hearthstone and Log Files folders, from both Norton and Windows Def (though I have the latter switched off, and Norton doesn't seem to make a difference).

I had no lag at all with only FilePrinting on.

**Comment by Epix37** [comment] 2015-09-08 16:23
Implemented the new logger! 
Give this version a try: https://github.com/Epix37/HDT-Test/releases/tag/v0.10.18PRE2

It will automatically disabled ConsolePrinting and enable FilePrinting.
(if you go back to an old HDT version, you have to edit or delete the log.config)

Also very likely that there are still some bugs.

**Comment by BobT36** [comment] 2015-09-08 17:44
Thanks Epix, should there be an executable in this version? There isn't one in the zip.

**Comment by finally-fixed** [comment] 2015-09-08 19:02
this finally fixed it for me. disabling anti-virus etc did nothing for me but now the fps lag seems 99% gone. thanks a lot epix37

**Comment by BobT36** [comment] 2015-09-08 19:05
Looks to be working! Just played two games (innkeeper and play mode) with HDT on and working, and no visible lag! 

There was obviously still an FPS drop in general as I could regrow the veg in the pandaria map, however it didn't affect my play at all. 

So what's changed, Hearthstone was reading/writing to a single, huge log file (and you reading it) was causing the lag, we're now using multiple, smaller files and reading from those (with a larger buffer to accommodate too)?

**Comment by Epix37** [comment] 2015-09-08 19:12
Pretty much, yes. The logs created by ConsolePrinting contain a lot of clutter and are written in duplicate. 
Please play with that version a bit and see if you notice any problems. Things like draws/plays not being registered or it not resetting when it's supposed to, etc.

**Comment by xyzXXXok** [comment] 2015-09-08 20:01
thanks epix, it really seems like the lag is gone! Thank you very much!

Gonna report in how everything is working out, gonna stress test it ;)

(now i have to find a away to import my stats from hearthstonetracker ;) )

**Comment by BobT36** [comment] 2015-09-09 00:21
Aye thanks a lot mate, I'm betting this will solve it for the majority of cases. It's certainly 100% tolerable for me now, and I can now play with the veg XD

I'll give this version a play with and report any issues. Looked fine on my last game though.

**Comment by dvide** [comment] 2015-09-09 03:43
Wow cool, I'll have a go with this later. I mean to empty my quest log tonight so I'll have to play at least 8 games or so. I'll keep an eye out for anything that doesn't seem right. :+1:

**Comment by Epix37** [comment] 2015-09-09 09:47
Now released as beta update v0.10.18

**Comment by dvide** [comment] 2015-09-09 12:36
Sorry I haven't had a chance to test this yet. I'm excited to try it though.

**Comment by dvide** [comment] 2015-09-09 17:14
Played eight games and everything went well up to that point, but on the ninth game it stopped tracking after the opening cards were shown and before I chose which cards to mulligan.

The game didn't save in the stats when it was finished (probably because I have 'discard games with zero turns' on), though a replay was saved with just the those same opening cards shown, and then it ends. The replay also didn't pick up my name (i.e. the replay filename is: `(Priest) vs käften(Mage) 1721-090915.hdtreplay` rather than `dvide(Priest) vs käften(Mage) 1721-090915.hdtreplay`).

Interestingly the date created on the replay file itself is when the game actually ended, approx. 6 minutes later. So it didn't just save the replay file after the opening hand, thinking the game was already over.

Here's the video of the game (not that it shows much):
https://www.youtube.com/watch?v=AyrJXApxKv4

I'll send you the hdtreplay file by email and my log files from today's games.

Just noticed as well that the card counts are wrong whenever I'm going second. The count of the number of cards left in the deck is consistently 1 more than it should be. Looking at my recordings, it's always the case when I go second.Whenever I go first, it seems to be correct. It looks like the enemy card counts are fine when they go first or second.

The next game I tried also didn't track, before I closed the game. I lost the overlay altogether, but it came back when I turned off 'hide in menu' during the game. Not that it was tracking anything; just showing the deck I had active with all cards grayed out.

**Comment by dvide** [comment] 2015-09-09 17:22
I restarted the game without restarting HDT and now the game I'm in seems to be tracking again.

**Comment by Epix37** [comment] 2015-09-09 17:57
It seems the Power.log reader just stopped working while the rest of them continued on fine. Not sure what to make of that yet.

**Comment by Epix37** [comment] 2015-09-10 01:08
* Fixed the LogReader issue with v0.10.19 (77705c5)
* Fixed the deck count issue. Not in v0.10.19.

**Comment by BobT36** [comment] 2015-09-10 03:45
Using 0.10.19 atm and seems to be ok so far. Just played 1 game though and the gold tracker still says 0/3?

**Comment by dvide** [comment] 2015-09-10 04:32
Cool. So you think that this was caused by incorrect handling of non-ascii characters in my opponent's name? Actually the next game I played, where I said it also didn't track, my opponent had Cyrillic characters as well. So not sure if it just stopped working until I restarted the game or because they both just happened to have non-ascii characters. I imagine it's the former though.

**Comment by Epix37** [comment] 2015-09-10 08:25
@BobT36 Yea I think I messed that up with the new LogReader, gonna fix it today

@dvide I was able to reproduce it by setting the hearthstone client to chinese (card names are in the set language)

**Comment by dvide** [comment] 2015-09-10 08:26
@Epix37 That's good Epix, nice work :+1: everyone else worked fine and no stuttering.

**Comment by Epix37** [comment] 2015-09-10 09:47
You think it's stable enough for an actual release? I'm hesitant but I can't think of anything or find anything broken (related to the changes).

**Comment by dvide** [comment] 2015-09-10 11:08
It's up to you. I'd be hesitant as well with this kind of change. I'd be surprised if there's not some obscure race condition type problems or something. I want to play some more tonight as I still have some Rogue quests to do, so I intend to test it a little more then.

**Comment by Epix37** [comment] 2015-09-10 11:42
The chances of finding that are probably pretty slim, so best way might be to just release it. I've been trying to break it for about half an hour now with different HS languages, rapidly switching decks with auto selection on (at the start/end/middle of games...), no issues. UpdateDelay at 10ms and 2000ms seem to work fine so that's probably a good sign. 

Gonna play a few more games and then push it I think.

**Comment by dvide** [comment] 2015-09-10 11:58
Okay sounds good. This will help a lot of people I think :)

**Comment by Epix37** [comment] 2015-09-10 17:45
Should be fixed with v0.11.0 !

**Closed by Epix37** 2015-09-10 17:45 UTC

**Comment by brir420** [comment] 2015-10-05 12:20
(I'm using a mac). I'm not able to find the log.config file. The "application support/blizzard" folder is empty.  I downloaded the deck tracker yesterday, and maybe its a new version that is not using log.config. But still, I re-installed hearthstone and battle.net, and deleted the deck tracker, but nothing seem to work.

**Comment by Epix37** [comment] 2015-10-05 19:01
HDT does not support OSX, are you sure you are in the right github project?
