### ISSUE TITLE
Feature: Custom labels at game-time

### ISSUE THREAD

**Issue by rrwoods** [Epix37/Hearthstone-Deck-Tracker#954] opened 2015-05-11 06:57 UTC
I'd like to be able to record notes on my opponent's cards during the game, probably by clicking on the turn-number label (or the card itself) and typing, then the note could appear when I hover over the turn-number label.

**Comment by culinko** [comment] 2016-04-11 09:26
Duplicate of #596.

**Closed by culinko** 2016-04-11 09:26 UTC
Labels: enhancement
