### ISSUE TITLE
Cards sometimes appear with the "0" mark, indicating it was drawn at the start of the game, even when drawn on turn 10 and later

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1435] opened 2015-09-11 02:17 UTC
This happened earlier today, so I can't find the log for it unfortunately, but if someone else noticed this, then perhaps they can post one.

What happened was that I was playing an Arena game. After around turn 10, new cards drawn by the opponent had the "0" mark rather than 11, 12, etc. I think this happened after I played Master Jouster, although I'm not 100% certain.

HDT didn't save the game, too. Probably due to this bug.

**Comment by Epix37** [comment] 2015-09-11 05:16
It seems there are currently some server/connection issues with hearthstone, could be related to that.

**Comment by 305jeff** [comment] 2015-10-01 12:24
I've had this happening to me all week, at least. It does seem like after turn 10 it starts marking all cards as 0. Very disorienting!

**Comment by Cu8eR** [comment] 2015-11-03 15:17
Cannot reproduce

**Comment by Epix37** [comment] 2016-03-25 18:10
Should be fixed.

**Closed by Epix37** 2016-03-25 18:10 UTC
