### ISSUE TITLE
suggestion: create/edit deck on the fly

### ISSUE THREAD

**Issue by Xilef11** [Epix37/Hearthstone-Deck-Tracker#1568] opened 2015-10-06 01:13 UTC
I think it could be a nice "lazy" way to import decks to have an option to create a new deck in the "card not found in deck" menu, and the cards drawn would automatically be added to it. this would allow to keep stats for experimental decks when one dosen't want to manually import them, and over a few games, most cards should have been drawn (including some doubles), reducing the effort of importing.

**Comment by GiggliG** [comment] 2015-10-11 20:45
This is a neat idea.

**Comment by bajungadustin** [comment] 2016-03-21 03:44
life track addition.. i like it...
the only thing i see... is that say you changed 5 cards...
and the HDT finds one of those cards and his like "Hey yo... this isnt the deck i thought it was... whats going on"
then it gives you the option..
Use anyway
Use no Deck
Put Deck in Edit mode...

so you put the deck in edit mode.

and throughout teh next 4 or 5 games you only ever see 3 of those cards.
your deck would technically never be accurate until it saw every changed card.. and 
if you switched the count of a certain card from 1 to 2 or from 2 to 1 it would be really hard for it to figure that out.

i would like it if it could be done well.

**Comment by Epix37** [comment] 2016-04-11 07:24
Duplicate of #1410

**Closed by Epix37** 2016-04-11 07:24 UTC
Labels: enhancement
