### ISSUE TITLE
"Alert after X seconds" doesn't load value

### ISSUE THREAD

**Issue by davidschwegler** [Epix37/Hearthstone-Deck-Tracker#2048] opened 2016-01-30 22:53 UTC
Repro:
1. Options -> Tracker -> General -> "Alert after X seconds"
2. Change seconds from 30 to 15
3. Play game (will alert at 30 seconds,  not 15)

You can also:
3. Restart HDT
4. "Alert after X seconds" now says 30 again

**Comment by Epix37** [comment] 2016-01-31 08:24
>2. Change seconds from 30 to 15
3. Play game (will alert at 30 seconds, not 15)

I'm not able to reproduce this, sound plays at the correct time.

> You can also:
3. Restart HDT
4. "Alert after X seconds" now says 30 again

Value was not being loaded correctly, this is now fixed.

**Closed** 2016-02-17 22:17 UTC
Labels: bug
